(()=>{
let selectedTool='light',selectedNode='light',hslBand='Red';
const groups=document.createElement('div');groups.id='advancedControls';$('controls').after(groups);
const existing=[...$('controls').children];existing[0].dataset.toolgroup='light';existing[1].dataset.toolgroup='color';existing[2].dataset.toolgroup='effects';$('maskPanel').dataset.toolgroup='mask';$('crop').closest('details').dataset.toolgroup='frame';
function section(title,group,rows){const el=document.createElement('details');el.open=true;el.dataset.toolgroup=group;const summary=document.createElement('summary');summary.textContent=title;el.append(summary);for(const row of rows)el.append(slider(...row));groups.append(el);return el;}
const auto=document.createElement('button');auto.id='autoTone';auto.textContent='✧ Auto tone';auto.className='wide-button';existing[0].prepend(auto);auto.onclick=()=>{if(!img)return;const c=document.createElement('canvas');c.width=120;c.height=120;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,120,120);const d=ctx.getImageData(0,0,120,120).data,l=[];for(let i=0;i<d.length;i+=4)if(d[i+3])l.push((d[i]*.2126+d[i+1]*.7152+d[i+2]*.0722)/255);l.sort((a,b)=>a-b);if(!l.length)return;const median=l[Math.floor(l.length*.5)],high=l[Math.floor(l.length*.98)],low=l[Math.floor(l.length*.02)];mutate(()=>{settings.exposure=Math.max(-1.5,Math.min(1.5,Math.log2(.42/Math.max(.02,median))));settings.highlights=high>.9?-25:0;settings.shadows=low<.08?18:0;});};
const curve=section('Tone curve','light',[['curveBlack','Black point',0,40,1],['curveShadow','Shadows',-40,40,1],['curveMid','Midtones',-40,40,1],['curveHighlight','Highlights',-40,40,1],['curveWhite','White point',-40,0,1]]);const curveCanvas=document.createElement('canvas');curveCanvas.id='curveGraph';curveCanvas.width=256;curveCanvas.height=120;curve.children[0].after(curveCanvas);
const mixer=section('Color mixer · HSL','color',[]);const chips=document.createElement('div');chips.className='color-chips';mixer.append(chips);for(const [name,hue]of FX.colorBands){const button=document.createElement('button');button.title=name;button.setAttribute('aria-label','Mix '+name);button.style.setProperty('--chip','hsl('+hue+' 75% 56%)');button.onclick=()=>{hslBand=name;syncAdvanced();};chips.append(button);const set=document.createElement('div');set.dataset.band=name;for(const [suffix,label,min,max]of [['Hue','Hue shift',-45,45],['Sat','Saturation',-100,100],['Lum','Luminance',-100,100]])set.append(slider('hsl'+name+suffix,name+' · '+label,min,max,1));mixer.append(set);}
const grading=section('Color grading','color',[]);for(const [name,label]of [['Shadows','Shadows'],['Midtones','Midtones'],['Highlights','Highlights'],['Global','Overall color wash']]){const row=document.createElement('label');row.className='color-row';row.textContent=label;const picker=document.createElement('input');picker.type='color';picker.id='grade'+name+'Color';picker.setAttribute('aria-label',label+' tint');let before=null;picker.oninput=()=>{if(!img)return;if(!before){pushHistory();before=true;}settings[picker.id]=picker.value;scheduleRender();};picker.onchange=()=>{before=null;render();save();};row.append(picker);grading.append(row,slider('grade'+name,label+' strength',0,100,1));}grading.append(slider('gradeBalance','Shadow / highlight balance',-100,100,1),slider('gradeBlend','Tonal overlap',0,100,1));
section('Presence & detail','detail',[['clarity','Clarity',-100,100,1],['texture','Texture',-100,100,1],['sharpen','Sharpening',0,100,1],['denoise','Noise smoothing',0,100,1]]);
section('Grain structure','effects',[['grainSize','Grain size',0,100,1],['grainRoughness','Grain roughness',0,100,1],['grainColor','Color grain',0,100,1]]);
const halation=section('Layered halation','effects',[['halationThreshold','Highlight threshold',0,95,1],['halationRadius','Spread / radius',0,100,1],['halationTight','Tight edge layer',0,100,1],['halationMid','Medium halo layer',0,100,1],['halationWide','Wide diffusion layer',0,100,1],['glowRadius','Dream glow spread',0,100,1]]);const hint=document.createElement('p');hint.className='small muted';hint.textContent='Raise Warm halation above, then lower the threshold for a stronger bloom. Three blurred highlight layers blend around bright edges.';halation.children[0].after(hint);const tint=document.createElement('label');tint.className='color-row';tint.textContent='Halo color';const color=document.createElement('input');color.type='color';color.id='halationTint';color.setAttribute('aria-label','Halo color');color.onchange=()=>mutate(()=>settings.halationTint=color.value);tint.append(color);halation.append(tint);
section('Vignette','effects',[['vignette','Darken / brighten edges',-100,100,1],['vignetteFeather','Vignette softness',0,100,1]]);
const border=section('Print borders','frame',[['border','Border width (%)',0,25,1],['borderBottom','Extra bottom border',0,200,1]]);const borderRow=document.createElement('label');borderRow.className='color-row';borderRow.textContent='Border color';const borderColor=document.createElement('input');borderColor.id='borderColor';borderColor.type='color';borderColor.setAttribute('aria-label','Border color');borderColor.onchange=()=>mutate(()=>settings.borderColor=borderColor.value);borderRow.append(borderColor);border.append(borderRow);const borders=document.createElement('div');borders.className='border-presets';for(const [label,width,bottom,color]of [['White',6,0,'#ffffff'],['Gallery',10,0,'#ffffff'],['Instant',7,140,'#fffdf6'],['None',0,0,'#ffffff']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>mutate(()=>{settings.border=width;settings.borderBottom=bottom;settings.borderColor=color;});borders.append(b);}border.append(borders);const borderHint=document.createElement('p');borderHint.className='small muted';borderHint.textContent='Borders are included in your export. Original photo pixels remain untouched.';border.append(borderHint);
function setTool(tool){selectedTool=tool;window.reviewUI?.toolChanged(tool);window.maskUI?.setActive(tool==='mask');document.querySelectorAll('[data-toolgroup]').forEach(el=>el.hidden=el.dataset.toolgroup!==tool);document.querySelectorAll('[data-tool]').forEach(el=>{el.classList.toggle('active',el.dataset.tool===tool);el.setAttribute('aria-pressed',el.dataset.tool===tool);});window.reviewUI?.refreshSections(tool);}
// Tool buttons are separate from node selection: several nodes share a toolbar.
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
function syncAdvanced(){for(const input of document.querySelectorAll('#advancedControls input')){input.disabled=!img;if(settings[input.id]!==undefined)input.value=settings[input.id];}for(const button of document.querySelectorAll('.border-presets button'))button.disabled=!img;$('autoTone').disabled=!img;document.querySelectorAll('[data-band]').forEach(el=>el.hidden=el.dataset.band!==hslBand);for(const [i,b]of [...chips.children].entries())b.classList.toggle('active',FX.colorBands[i][0]===hslBand);const ctx=curveCanvas.getContext('2d');ctx.clearRect(0,0,256,120);ctx.strokeStyle='#8886';ctx.lineWidth=1;for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(i*64,0);ctx.lineTo(i*64,120);ctx.moveTo(0,i*30);ctx.lineTo(256,i*30);ctx.stroke();}ctx.strokeStyle='#a6c77b';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<=256;i++)ctx.lineTo(i,120-FX.curveValue(i/256,settings)*120);ctx.stroke();}
window.advancedUI={sync:syncAdvanced,setTool,section};setTool('light');sync();
})();
