const $=id=>document.getElementById(id),api=window.desktop;
let documentSettings=structuredClone(Imaging.defaults),activeNodeUid=null;
const parameterTarget=key=>Imaging.compositionKeys.includes(key)||key==='nodes'||key==='_schema'?documentSettings:documentSettings.nodes.find(n=>n.uid===activeNodeUid)?.adjustments||documentSettings;
const viewSettings=new Proxy({},{get:(_,key)=>parameterTarget(key)[key]??Imaging.defaults[key],set:(_,key,value)=>{parameterTarget(key)[key]=value;if(Imaging.compositionKeys.includes(key)){const n=documentSettings.nodes.find(n=>n.uid===activeNodeUid);if(n){n.frame||={};n.frame[key]=value;}}return true;}});
const cloneDocument=()=>structuredClone(Imaging.resolveFrame(documentSettings));
const historyState=()=>({document:cloneDocument(),target:activeNodeUid});
function restoreDocument(value){documentSettings=value.document||value;activeNodeUid=(value.document?value.target:documentSettings.selectedNode)||documentSettings.nodes[0]?.uid||null;}

let catalog={photos:[]},current=null,img=null,settings=viewSettings,history=[],future=[],filter='all',mode='edit',zoom=0,comparing=false,selection=0,renderTimer,saveTimer,toastTimer;
const thumbs=new Map(); let thumbQueue=Promise.resolve(); let renderVersion=0, paintedVersion=0, settleTimer;
const cloneSettings=()=>structuredClone(Object.fromEntries(Object.keys(Imaging.defaults).map(key=>[key,settings[key]])));
const looks=[
['Original','A clean beginning',{}],
['Portra 400 · inspired','Soft skin tones · warm pastels',{exposure:.12,contrast:-8,highlights:-22,shadows:12,temperature:12,tint:5,saturation:-9,vibrance:12,fade:18,grain:22}],
['Portra 800 · inspired','Warm shadows · textured 35mm',{exposure:.1,contrast:8,highlights:-20,shadows:15,temperature:19,tint:4,saturation:-12,fade:15,grain:38}],
['CineStill 800T · inspired','Cool night · red highlight bloom',{contrast:13,highlights:-12,shadows:9,temperature:-20,tint:9,saturation:-8,fade:10,grain:30,halation:78,halationRadius:48,halationThreshold:58,halationWide:65}],
['CineStill 50D · inspired','Clean daylight · gentle warmth',{exposure:.12,contrast:5,highlights:-16,shadows:8,temperature:7,saturation:4,fade:6,grain:12,halation:18}],
['Gold 200 · inspired','Sunny color · nostalgic warmth',{temperature:26,contrast:10,saturation:10,highlights:-17,shadows:8,fade:13,grain:26}],
['HP5 35mm · inspired','Silver monochrome · tactile grain',{saturation:-100,contrast:22,highlights:-14,shadows:12,fade:16,grain:42}],
['Dream / milk & honey','Creamy highlights · soft glow',{exposure:.25,contrast:-20,highlights:-18,shadows:20,temperature:15,tint:5,saturation:-13,fade:30,glow:65,grain:9,halation:45,halationThreshold:48,halationWide:65}],
['Dream / blue hour','Cool haze · lavender shadows',{exposure:.15,contrast:-16,temperature:-15,tint:17,shadows:19,saturation:-14,fade:24,glow:58,grain:14,halation:38,halationRadius:64}],
['Dream / rosewater','Blush warmth · luminous skin',{exposure:.2,contrast:-13,temperature:10,tint:20,highlights:-18,saturation:-8,fade:18,glow:62,grain:12,halation:88,halationThreshold:42,halationRadius:65,halationWide:90}],
['35mm / faded summer','Washed blacks · warm nostalgia',{contrast:-9,temperature:22,tint:-5,saturation:-18,fade:48,grain:33,glow:12}],
['35mm / midnight','Deep cool tones · glowing lights',{exposure:-.15,contrast:22,temperature:-23,tint:7,shadows:-8,saturation:-16,grain:35,halation:45}]];
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6000);}
function fail(e){console.error(e);toast(e.message||String(e));}
function projectPhotos(){return catalog.photos.filter(p=>p.projectId===catalog.activeProjectId);}
function visible(){const photos=projectPhotos().filter(p=>filter!=='favorites'||p.favorite);return window.copyUI?copyUI.group(photos):photos;}
function controls(){const groups=[['Light',[['exposure','Exposure',-3,3,.05],['contrast','Contrast',-100,100,1],['highlights','Highlights',-100,100,1],['shadows','Shadows',-100,100,1]]],['Color',[['temperature','Temperature',-100,100,1],['tint','Tint',-100,100,1],['saturation','Saturation',-100,100,1],['vibrance','Vibrance',-100,100,1]]],['Film & atmosphere',[['fade','Black fade',0,100,1],['grain','35mm grain',0,100,1],['glow','Dream glow',0,100,1],['halation','Warm halation',0,100,1]]]];for(const [name,rows]of groups){const section=document.createElement('details');section.open=true;const title=document.createElement('summary');title.textContent=name;section.append(title);rows.forEach(r=>section.append(slider(...r)));$('controls').append(section);} $('cropControls').append(slider('cropX','Horizontal position',0,100,1),slider('cropY','Vertical position',0,100,1));}
function slider(key,label,min,max,step){const row=document.createElement('div');row.className='slider-row';const lab=document.createElement('label');lab.className='slider-label';lab.htmlFor=key;lab.append(document.createTextNode(label));const out=document.createElement('output');out.id=key+'Value';lab.append(out);const input=document.createElement('input');Object.assign(input,{type:'range',id:key,min,max,step,value:settings[key],disabled:true});let started=false;input.addEventListener('input',()=>{if(!started){pushHistory();started=true;}settings[key]=Number(input.value);syncValues();scheduleRender();});input.addEventListener('change',()=>{started=false;render();save();});input.addEventListener('dblclick',()=>{if(!current)return;pushHistory();settings[key]=Imaging.defaults[key];sync();render();save();});row.append(lab,input);return row;}
function syncValues(){window.gradingWheels?.sync();window.studioUI?.curve();for(const key of Object.keys(Imaging.defaults)){if($(key+'Value'))$(key+'Value').textContent=['exposure','printExposure'].includes(key)?Number(settings[key]).toFixed(2):key==='straighten'?Number(settings[key]).toFixed(1)+'°':Math.round(settings[key]);}}
function sync(){window.precisionUI?.sync();Imaging.resolveFrame(documentSettings);for(const key of Object.keys(Imaging.defaults)){if($(key))$(key).value=settings[key];}syncValues();const active=!!(current&&img);document.querySelectorAll('#controls input,#cropControls input,.composition-buttons button,#crop').forEach(el=>el.disabled=!active);for(const id of ['export','favorite','reset','compare'])$(id).disabled=!active;$('undo').disabled=!active||!history.length;$('redo').disabled=!active||!future.length;$('favorite').textContent=current?.favorite?'★':'☆';document.querySelectorAll('.preset').forEach(el=>el.disabled=!active);window.maskUI?.sync();window.advancedUI?.sync();window.nodeUI?.sync();window.reviewUI?.sync();window.studioUI?.sync();window.nodeFlowUI?.sync();window.lookBrowserUI?.sync();window.textUI?.sync();window.creativeUI?.sync();window.workspaceUI?.sync();window.lookPreviewUI?.sync();window.rawDevelopUI?.sync();}
function pushHistory(){history.push(historyState());if(history.length>80)history.shift();future=[];}
const savedEdits=new Map(),pendingEdits=new Map();
function editUpdate(){if(!current)return null;current.settings=cloneDocument();return {id:current.id,settings:current.settings,favorite:!!current.favorite,rating:current.rating||0};}
async function writeEdits(update){if(!update)return;const signature=JSON.stringify(update);if(pendingEdits.get(update.id)?.signature===signature)return pendingEdits.get(update.id).promise;if(savedEdits.get(update.id)===signature&&!pendingEdits.has(update.id))return;const promise=api.save(update).then(()=>{savedEdits.delete(update.id);savedEdits.set(update.id,signature);if(savedEdits.size>30)savedEdits.delete(savedEdits.keys().next().value);}).finally(()=>{if(pendingEdits.get(update.id)?.promise===promise)pendingEdits.delete(update.id);});pendingEdits.set(update.id,{signature,promise});return promise;}
function save(){const update=editUpdate();if(!update)return;$('saveStatus').textContent='Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>writeEdits(update).then(()=>{if(current?.id===update.id)$('saveStatus').textContent='Edits saved locally';}).catch(e=>{$('saveStatus').textContent='Could not save';fail(e);}),200);sync();}
async function flush(){clearTimeout(saveTimer);await writeEdits(editUpdate());}
function scheduleRender(){if(!renderTimer)renderTimer=requestAnimationFrame(()=>{renderTimer=null;render(true);});clearTimeout(settleTimer);settleTimer=setTimeout(()=>render(false,true),260);}
function previewLimit(photo=img,snapshot=cloneDocument(),interactive=false){if(interactive)return Renderer.interactiveSize();if(zoom>=1&&window.detailPreviewUI?.eligible(snapshot))return 2048;if(zoom>=1||window.previewQualityUI?.maximum())return 0;const g=Imaging.geometry(photo.naturalWidth,photo.naturalHeight,snapshot),stage=$('stage'),fit=Math.min((stage.clientWidth-52)/g.width,(stage.clientHeight-52)/g.height,1);return Math.min(Math.max(g.width,g.height),Math.max(1280,Math.ceil(Math.max(g.width,g.height)*(zoom||Math.max(.1,fit))*(window.devicePixelRatio||1)*1.25)));}
async function render(interactive=false,refine=false){if(!img)return;window.detailPreviewUI?.invalidate();const version=++renderVersion;if(img.lithRawKey!==RawColor.key(documentSettings.rawDevelop)){try{const next=await PhotoCache.load(current.id,documentSettings.rawDevelop);if(version!==renderVersion)return;img=next;Renderer.clear();}catch(e){fail(e);return;}}const photo=img,snapshot=window.reviewUI?.previewSettings(window.lookPreviewUI?.snapshot(cloneDocument())||cloneDocument())||cloneDocument(),original=comparing;if(window.secondDisplayUI?.update(photo,snapshot,original))return;try{$('photo').dataset.settled='false';const max=previewLimit(photo,snapshot,interactive);const cacheKey=JSON.stringify([snapshot,max,original]),cached=!interactive&&PhotoCache.preview(current.id,cacheKey);if(!interactive&&!refine&&!cached){clearTimeout(settleTimer);render(true);settleTimer=setTimeout(()=>render(false,true),260);return;}const result=cached||await Renderer.preview(photo,snapshot,max,original,interactive);if(!result)return;if(!interactive&&version!==renderVersion||version<paintedVersion||photo!==img||original!==comparing||!original&&window.reviewUI&&!window.reviewUI.isCurrent(snapshot)){result.close?.();return;}paintedVersion=version;if(!interactive&&!cached)PhotoCache.rememberPreview(current.id,cacheKey,result);const canvas=$('photo');canvas.width=result.width;canvas.height=result.height;canvas.getContext('2d').drawImage(result,0,0);canvas.dataset.settled=String(!interactive&&version===renderVersion);canvas.dataset.previewGate=String(!!snapshot.previewGate);result.close?.();canvas.hidden=false;$('empty').hidden=true;$('originalLabel').hidden=!comparing;layout();if(!interactive)histogram(canvas);const g=Imaging.geometry(img.naturalWidth,img.naturalHeight,comparing?Imaging.defaults:snapshot),out=FX.borderGeometry(g.width,g.height,comparing?Imaging.defaults:snapshot);$('dimensions').textContent=out.width+' × '+out.height+' px  /  '+(current.size/1024/1024).toFixed(1)+' MB';window.maskUI?.overlay();if(!interactive)window.reviewUI?.update(snapshot);if(!interactive){PhotoCache.prefetch(current.id);window.detailPreviewUI?.refresh();}}catch(e){fail(e);}}

function layout(){const c=$('photo'),stage=$('stage');if(!img)return;const fit=Math.min((stage.clientWidth-52)/c.width,(stage.clientHeight-52)/c.height,1);const g=Imaging.geometry(img.naturalWidth,img.naturalHeight,documentSettings),full=FX.borderGeometry(g.width,g.height,documentSettings);const scale=zoom?zoom*full.width/c.width:fit;c.style.width=Math.round(c.width*scale)+'px';c.style.height=Math.round(c.height*scale)+'px';stage.style.alignItems=c.height*scale>stage.clientHeight-52?'flex-start':'center';stage.style.justifyContent=c.width*scale>stage.clientWidth-52?'flex-start':'center';$('fit').textContent=zoom?Math.round(zoom*100)+'%':'Fit';window.reviewUI?.layout();window.textUI?.layout();}
function histogram(canvas){if(window.scopesUI){window.scopesUI.update(canvas);return;}const small=document.createElement('canvas');small.width=160;small.height=100;const cx=small.getContext('2d',{willReadFrequently:true});cx.drawImage(canvas,0,0,160,100);const data=cx.getImageData(0,0,160,100).data,bins=Array.from({length:3},()=>new Uint32Array(64));for(let i=0;i<data.length;i+=4){if(!data[i+3])continue;for(let c=0;c<3;c++)bins[c][data[i+c]>>2]++;}const h=$('histogram'),ctx=h.getContext('2d');ctx.clearRect(0,0,h.width,h.height);const max=Math.max(...bins.flatMap(b=>Array.from(b)),1);['#bac88980','#7ead9680','#7e9cbb70'].forEach((color,c)=>{ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,76);bins[c].forEach((n,i)=>ctx.lineTo(i*260/63,76-Math.sqrt(n/max)*70));ctx.lineTo(260,76);ctx.closePath();ctx.fill();});}
function thumb(p){if(!thumbs.has(p.id)){const pending=api.thumbnail(p.id).catch(()=>{thumbs.delete(p.id);return '';});thumbs.set(p.id,pending);}return thumbs.get(p.id);}
const thumbnailObserver=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;const image=entry.target,p=catalog.photos.find(p=>p.id===image.dataset.photoId);thumbnailObserver.unobserve(image);if(p)thumb(p).then(url=>{if(image.isConnected)image.src=url;});}},{rootMargin:'100px'});
let collectionKey='';
async function refresh(){const list=visible();$('count').textContent=projectPhotos().length;$('favCount').textContent=projectPhotos().filter(p=>p.favorite).length;$('filmCount').textContent=list.length+' PHOTOS';window.projectUI?.sync();
const key=catalog.activeProjectId+':'+filter+':'+list.map(p=>p.id).join(',');
if(collectionKey!==key){collectionKey=key;thumbnailObserver.disconnect();$('filmstrip').replaceChildren();$('grid').replaceChildren();for(const p of list){for(const kind of ['film','grid']){const button=document.createElement('button');button.className=kind==='film'?'thumb':'grid-card';button.dataset.photoId=p.id;button.title=p.name;button.setAttribute('aria-label',p.name);const image=document.createElement('img');image.alt=p.name;image.dataset.photoId=p.id;image.decoding='async';button.append(image);const caption=document.createElement(kind==='film'?'span':'div');caption.textContent=kind==='film'?(p.favorite?'★':''):p.name;button.append(caption);button.onclick=()=>{setMode('edit');select(p.id).catch(fail);};$(kind==='film'?'filmstrip':'grid').append(button);thumbnailObserver.observe(image);}}}
const photoMap=new Map(list.map(p=>[p.id,p]));for(const b of document.querySelectorAll('#filmstrip .thumb,#grid .grid-card')){b.classList.toggle('active',b.dataset.photoId===current?.id);if(b.classList.contains('thumb'))b.querySelector('span').textContent=photoMap.get(b.dataset.photoId)?.favorite?'★':'';}
window.copyUI?.refresh();window.batchUI?.refresh();
}
async function select(id){if(current?.id===id&&img){++selection;$('loading').hidden=true;render();return;}const p=catalog.photos.find(p=>p.id===id);if(!p||p.projectId!==catalog.activeProjectId)return;const token=++selection;clearTimeout(settleTimer);if(renderTimer){cancelAnimationFrame(renderTimer);renderTimer=null;}Renderer.clear();$('loading').textContent=/\.(jpe?g|png|webp)$/i.test(p.ext)?'Opening photo…':'Developing RAW… First opening takes longer; later visits use the cache.';$('loading').hidden=false;try{const [,next]=await Promise.all([flush(),PhotoCache.load(id)]);if(token!==selection)return;current=p;img=next;restoreDocument(Imaging.normalizeSettings(p.settings));history=[];future=[];zoom=0;comparing=false;savedEdits.set(id,JSON.stringify(editUpdate()));if(savedEdits.size>30)savedEdits.delete(savedEdits.keys().next().value);$('photoName').textContent=p.name+(/\.(jpe?g|png|webp)$/i.test(p.ext)?'':' · RAW');sync();render();refresh();api.save({id}).catch(fail);$('saveStatus').textContent='Edits saved locally';}catch(e){if(token===selection){current=null;img=null;window.secondDisplayUI?.clear();$('photo').hidden=true;$('empty').hidden=false;sync();}fail(Error('This image could not be opened. '+e.message));}finally{if(token===selection)$('loading').hidden=true;}}
async function imported(result){catalog=result.catalog;await refresh();if(result.errors.length)toast(result.errors.join('\n'));if(catalog.selected&&catalog.selected!==current?.id){setMode('edit');await select(catalog.selected);}}
async function importPhotos(){try{await flush();await imported(await api.import());}catch(e){fail(e);}}
function setMode(value){mode=value;window.secondDisplayUI?.sync();$('stage').hidden=value==='library';$('stage').style.display=value==='library'?'none':'flex';$('grid').hidden=value!=='library';$('editMode').classList.toggle('active',value==='edit');$('libraryMode').classList.toggle('active',value==='library');if(value==='edit')requestAnimationFrame(layout);}
function mutate(fn){if(!img)return;pushHistory();fn();sync();render();save();}
function compare(value){if(!img)return;comparing=value;render();}
looks.push(...(window.extraLooks||[]));controls();looks.forEach(([name,desc,values],i)=>{const b=document.createElement('button');b.className='preset';b.disabled=true;const swatch=document.createElement('span');swatch.className='swatch';swatch.style.filter=['none','sepia(.3)','sepia(.55)','hue-rotate(35deg)','sepia(.15)','sepia(.6) saturate(1.5)','grayscale(1)','sepia(.3) contrast(.7)','hue-rotate(45deg) contrast(.7)','sepia(.3) hue-rotate(320deg)','sepia(.6) contrast(.6)','hue-rotate(35deg) brightness(.7)'][i];const text=document.createElement('span');text.textContent=name;const sub=document.createElement('small');sub.textContent=desc;text.append(sub);b.append(swatch,text);b.onclick=()=>{mutate(()=>{for(const key of Object.keys(Imaging.defaults).filter(k=>!Imaging.compositionKeys.includes(k)&&!['nodes','masks','_schema','developMix'].includes(k)))settings[key]=values[key]??Imaging.defaults[key];});document.querySelectorAll('.preset').forEach(el=>el.classList.toggle('active',el===b));};$('presets').append(b);});
$('import').onclick=$('emptyImport').onclick=importPhotos;
$('editMode').onclick=()=>setMode('edit');$('libraryMode').onclick=()=>{setMode('library');refresh();};
for(const key of ['all','favorites'])$(key).onclick=()=>{filter=key;$(key).classList.add('active');$(key==='all'?'favorites':'all').classList.remove('active');if(!window.workspaceUI)setMode('library');refresh();};
$('favorite').onclick=()=>{if(!current)return;current.favorite=!current.favorite;save();refresh();};
$('undo').onclick=()=>{if(!history.length)return;future.push(historyState());restoreDocument(history.pop());sync();render();save();};$('redo').onclick=()=>{if(!future.length)return;history.push(historyState());restoreDocument(future.pop());sync();render();save();};
$('reset').onclick=()=>mutate(()=>{const node=documentSettings.nodes.find(n=>n.uid===activeNodeUid);if(node){node.adjustments=structuredClone(Imaging.defaults);node.looks=[];node.frame={};delete node.legacyStage;node.mix=100;}else{const nodes=documentSettings.nodes;documentSettings=structuredClone(Imaging.defaults);documentSettings.nodes=nodes;}});$('rotate').onclick=()=>mutate(()=>settings.rotation=(settings.rotation+90)%360);$('flip').onclick=()=>mutate(()=>settings.flip=!settings.flip);$('crop').onchange=e=>mutate(()=>settings.crop=Number(e.target.value));
$('compare').onpointerdown=e=>{e.currentTarget.setPointerCapture(e.pointerId);compare(true);};$('compare').onpointerup=$('compare').onpointercancel=()=>compare(false);$('compare').onkeydown=e=>{if(e.key===' '){e.preventDefault();compare(true);}};$('compare').onkeyup=e=>{if(e.key===' ')compare(false);};window.addEventListener('blur',()=>{if(comparing)compare(false);});
$('fit').onclick=()=>{zoom=0;layout();};$('zoomIn').onclick=()=>{zoom=Math.min(4,(zoom||.8)*1.25);layout();};$('zoomOut').onclick=()=>{zoom=Math.max(.1,(zoom||1)/1.25);layout();};let resizeRender;new ResizeObserver(()=>{layout();clearTimeout(resizeRender);resizeRender=setTimeout(()=>{if(img)render();},200);}).observe($('stage'));
$('quality').oninput=()=>$('qualityValue').textContent=$('quality').value+'%';$('exportFormat').onchange=()=>{$('quality').disabled=$('exportFormat').value==='png';};$('export').onclick=()=>$('exportDialog').showModal();
$('saveExport').onclick=async()=>{if(!img)return;const b=$('saveExport');b.disabled=true;b.textContent='Rendering your photograph…';try{await new Promise(r=>setTimeout(r,40));const projectId=catalog.activeProjectId,format=$('exportFormat').value,exportName=current.name,blob=await Renderer.export(img,cloneDocument(),Number($('exportSize').value),format,Number($('quality').value)/100,catalog.projects.find(p=>p.id===projectId)?.settings.sharpening);const url=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob);});if(!url.startsWith('data:image/'+format))throw Error('This format could not be encoded. Choose PNG.');const ok=await api.export({projectId,name:exportName,format,base64:url.split(',')[1]});if(ok){const saved=await api.catalog();const project=catalog.projects.find(p=>p.id===projectId);if(project)project.exportFolder=saved.projects.find(p=>p.id===projectId)?.exportFolder;$('exportDialog').close();toast('Your edited photograph has been exported.');}}catch(e){fail(e);}finally{b.disabled=false;b.textContent='Choose location & export ↗';}};
Shortcuts.register('undo','Undo','Editing',['mod+z'],()=>$('undo').click());
Shortcuts.register('redo','Redo','Editing',['mod+shift+z'],()=>$('redo').click());
Shortcuts.register('import','Import photos','Photos',['mod+o'],importPhotos);

document.addEventListener('dragover',e=>{if(!e.dataTransfer.types.includes('Files'))return;e.preventDefault();document.body.classList.add('dragging');});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)document.body.classList.remove('dragging');});document.addEventListener('drop',async e=>{e.preventDefault();document.body.classList.remove('dragging');if(!e.dataTransfer.files.length)return;try{await flush();await imported(await api.drop(Array.from(e.dataTransfer.files)));}catch(error){fail(error);}});
api.catalog().then(async c=>{catalog=c;window.projectUI?.sync();if(c.selected)await select(c.selected);await refresh();sync();}).catch(fail);
