(()=>{
let clipboard=null,busy=false,anchor=null,activeAsset=null,closeTimer,openTimer,previewToken=0;
const remembered=new Map(),previewCache=new Map();
const asset=p=>p.sourceId||p.id,label=p=>p.copyNumber?'Copy '+p.copyNumber:'Original';
function group(photos){const groups=new Map();for(const p of photos){const key=p.projectId+':'+asset(p);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(p);}return [...groups].map(([key,versions])=>{const chosen=versions.find(p=>p.id===current?.id)||versions.find(p=>p.id===remembered.get(key))||versions[0];remembered.set(key,chosen.id);return chosen;});}
const panel=document.createElement('section');panel.id='photoCopiesPanel';panel.hidden=true;panel.tabIndex=-1;panel.setAttribute('aria-label','Photo versions and edit actions');panel.innerHTML='<div class="copies-heading"><strong>Photo versions</strong><button id="closeCopies" aria-label="Close versions">✕</button></div><div id="photoCopiesList"></div><div class="photo-hover-actions"></div>';document.body.append(panel);
const paths={add:'M8 8h12v12H8z M4 15V4h11 M11 14h6 M14 11v6',copy:'M8 8h12v12H8z M4 15V4h11',paste:'M9 5H5v16h14V5h-4 M9 3h6v4H9z M8 13h8 M12 10v6'};
function icon(name){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+paths[name]+'"/></svg>';}
for(const [name,title,action]of [['add','New copy',duplicate],['copy','Copy edits',copy],['paste','Paste edits',paste]]){const b=document.createElement('button');b.innerHTML=icon(name)+'<span>'+title+'</span>';b.title=name==='add'?'Create an independent virtual copy':title;b.setAttribute('aria-label',name==='add'?'Create virtual copy':title);if(name==='paste')b.dataset.pasteEdits='true';b.onclick=()=>{const id=anchor?.querySelector('[data-photo-id]')?.dataset.photoId;if(id)action(id);};panel.querySelector('.photo-hover-actions').append(b);}
function hide(){clearTimeout(openTimer);clearTimeout(closeTimer);panel.hidden=true;activeAsset=null;anchor=null;++previewToken;}
function later(){clearTimeout(closeTimer);closeTimer=setTimeout(()=>{if(!panel.matches(':hover')&&!panel.contains(document.activeElement)&&!anchor?.matches(':hover'))hide();},220);}
panel.onpointerenter=()=>clearTimeout(closeTimer);panel.onpointerleave=later;panel.onfocusout=later;$('closeCopies').onclick=hide;
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden){const button=anchor?.querySelector('.thumb,.grid-card');hide();button?.focus();}});
document.addEventListener('pointerdown',e=>{if(!panel.hidden&&!panel.contains(e.target)&&!anchor?.contains(e.target))hide();});
function position(){if(!anchor?.isConnected){hide();return;}const r=anchor.getBoundingClientRect();panel.style.left=Math.max(8,Math.min(innerWidth-panel.offsetWidth-8,r.left))+'px';const above=r.top-panel.offsetHeight-8;panel.style.top=Math.max(8,above>=8?above:Math.min(innerHeight-panel.offsetHeight-8,r.bottom+8))+'px';}
window.addEventListener('resize',hide);for(const id of ['filmstrip','grid'])$(id).addEventListener('scroll',hide);
async function duplicate(id){if(busy)return;busy=true;try{await flush();const result=await api.virtualCopy(id);catalog=result.catalog;setMode('edit');await select(result.id);await refresh();toast('Virtual copy created. Its edits are independent.');}catch(e){fail(e);}finally{busy=false;}}
async function copy(id){try{await flush();const p=catalog.photos.find(p=>p.id===id);if(!p)return;clipboard={name:p.name,settings:structuredClone(p.id===current?.id?cloneDocument():Imaging.normalizeSettings(p.settings))};refreshActions();toast('Copied edits from '+p.name);}catch(e){fail(e);}}
async function paste(id){if(!clipboard||busy)return;busy=true;try{setMode('edit');await select(id);if(current?.id!==id)return;mutate(()=>restoreDocument(Imaging.normalizeSettings(structuredClone(clipboard.settings))));if(anchor)show(anchor);toast('Pasted all edits. Undo restores the previous version.');}catch(e){fail(e);}finally{busy=false;}}
function refreshActions(){for(const button of panel.querySelectorAll('[data-paste-edits]')){button.disabled=!clipboard;button.title=clipboard?'Paste all edits from '+clipboard.name+' (replaces nodes, masks, crop and text; supports Undo)':'Copy edits from a photo first';}}
async function show(tile){clearTimeout(closeTimer);anchor=tile;const p=catalog.photos.find(p=>p.id===tile.querySelector('[data-photo-id]').dataset.photoId);if(!p)return;activeAsset=asset(p);const token=++previewToken,versions=catalog.photos.filter(v=>asset(v)===activeAsset&&v.projectId===catalog.activeProjectId);const list=$('photoCopiesList');list.replaceChildren();const items=[];for(const photo of versions){const b=document.createElement('button');b.className='copy-choice';b.dataset.versionId=photo.id;b.setAttribute('aria-current',String(photo.id===current?.id));b.setAttribute('aria-label','Switch to '+label(photo));const image=document.createElement('img');image.alt=label(photo)+' edited preview';const caption=document.createElement('span');caption.textContent=label(photo);b.append(image,caption);b.onclick=()=>{setMode('edit');select(photo.id).catch(fail);};list.append(b);items.push({photo,image});}panel.hidden=false;refreshActions();position();
// Only build previews for the hovered photo. Keep a small cache keyed by edits.
for(const {photo,image}of items){if(token!==previewToken)return;const snapshot=photo.id===current?.id?cloneDocument():Imaging.normalizeSettings(photo.settings),key=photo.id+JSON.stringify(snapshot);try{let url=previewCache.get(key);if(!url){const source=await PhotoCache.load(photo.id);if(token!==previewToken)return;const blob=await Renderer.export(source,snapshot,320,'jpeg',.85,null,true);if(token!==previewToken)return;url=URL.createObjectURL(blob);previewCache.set(key,url);while(previewCache.size>24){const oldest=previewCache.keys().next().value;URL.revokeObjectURL(previewCache.get(oldest));previewCache.delete(oldest);}}if(token!==previewToken)return;image.src=url;}catch{if(token===previewToken)image.alt='Preview unavailable';}}
}
function refreshCopies(){const photos=new Map(catalog.photos.map(p=>[p.id,p])),counts=new Map();for(const p of catalog.photos){const key=p.projectId+':'+asset(p);counts.set(key,(counts.get(key)||0)+1);}let replacement=null;for(const button of document.querySelectorAll('#filmstrip .thumb,#grid .grid-card')){const p=photos.get(button.dataset.photoId);if(!p)continue;let tile=button.closest('.photo-tile');if(!tile){tile=document.createElement('div');tile.className='photo-tile '+(button.classList.contains('thumb')?'film-tile':'grid-tile');button.before(tile);tile.append(button);tile.onpointerenter=()=>{clearTimeout(closeTimer);clearTimeout(openTimer);openTimer=setTimeout(()=>show(tile),180);};tile.onpointerleave=()=>{clearTimeout(openTimer);later();};const badge=document.createElement('button');badge.className='copy-badge';badge.onclick=e=>{e.stopPropagation();show(tile);if(e.detail===0)panel.querySelector('.copy-choice')?.focus();};tile.append(badge);}const count=counts.get(p.projectId+':'+asset(p)),badge=tile.querySelector('.copy-badge');badge.textContent=label(p)+(count>1?' · '+count+' versions':' · +');badge.setAttribute('aria-label','Show versions and actions for '+p.name);badge.title='Preview versions, create a copy, or copy and paste edits';if(activeAsset===asset(p)&&(!replacement||tile.classList.contains('film-tile')))replacement=tile;}
if(!panel.hidden){if(replacement)show(replacement);else hide();}refreshActions();}
window.copyUI={refresh:refreshCopies,duplicate,copy,paste,group};refresh().catch(fail);
})();
