(()=>{
let clipboard=null,busy=false;
const dialog=document.createElement('dialog');dialog.id='photoCopiesDialog';dialog.innerHTML='<div class="dialog-top"><strong>Versions of this photo</strong><button id="closeCopies" aria-label="Close copies">✕</button></div><p class="small muted">Each version has independent edits and shares the same original.</p><div id="photoCopiesList"></div>';document.body.append(dialog);$('closeCopies').onclick=()=>dialog.close();
async function duplicate(id){if(busy)return;busy=true;try{await flush();const result=await api.virtualCopy(id);catalog=result.catalog;await refresh();setMode('edit');await select(result.id);toast('Virtual copy created. Its edits are independent.');}catch(e){fail(e);}finally{busy=false;}}
async function copy(id){try{await flush();const p=catalog.photos.find(p=>p.id===id);if(!p)return;clipboard={name:p.name,settings:structuredClone(p.id===current?.id?cloneDocument():Imaging.normalizeSettings(p.settings))};refreshActions();toast('Copied edits from '+p.name);}catch(e){fail(e);}}
async function paste(id){if(!clipboard||busy)return;busy=true;try{setMode('edit');await select(id);if(current?.id!==id)return;mutate(()=>restoreDocument(Imaging.normalizeSettings(structuredClone(clipboard.settings))));toast('Pasted all edits. Undo restores the previous version.');}catch(e){fail(e);}finally{busy=false;}}
function showCopies(id){const p=catalog.photos.find(p=>p.id===id),asset=p.sourceId||p.id;const list=$('photoCopiesList');list.replaceChildren();for(const photo of catalog.photos.filter(p=>(p.sourceId||p.id)===asset&&p.projectId===catalog.activeProjectId)){const b=document.createElement('button');b.textContent=(photo.copyNumber?'Copy '+photo.copyNumber:'Original')+' · '+photo.name;b.className='copy-choice';b.setAttribute('aria-current',String(photo.id===current?.id));b.onclick=()=>{dialog.close();setMode('edit');select(photo.id).catch(fail);};list.append(b);}dialog.showModal();}
function refreshActions(){for(const button of document.querySelectorAll('[data-paste-edits]')){button.disabled=!clipboard;button.title=clipboard?'Paste all edits from '+clipboard.name+' (replaces nodes, masks, crop and text; supports Undo)':'Copy edits from a photo first';}}
function refreshCopies(){const photos=new Map(catalog.photos.map(p=>[p.id,p])),counts=new Map();for(const p of catalog.photos){const key=p.projectId+':'+(p.sourceId||p.id);counts.set(key,(counts.get(key)||0)+1);}for(const button of document.querySelectorAll('#filmstrip .thumb,#grid .grid-card')){const p=photos.get(button.dataset.photoId);if(!p)continue;let tile=button.closest('.photo-tile');if(!tile){tile=document.createElement('div');tile.className='photo-tile '+(button.classList.contains('thumb')?'film-tile':'grid-tile');button.before(tile);tile.append(button);const actions=document.createElement('div');actions.className='photo-hover-actions';for(const [label,icon,action]of [['Create virtual copy','⧉+',()=>duplicate(p.id)],['Copy edits','⧉',()=>copy(p.id)],['Paste edits','↧',()=>paste(p.id)],['Show versions','▤',()=>showCopies(p.id)]]){const b=document.createElement('button');b.textContent=icon;b.title=label;b.setAttribute('aria-label',label+' · '+p.name);if(label==='Paste edits')b.dataset.pasteEdits='true';b.onclick=e=>{e.stopPropagation();action();};actions.append(b);}tile.append(actions);const badge=document.createElement('span');badge.className='copy-badge';tile.append(badge);}const count=counts.get(p.projectId+':'+(p.sourceId||p.id));const badge=tile.querySelector('.copy-badge');badge.textContent=p.copyNumber?'Copy '+p.copyNumber:count>1?'Original · '+count+' versions':'';badge.hidden=!badge.textContent;}
refreshActions();}
window.copyUI={refresh:refreshCopies,duplicate,copy,paste};refreshCopies();
})();
