(()=>{
const cards=[];
function card(title,group,family,id,description,rows){const el=advancedUI.section(title,group,rows);el.id=id;el.classList.add('creative-card');if(family)el.dataset.effectFamily=family;const p=document.createElement('p');p.className='creative-help';p.textContent=description;el.querySelector('summary').after(p);cards.push(el);return el;}
function select(el,key,label,items){const row=document.createElement('label');row.className='select-row';row.textContent=label;const control=document.createElement('select');control.id=key;control.setAttribute('aria-label',label);items.forEach((name,i)=>control.append(new Option(name,String(i))));control.onchange=()=>mutate(()=>settings[key]=Number(control.value));row.append(control);el.append(row);return control;}
function advanced(el,title,keys){const more=document.createElement('details'),summary=document.createElement('summary');summary.textContent=title;more.append(summary);for(const key of keys){const input=$(key);more.append(input.closest('.slider-row,.select-row')||input);}el.append(more);}
function recipes(el,items){const row=document.createElement('div');row.className='creative-recipes';for(const [name,values]of items){const b=document.createElement('button');b.textContent=name;b.onclick=()=>{if(img)mutate(()=>Object.assign(settings,values));};row.append(b);}el.querySelector('.creative-help').after(row);}
function reset(el){const b=document.createElement('button');b.className='creative-reset';b.textContent='Reset this effect';b.onclick=()=>{if(img)mutate(()=>{for(const input of el.querySelectorAll('input[id],select[id]'))if(Object.hasOwn(Imaging.defaults,input.id))settings[input.id]=structuredClone(Imaging.defaults[input.id]);});};el.append(b);}
const compression=card('◒ Highlight compression','light',null,'compressionCard','Soften bright areas while preserving their color. This cannot recover detail already clipped in the original.',[['highlightCompression','Strength',0,100,1],['compressionStart','Start in highlights',10,95,1]]);recipes(compression,[['Gentle',{highlightCompression:30,compressionStart:75}],['Soft film',{highlightCompression:65,compressionStart:60}],['Strong roll-off',{highlightCompression:90,compressionStart:45}]]);reset(compression);
const prism=card('◇ Prism & glass','effects','optics','prismCard','Reflect and split the photo through virtual glass. Keep the center clear or move the clear area over your subject.',[['prism','Strength',0,100,1],['prismDistance','Reflection spread',0,100,1],['prismAngle','Glass angle',-180,180,1],['prismDispersion','Rainbow edges',0,100,1],['prismCenterX','Clear center · horizontal',0,100,1],['prismCenterY','Clear center · vertical',0,100,1],['prismProtect','Clear area size',0,100,1],['prismFeather','Soft transition',0,100,1]]);const prismMode=select(prism,'prismMode','Glass shape',['Single prism','Three reflections','Mirrored glass']);prism.querySelector('.creative-help').after(prismMode.parentElement);recipes(prism,[['Soft prism',{prism:35,prismMode:0,prismDistance:18,prismDispersion:15,prismProtect:40}],['Dream split',{prism:55,prismMode:1,prismDistance:32,prismDispersion:45,prismProtect:25}],['Glass edge',{prism:65,prismMode:2,prismDistance:16,prismDispersion:25,prismProtect:55}]]);advanced(prism,'Placement & rainbow edges',['prismDispersion','prismCenterX','prismCenterY','prismProtect','prismFeather']);reset(prism);
const double=card('▧ Double exposure','effects','blend','doubleCard','Combine a second image with this photo. Its original is copied into your private library; source edits are not applied.',[['doubleAmount','Second image strength',0,100,1],['doubleScale','Second image size (%)',10,300,1],['doubleX','Horizontal position',-100,100,1],['doubleY','Vertical position',-100,100,1],['doubleRotation','Rotation',-180,180,1],['doubleSoftness','Tonal transition',0,100,1]]);
const source=document.createElement('div');source.className='double-source';source.innerHTML='<img id="doublePreview" alt="Second exposure" hidden><span id="doubleSourceLabel">Choose a second photo</span><button id="chooseDoubleSource">＋ Choose image</button><button id="clearDoubleSource" aria-label="Remove second exposure">Remove</button><input id="doubleSource" type="hidden"><input id="doubleName" type="hidden">';double.querySelector('.creative-help').after(source);
$('chooseDoubleSource').onclick=async()=>{if(!img)return;const photo=current.id,node=activeNodeUid,b=$('chooseDoubleSource');b.disabled=true;try{const asset=await api.importEffectAsset();if(!asset)return;if(current?.id!==photo||activeNodeUid!==node){toast('The edit target changed. Choose the second image again.');return;}mutate(()=>{settings.doubleSource=asset.id;settings.doubleName=asset.name;settings.doubleAmount=50;});}catch(e){fail(e);}finally{b.disabled=!img;}};
$('clearDoubleSource').onclick=()=>{if(img)mutate(()=>{settings.doubleSource='';settings.doubleName='';settings.doubleAmount=0;});};
const blend=select(double,'doubleMode','Blend',['Normal · layer images','Screen · luminous blend','Multiply · richer shadows','Lighten · bright details']);source.after(blend.parentElement);const target=select(double,'doubleTarget','Apply to',['Whole photo','Shadows of base photo','Highlights of base photo']);blend.parentElement.after(target.parentElement);advanced(double,'Position, scale & transition',['doubleScale','doubleX','doubleY','doubleRotation','doubleSoftness']);reset(double);
const darkroom=card('▣ Darkroom · print & paper','color',null,'darkroomCard','Shape the final print with cyan, magenta and yellow filters, then choose a paper tone. These are creative print treatments.',[['darkroom','Print strength',0,100,1],['printExposure','Print exposure',-2,2,.05],['printContrast','Print contrast',-60,60,1],['printCyan','Cyan filter',-100,100,1],['printMagenta','Magenta filter',-100,100,1],['printYellow','Yellow filter',-100,100,1],['printFade','Paper fading',0,100,1]]);const paper=select(darkroom,'printPaper','Paper tone',['Neutral white','Warm fiber','Cool pearl']);darkroom.querySelector('.creative-help').after(paper.parentElement);recipes(darkroom,[['Warm print',{darkroom:75,printPaper:1,printCyan:-5,printMagenta:3,printYellow:12,printContrast:8,printFade:10}],['Cool editorial',{darkroom:70,printPaper:2,printCyan:8,printMagenta:0,printYellow:-8,printContrast:12,printFade:0}],['Faded paper',{darkroom:80,printPaper:1,printCyan:0,printMagenta:4,printYellow:8,printContrast:-12,printFade:50}]]);advanced(darkroom,'CMY print filters',['printCyan','printMagenta','printYellow']);reset(darkroom);
for(const [el,key,amount]of [[prism,'prism',40],[darkroom,'darkroom',100]])for(const type of ['input','change'])el.addEventListener(type,e=>{if(!img||e.target.id===key||!e.target.matches('input,select')||settings[key])return;settings[key]=amount;sync();if(type==='change'){render();save();}else scheduleRender();});
let thumbnailId='';function syncCreative(){for(const el of cards){for(const control of el.querySelectorAll('button,input,select'))control.disabled=!img;const keys=[...el.querySelectorAll('input[id],select[id]')].map(i=>i.id);el.classList.toggle('creative-modified',keys.some(k=>settings[k]!==Imaging.defaults[k]));}const id=settings.doubleSource||'';$('doubleSourceLabel').textContent=id?(settings.doubleName||'Second exposure'):'Choose a second photo';$('clearDoubleSource').hidden=!id;const preview=$('doublePreview');if(id!==thumbnailId){thumbnailId=id;preview.hidden=true;preview.removeAttribute('src');if(id)api.effectAsset(id).then(url=>{if(thumbnailId===id){preview.src=url;preview.hidden=false;}}).catch(()=>{if(thumbnailId===id)$('doubleSourceLabel').textContent='Image missing — choose it again';});}$('doubleAmount').disabled=!img||!id;}
window.creativeUI={sync:syncCreative};syncCreative();advancedUI.setTool(document.querySelector('[data-tool].active')?.dataset.tool||'light');
})();
