const assert=require('node:assert/strict'),Creative=require('./creative-effects.js'),Imaging=require('./processing.js'),{normalize}=require('./look-sharing.cjs');
const p={...Imaging.defaults},pixels=new Float32Array([30,60,90,128,180,200,250,255,300,450,600,200]);
for(const fn of [d=>Creative.compression(d,p),d=>Creative.printing(d,p),d=>Creative.prism(d,3,1,p),d=>Creative.double(d,3,1,p)]){const copy=pixels.slice();fn(copy);assert.deepEqual(copy,pixels);}
const compressed=pixels.slice();Creative.compression(compressed,{...p,highlightCompression:100});assert.deepEqual([...compressed.slice(0,4)],[...pixels.slice(0,4)]);assert.ok(compressed[10]<255);assert.ok(Math.abs(compressed[8]/compressed[10]-.5)<1e-6);assert.equal(compressed[11],200);
const warm=pixels.slice();Creative.printing(warm,{...p,darkroom:100,printYellow:50});assert.equal(warm[0],30);assert.ok(warm[2]<90);assert.equal(warm[3],128);
const high=pixels.slice();Creative.printing(high,{...p,darkroom:100,printExposure:1});assert.ok(high[10]>255,'Float highlights must not quantize or clip');
const sample=new Float32Array(12*8*4);for(let i=0;i<sample.length;i+=4)sample.set([i%255,(i*3)%255,(i*7)%255,170],i);
for(const mode of [0,1,2]){const out=sample.slice();Creative.prism(out,12,8,{...p,prism:60,prismMode:mode,prismProtect:0});assert.notDeepEqual(out,sample);assert.ok([...out].every(Number.isFinite));for(let i=3;i<out.length;i+=4)assert.equal(out[i],170);}
assert.deepEqual(Creative.refs({nodes:[{enabled:false,adjustments:{doubleSource:'private',doubleAmount:50}},{adjustments:{doubleSource:'kept',doubleAmount:50}}]}),['kept']);
const shared=normalize({name:'New effects',recipe:[{operation:'prism',adjustments:{...p,prism:50,doubleSource:'secret',doubleName:'private.jpg'}}]});assert.equal(shared.recipe[0].adjustments.prism,50);assert.ok(!JSON.stringify(shared).includes('secret'));assert.ok(!JSON.stringify(shared).includes('private.jpg'));
(async()=>{const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),{setup,restoreAssets}=require('./effect-assets.cjs');const temp=await fs.mkdtemp(path.join(os.tmpdir(),'lith-assets-test-'));try{const root=path.join(temp,'library'),original=path.join(temp,'photo.jpg'),bytes=Buffer.from('preserved-original');await fs.writeFile(original,bytes);const handlers={};setup({ipcMain:{handle:(id,fn)=>handlers[id]=fn},dialog:{showOpenDialog:async()=>({filePaths:[original]})},getWindow:()=>null,root});const asset=await handlers['effect-asset-import']();assert.equal(asset.name,'photo.jpg');assert.deepEqual(await fs.readFile(path.join(root,'effect-assets/originals',asset.id)),bytes);await assert.rejects(handlers['effect-asset-image']({},'../../photo.jpg'));await fs.unlink(original);assert.match(await handlers['effect-asset-image']({},asset.id),/^file:/);const dest=path.join(temp,'restored');await restoreAssets(root,dest,{photos:[{settings:{nodes:[{adjustments:{doubleSource:asset.id}}]}}]});assert.deepEqual(await fs.readFile(path.join(dest,'effect-assets/originals',asset.id)),bytes);console.log('PASS: creative neutral identity, highlight roll-off/hue/alpha, float print range, prism variants, private sharing, stored assets, library restore and path validation.');}finally{await fs.rm(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
