(function(scope){
const defaults={highlightCompression:0,compressionStart:65,prism:0,prismMode:0,prismDistance:22,prismAngle:0,prismDispersion:20,prismCenterX:50,prismCenterY:50,prismProtect:40,prismFeather:35,darkroom:0,printCyan:0,printMagenta:0,printYellow:0,printExposure:0,printContrast:0,printPaper:0,printFade:0,doubleSource:'',doubleName:'',doubleAmount:0,doubleMode:1,doubleScale:100,doubleX:0,doubleY:0,doubleRotation:0,doubleTarget:0,doubleSoftness:60};
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
function compression(data,p){const mix=clamp(p.highlightCompression/100),start=clamp(p.compressionStart/100,.1,.95),room=1-start;if(!mix)return;for(let i=0;i<data.length;i+=4){const lum=Math.max(data[i],data[i+1],data[i+2])/255;if(lum<=start)continue;const x=lum-start,target=start+room*x/(room+x),scale=1+(target/lum-1)*mix;for(let k=0;k<3;k++)data[i+k]*=scale;}}
function printing(data,p){const mix=clamp(p.darkroom/100);if(!mix)return;const paper=Math.round(p.printPaper),white=paper===1?[1,.965,.9]:paper===2?[.935,.97,1]:[1,1,1],black=paper===1?[.065,.052,.04]:paper===2?[.035,.043,.065]:[0,0,0],filters=[p.printCyan,p.printMagenta,p.printYellow].map(v=>2**(-v/100)),exposure=2**p.printExposure,contrast=1+p.printContrast/100,fade=p.printFade/100;for(let i=0;i<data.length;i+=4)for(let k=0;k<3;k++){const value=data[i+k]/255;let v=(value*filters[k]*exposure-.5)*contrast+.5;v=v*(1-fade*.3)+fade*.065;v=v*(white[k]-black[k])+black[k];data[i+k]+=(v*255-data[i+k])*mix;}}
function sample(a,w,h,x,y,k){x=clamp(x,0,w-1);y=clamp(y,0,h-1);const ix=Math.floor(x),iy=Math.floor(y),jx=Math.min(w-1,ix+1),jy=Math.min(h-1,iy+1),fx=x-ix,fy=y-iy;return (a[(iy*w+ix)*4+k]*(1-fx)+a[(iy*w+jx)*4+k]*fx)*(1-fy)+(a[(jy*w+ix)*4+k]*(1-fx)+a[(jy*w+jx)*4+k]*fx)*fy;}
function prism(data,w,h,p){const amount=clamp(p.prism/100);if(!amount)return;const original=data.slice(),angle=p.prismAngle*Math.PI/180,dist=p.prismDistance/100*Math.min(w,h),cx=p.prismCenterX/100*w,cy=p.prismCenterY/100*h,protect=p.prismProtect/100*.6,feather=Math.max(.01,p.prismFeather/100*.6),count=p.prismMode===1?3:p.prismMode===2?2:1,directions=Array.from({length:count},(_,j)=>{const a=angle+(p.prismMode===1?j*Math.PI*2/3:j*Math.PI);return [Math.cos(a),Math.sin(a)];});for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,r=Math.hypot((x-cx)/w,(y-cy)/h);let gate=clamp((r-protect)/feather);gate=gate*gate*(3-2*gate);const mix=gate*amount;if(!mix)continue;for(let k=0;k<3;k++){let total=0;for(let j=0;j<count;j++){const [cos,sin]=directions[j],offset=dist*(1+(k-1)*p.prismDispersion/250);let sx=x+cos*offset,sy=y+sin*offset;if(p.prismMode===2){const dx=x-cx,dy=y-cy,dot=dx*cos+dy*sin;sx=x-2*dot*cos+cos*offset;sy=y-2*dot*sin+sin*offset;}total+=sample(original,w,h,sx,sy,k);}data[i+k]+=(total/count-data[i+k])*mix;}}}
const assets=new Map();function setAsset(id,bitmap,precise=null){assets.get(id)?.bitmap.close?.();assets.set(id,{bitmap,precise,prepared:null,key:null});}function prune(ids){for(const [id,a]of assets)if(!ids.includes(id)){a.bitmap.close?.();assets.delete(id);}}
function refs(settings){const ids=new Set();function walk(n){if(!n||n.enabled===false||n.mix===0)return;const p=n.adjustments||n;if(p.doubleAmount&&p.doubleSource)ids.add(p.doubleSource);if(n.legacyStage)walk(n.legacyStage);for(const v of n.nodes||[])walk(v);for(const l of n.looks||[])if(l.enabled!==false&&l.amount!==0){if(l.values?.recipeNodes)l.values.recipeNodes.forEach(walk);else walk(l.values);}}walk(settings);return [...ids];}
function double(data,w,h,p){if(!p.doubleAmount||!p.doubleSource)return;const asset=assets.get(p.doubleSource);if(!asset)throw Error('The second exposure is unavailable. Choose its image again.');const max=Math.max(w,h),key=String(max);if(asset.key!==key){if(typeof PrecisionSource!=='undefined'){asset.prepared=PrecisionSource.prepare(asset.bitmap,asset.precise,Imaging.defaults,max);}else{const scale=Math.min(1,max/Math.max(asset.bitmap.width,asset.bitmap.height)),c=new OffscreenCanvas(Math.max(1,Math.round(asset.bitmap.width*scale)),Math.max(1,Math.round(asset.bitmap.height*scale))),ctx=c.getContext('2d');ctx.drawImage(asset.bitmap,0,0,c.width,c.height);asset.prepared={data:ctx.getImageData(0,0,c.width,c.height).data,width:c.width,height:c.height};}asset.key=key;}const {data:b,width:bw,height:bh}=asset.prepared,scale=Math.max(w/bw,h/bh)*Math.max(.1,p.doubleScale/100),angle=-p.doubleRotation*Math.PI/180,cos=Math.cos(angle),sin=Math.sin(angle),cx=w*(.5+p.doubleX/100),cy=h*(.5+p.doubleY/100),amount=clamp(p.doubleAmount/100),soft=.05+p.doubleSoftness/100*.9;
for(let y=0;y<h;y++)for(let x=0;x<w;x++){const dx=x-cx,dy=y-cy,sx=(dx*cos-dy*sin)/scale+bw/2,sy=(dx*sin+dy*cos)/scale+bh/2;if(sx<0||sy<0||sx>bw-1||sy>bh-1)continue;const i=(y*w+x)*4,lum=clamp((data[i]*.2126+data[i+1]*.7152+data[i+2]*.0722)/255);let weight=p.doubleTarget===1?clamp((.5+soft/2-lum)/soft):p.doubleTarget===2?clamp((lum-.5+soft/2)/soft):1;weight=weight*weight*(3-2*weight);const mix=amount*weight*clamp(sample(b,bw,bh,sx,sy,3)/255);for(let k=0;k<3;k++){const a=data[i+k]/255,v=sample(b,bw,bh,sx,sy,k)/255,result=p.doubleMode===1?1-(1-a)*(1-v):p.doubleMode===2?a*v:p.doubleMode===3?Math.max(a,v):v;data[i+k]+=(result*255-data[i+k])*mix;}}}
const api={defaults,compression,printing,prism,double,setAsset,prune,refs,sample};if(typeof module!=='undefined')module.exports=api;else scope.Creative=api;
})(globalThis);
