(()=>{
const operations=[['develop','Full Develop'],['diffusion','Diffusion / mist'],['glow','Glow / bloom'],['halation','Halation'],['flare','Anamorphic flare'],['grain','Grain'],['fade','Fade'],['matte','Matte shadows'],...FX.nodeTypes.map(([id,label])=>[id,label])];
for(const [id,label]of operations)$('nodeOperation').append(new Option(label,id));
let signature='';
const currentNode=()=>documentSettings.nodes.find(n=>n.uid===activeNodeUid);
function choose(uid){activeNodeUid=uid||documentSettings.nodes[0]?.uid||null;documentSettings.selectedNode=activeNodeUid;const node=currentNode();window.advancedUI.setTool(node&&node.operation!=='develop'?({color:'color',grade:'color'}[node.operation]||FX.nodeTypes.find(t=>t[0]===node.operation)?.[2]||'effects'):'light');sync();}
function move(step){const nodes=documentSettings.nodes,i=nodes.findIndex(n=>n.uid===activeNodeUid),j=i+step;if(i<0||j<0||j>=nodes.length)return;mutate(()=>{[nodes[i],nodes[j]]=[nodes[j],nodes[i]];});}
function operationFor(key){if(Imaging.compositionKeys.includes(key))return 'composition';if(/^hsl/.test(key))return 'color';if(/^grade/.test(key))return 'grade';if(['clarity','texture','sharpen','denoise'].includes(key))return 'detail';if(/^(glow|halation|bloom|diffusion|flare)/.test(key))return 'bloom';if(/^(grain|fade|matte)/.test(key))return 'film';if(/^vignette/.test(key))return 'vignette';if(/^mask|^addBrush|^addLinear|^addRadial|^deleteMask/.test(key))return 'masks';return 'light';}
function canEdit(){return true;}
function syncNodes(){if(!currentNode())activeNodeUid=documentSettings.nodes[0]?.uid||null;const nodes=documentSettings.nodes,node=currentNode(),at=nodes.indexOf(node),active=!!img;const key=JSON.stringify(nodes.map(n=>[n.uid,n.label,n.operation,n.enabled,n.operations?.length]))+'|'+activeNodeUid+'|'+active;
if(key!==signature){signature=key;const graph=$('nodeGraph');graph.replaceChildren();const endpoint=text=>{const e=document.createElement('span');e.className='node-end';e.textContent=text;graph.append(e);};endpoint('Original');const targets=$('editTarget');targets.replaceChildren(new Option('Base photo',''));if(!nodes.length){const hint=document.createElement('span');hint.className='node-empty';hint.textContent='No nodes yet. Add one and choose its operation.';graph.append(hint);}for(const [index,n]of nodes.entries()){targets.append(new Option(n.label,n.uid));const wire=document.createElement('span');wire.className='node-wire';wire.textContent='→';graph.append(wire);const b=document.createElement('button');b.className='effect-node'+(n.uid===activeNodeUid?' selected':'')+(n.enabled?'':' bypassed');b.dataset.node=n.uid;b.draggable=active;b.disabled=!active;b.setAttribute('aria-label',n.label+' node');const tag=document.createElement('small');tag.textContent=String(index+1).padStart(2,'0')+' · '+(n.operations?.length>1?n.operations.length+' effects':(operations.find(o=>o[0]===n.operation)?.[1]||'Develop'));const name=document.createElement('span');name.textContent=n.label;b.append(tag,name);b.onclick=()=>choose(n.uid);b.ondragstart=e=>e.dataTransfer.setData('text/lith-node',n.uid);b.ondragover=e=>{e.preventDefault();e.stopPropagation();};b.ondrop=e=>{e.preventDefault();e.stopPropagation();document.body.classList.remove('dragging');const from=e.dataTransfer.getData('text/lith-node');if(from===n.uid||!nodes.some(v=>v.uid===from))return;mutate(()=>{const [item]=nodes.splice(nodes.findIndex(v=>v.uid===from),1);nodes.splice(nodes.findIndex(v=>v.uid===n.uid),0,item);activeNodeUid=from;});};b.onkeydown=e=>{if(e.altKey&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();activeNodeUid=n.uid;move(e.key==='ArrowLeft'?-1:1);}};graph.append(b);}const wire=document.createElement('span');wire.className='node-wire';wire.textContent='→';graph.append(wire);endpoint('Output');}
$('editTarget').value=activeNodeUid||'';$('editTarget').disabled=!active;$('nodeLabel').disabled=!active||!node;$('nodeOperation').disabled=!active||!node;if(document.activeElement!==$('nodeLabel'))$('nodeLabel').value=node?.label||'';$('nodeOperation').value=node?.operation||'develop';$('nodeAdd').disabled=!active||nodes.length>=24;$('nodeRemove').disabled=!active||!node||nodes.length<=1;$('nodeBypass').disabled=!active||!node;$('nodeBypass').textContent=node?.enabled?'Bypass selected':'Enable selected';$('nodeLeft').disabled=!active||at<=0;$('nodeRight').disabled=!active||at<0||at===nodes.length-1;$('nodeHelp').textContent=node?'All tools and looks are saved in '+node.label+'.':'All Develop tools edit the base photo. Add nodes for independent effects.';
document.querySelectorAll('#controls input,#advancedControls input,#advancedControls select,#maskPanel input,#maskPanel select,#maskPanel button,#cropControls input').forEach(el=>{el.disabled=!active||!canEdit(el.id)||['addBrush','addLinear','addRadial','maskAddColor'].includes(el.id)&&(settings.masks||[]).length>=12;el.closest('.slider-row')?.classList.toggle('control-unavailable',el.disabled&&active);});document.querySelectorAll('.preset').forEach(el=>{el.disabled=!active;});$('autoTone').disabled=!active||!canEdit('exposure');}
$('nodeAdd').onclick=()=>{if(!img)return;mutate(()=>{const uid=crypto.randomUUID();documentSettings.nodes.push({...Imaging.newNode('Node '+(documentSettings.nodes.length+1)),uid});activeNodeUid=uid;});choose(activeNodeUid);};$('editTarget').onchange=()=>choose($('editTarget').value);$('nodeLabel').onchange=()=>{const value=$('nodeLabel').value.trim().slice(0,60);if(!currentNode())return;mutate(()=>currentNode().label=value||'Untitled adjustment');};$('nodeOperation').onchange=()=>{if(!currentNode())return;mutate(()=>{currentNode().operation=$('nodeOperation').value;currentNode().operations=[{type:currentNode().operation,mix:100}];});choose(activeNodeUid);};$('nodeBypass').onclick=()=>{if(currentNode())mutate(()=>currentNode().enabled=!currentNode().enabled);};$('nodeLeft').onclick=()=>move(-1);$('nodeRight').onclick=()=>move(1);$('nodeRemove').onclick=()=>{if(!currentNode()||documentSettings.nodes.length<=1)return;mutate(()=>{documentSettings.nodes=documentSettings.nodes.filter(n=>n.uid!==activeNodeUid);activeNodeUid=null;});};$('toggleNodes').onclick=()=>{$('nodeGraph').hidden=!$('nodeGraph').hidden;};
window.nodeUI={sync:syncNodes,choose,canEdit,targetId:()=>activeNodeUid};sync();
})();
