(function(scope){
const Creative=typeof module!=="undefined"?require("./creative-effects.js"):scope.Creative;
const Optics=typeof module!=="undefined"?require("./optics.js"):scope.Optics;
const extraDefaults={clarity:0,texture:0,sharpen:0,denoise:0,grainSize:35,grainRoughness:50,grainColor:0,halationThreshold:65,halationRadius:40,halationTight:70,halationMid:65,halationWide:40,halationTint:'#ff5631',glowRadius:40,vignette:0,vignetteFeather:65,border:0,borderColor:'#ffffff',borderBottom:0,gradeBalance:0,gradeBlend:50,gradeShadowsColor:'#4078c0',gradeShadows:0,gradeMidtonesColor:'#db9270',gradeMidtones:0,gradeHighlightsColor:'#ffcb87',gradeHighlights:0,gradeGlobalColor:'#e8ab71',gradeGlobal:0,curveBlack:0,curveShadow:0,curveMid:0,curveHighlight:0,curveWhite:0};
Object.assign(extraDefaults,Optics.defaults,Creative.defaults);
const colorBands=[['Red',0],['Orange',30],['Yellow',60],['Green',120],['Aqua',180],['Blue',240],['Purple',275],['Magenta',315]];
for(const [name]of colorBands)for(const control of ['Hue','Sat','Lum'])extraDefaults['hsl'+name+control]=0;
const nodeTypes=[...Creative.Playful.types.map(k=>[k,({shutter:'Shutter drag',fisheye:'Fisheye',colorBleed:'Color bleeding',lightLeak:'Light leaks',bokeh:'Bokeh painter',relight:'Artificial lights'})[k],'effects']),['light','Light & curve','light'],['color','Color mixer','color'],['grade','Color grading','color'],['detail','Detail','detail'],['masks','Local masks','mask'],['bloom','Optical effects','effects'],['film','Film finish','effects'],['prism','Prism & glass','effects'],['double','Double exposure','effects'],['darkroom','Darkroom printing','color'],['vignette','Vignette','effects']];
extraDefaults.nodes=[];extraDefaults._schema=4;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const canvasFor=(w,h)=>{const c=typeof document==='undefined'?new OffscreenCanvas(w,h):document.createElement('canvas');c.width=w;c.height=h;return c;};
function rgb(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255);}
function blur(c,r){const out=canvasFor(c.width,c.height),ctx=out.getContext('2d');ctx.filter='blur('+Math.max(.1,r)+'px)';ctx.drawImage(c,0,0);return out;}
function curveValue(v,s){const values=[clamp(s.curveBlack/100),clamp(.25+s.curveShadow/100),clamp(.5+s.curveMid/100),clamp(.75+s.curveHighlight/100),clamp(1+s.curveWhite/100)];const at=clamp(v)*4,lo=Math.min(3,Math.floor(at)),f=at-lo;const delta=values.slice(1).map((v,i)=>v-values[i]),slope=i=>i===0?delta[0]:i===4?delta[3]:delta[i-1]*delta[i]<=0?0:2*delta[i-1]*delta[i]/(delta[i-1]+delta[i]);const f2=f*f,f3=f2*f;return clamp((2*f3-3*f2+1)*values[lo]+(f3-2*f2+f)*slope(lo)+(-2*f3+3*f2)*values[lo+1]+(f3-f2)*slope(lo+1));}
function curves(data,s){if(!['Black','Shadow','Mid','Highlight','White'].some(k=>s['curve'+k]))return;const lut=Uint8ClampedArray.from({length:256},(_,i)=>curveValue(i/255,s)*255);for(let i=0;i<data.length;i+=4)for(let k=0;k<3;k++)data[i+k]=lut[data[i+k]];}
function hsl(data,s){const bands=colorBands.filter(([n])=>s['hsl'+n+'Hue']||s['hsl'+n+'Sat']||s['hsl'+n+'Lum']);if(!bands.length)return;for(let i=0;i<data.length;i+=4){const r=data[i]/255,g=data[i+1]/255,b=data[i+2]/255,max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;if(d<.00001)continue;let h=max===r?((g-b)/d+6)%6:max===g?(b-r)/d+2:(r-g)/d+4;h*=60;let l=(max+min)/2,sat=d/(1-Math.abs(2*l-1)),dh=0,ds=0,dl=0;for(const [n,center]of bands){const distance=Math.min(Math.abs(h-center),360-Math.abs(h-center)),range=n==='Red'||n==='Orange'||n==='Yellow'?38:50;const weight=Math.max(0,1-distance/range);dh+=(s['hsl'+n+'Hue']||0)*weight;ds+=(s['hsl'+n+'Sat']||0)*weight/100;dl+=(s['hsl'+n+'Lum']||0)*weight/200;}h=(h+dh+360)%360;sat=clamp(sat*(1+ds));l=clamp(l+dl);const c=(1-Math.abs(2*l-1))*sat,x=c*(1-Math.abs(h/60%2-1)),m=l-c/2;const v=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];for(let k=0;k<3;k++)data[i+k]=(v[k]+m)*255;}}
function grade(data,s){const groups=['Shadows','Midtones','Highlights','Global'].map(n=>({n,color:rgb(s['grade'+n+'Color']),amount:s['grade'+n]/100}));if(!groups.some(g=>g.amount))return;const overlap=.5+s.gradeBlend/100;for(let i=0;i<data.length;i+=4){const lum=(.2126*data[i]+.7152*data[i+1]+.0722*data[i+2])/255,bias=s.gradeBalance/250;const l=clamp(lum+bias);for(const group of groups){if(!group.amount)continue;const weight=group.n==='Global'?1:group.n==='Shadows'?Math.pow(1-l,2/overlap):group.n==='Highlights'?Math.pow(l,2/overlap):Math.pow(Math.max(0,1-Math.abs(l-.5)*2),1/overlap);const gray=.2126*group.color[0]+.7152*group.color[1]+.0722*group.color[2];for(let k=0;k<3;k++)data[i+k]+=((group.color[k]-gray)*255)*group.amount*weight*.65;}}}
function detail(c,s){if(!s.clarity&&!s.texture&&!s.sharpen&&!s.denoise)return;const ctx=c.getContext('2d',{willReadFrequently:true});let image=ctx.getImageData(0,0,c.width,c.height);const short=Math.min(c.width,c.height);if(s.denoise){const smooth=blur(c,Math.max(.5,short*.0015)).getContext('2d').getImageData(0,0,c.width,c.height);for(let i=0;i<image.data.length;i+=4)for(let k=0;k<3;k++)image.data[i+k]+=(smooth.data[i+k]-image.data[i+k])*s.denoise/140;ctx.putImageData(image,0,0);}for(const [amount,radius,weight]of [[s.clarity,short*.014,1.3],[s.texture,short*.0023,1.2],[s.sharpen,short*.0008,1.8]]){if(!amount)continue;const smooth=blur(c,Math.max(.5,radius)).getContext('2d').getImageData(0,0,c.width,c.height);for(let i=0;i<image.data.length;i+=4){const lum=(image.data[i]+image.data[i+1]+image.data[i+2])/765,mid=.4+.6*(1-Math.abs(lum-.5)*2);for(let k=0;k<3;k++)image.data[i+k]+=(image.data[i+k]-smooth.data[i+k])*amount/100*weight*mid;}ctx.putImageData(image,0,0);}}
function bloom(c,s){if(!s.glow&&!s.halation&&!s.diffusion&&!s.flare)return;Optics.diffusion(c,s);const ctx=c.getContext('2d',{willReadFrequently:true}),w=c.width,h=c.height,original=ctx.getImageData(0,0,w,h);const threshold=clamp(s.halationThreshold/100,0,.98),tint=rgb(s.halationTint);if(s.halation){const glow=canvasFor(w,h),g=glow.getContext('2d'),image=new ImageData(new Uint8ClampedArray(original.data),w,h);for(let i=0;i<image.data.length;i+=4){const l=Math.max(original.data[i],original.data[i+1],original.data[i+2])/255;const a=clamp((l-threshold)/(1-threshold));image.data[i]=tint[0]*255;image.data[i+1]=tint[1]*255;image.data[i+2]=tint[2]*255;image.data[i+3]=original.data[i+3]*a*a;}g.putImageData(image,0,0);const radius=Math.max(w,h)*(.001+s.halationRadius*.00035);for(const [mult,amount]of [[.22,s.halationTight],[1,s.halationMid],[3.1,s.halationWide]]){if(!amount)continue;const layer=blur(glow,Math.max(.7,radius*mult));const lx=layer.getContext('2d');lx.globalCompositeOperation='destination-out';lx.globalAlpha=.78;lx.drawImage(glow,0,0);ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=clamp(s.halation/100*amount/100*.95);ctx.drawImage(layer,0,0);ctx.restore();}}Optics.bloom(c,s);Optics.flare(c,s);}

function noise(x,y,channel=0){let n=(x*374761393+y*668265263+channel*1442695041)|0;n=Math.imul(n^(n>>>13),1274126177);return ((n>>>0)/4294967295-.5);}
function film(data,w,h,s,originalW,originalH){Optics.matte(data,w,h,s);const fade=s.fade/100;if(fade)for(let i=0;i<data.length;i+=4)for(let k=0;k<3;k++)data[i+k]=data[i+k]*(1-fade*.22)+fade*17.85;if(!s.grain)return;const cell=1+s.grainSize/12,rough=s.grainRoughness/100,col=s.grainColor/100;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const xx=x/w*originalW/cell,yy=y/h*originalH/cell,ix=Math.floor(xx),iy=Math.floor(yy),fx=xx-ix,fy=yy-iy;const smooth=(ch)=>{const a=noise(ix,iy,ch)*(1-fx)+noise(ix+1,iy,ch)*fx,b=noise(ix,iy+1,ch)*(1-fx)+noise(ix+1,iy+1,ch)*fx;return a*(1-fy)+b*fy;};const mono=smooth(0)*(1-rough)+noise(ix,iy)*rough;const i=(y*w+x)*4;if(!col){const n=mono*s.grain*.65;data[i]+=n;data[i+1]+=n;data[i+2]+=n;}else for(let k=0;k<3;k++)data[i+k]+=(mono*(1-col)+smooth(k+1)*col)*s.grain*.65;}}
function vignette(data,w,h,s){if(!s.vignette)return;const inner=.1+s.vignetteFeather/160;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const d=Math.hypot((x/w-.5)*1.414,(y/h-.5)*1.414),f=clamp((d-(1-inner))/(inner||1)),weight=f*f*(3-2*f)*s.vignette/100*.8,i=(y*w+x)*4;for(let k=0;k<3;k++)data[i+k]=s.vignette>=0?data[i+k]*(1-weight):data[i+k]+(255-data[i+k])*-weight;}}
function borderGeometry(w,h,s){const b=Math.round(Math.min(w,h)*(s.border||0)/100);return {inset:b,bottom:b+Math.round(b*(s.borderBottom||0)/100),width:w+2*b,height:h+2*b+Math.round(b*(s.borderBottom||0)/100)};}
function border(c,s,max){const g=borderGeometry(c.width,c.height,s);if(!g.inset)return c;const scale=max?Math.min(1,max/Math.max(g.width,g.height)):1,out=canvasFor(Math.max(1,Math.round(g.width*scale)),Math.max(1,Math.round(g.height*scale))),ctx=out.getContext('2d');ctx.fillStyle=s.borderColor;ctx.fillRect(0,0,out.width,out.height);ctx.drawImage(c,g.inset*scale,g.inset*scale,c.width*scale,c.height*scale);return out;}
const api={Optics,extraDefaults,colorBands,nodeTypes,canvasFor,curves,curveValue,hsl,grade,detail,bloom,film,vignette,borderGeometry,border};if(typeof module!=='undefined')module.exports=api;else scope.FX=api;
})(globalThis);
