// Float kernels use encoded-sRGB channel values in 0..255 units; values are not quantized between edits.
const FloatKernels=(()=>{
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
function point(data,p,mode='all'){if(mode==='all'||mode==='light'){if(['exposure','contrast','highlights','shadows','temperature','tint','saturation','vibrance'].some(k=>p[k]))Imaging.pixels(data,{...p,fade:0});if(['curveBlack','curveShadow','curveMid','curveHighlight','curveWhite'].some(k=>p[k])){const v=[clamp(p.curveBlack/100),clamp(.25+p.curveShadow/100),clamp(.5+p.curveMid/100),clamp(.75+p.curveHighlight/100),clamp(1+p.curveWhite/100)],d=v.slice(1).map((x,i)=>x-v[i]),m=[d[0],0,0,0,d[3]];for(let i=1;i<4;i++)m[i]=d[i-1]*d[i]>0?2*d[i-1]*d[i]/(d[i-1]+d[i]):0;for(let i=0;i<data.length;i+=4)for(let k=0;k<3;k++){const at=clamp(data[i+k]/255)*4,j=Math.min(3,Math.floor(at)),f=at-j,f2=f*f,f3=f2*f;data[i+k]=clamp((2*f3-3*f2+1)*v[j]+(f3-2*f2+f)*m[j]+(-2*f3+3*f2)*v[j+1]+(f3-f2)*m[j+1])*255;}}}if((mode==='all'||mode==='light')&&p.highlightCompression)Creative.compression(data,p);if(mode==='all'||mode==='color')FX.hsl(data,p);if(mode==='all'||mode==='grade')FX.grade(data,p);return data;}
function blur(input,w,h,radius){let a=input.slice(),b=new Float32Array(a.length);const radii=Array(3).fill(Math.max(1,Math.round(radius)));for(const r of radii)for(const horizontal of [true,false]){const outer=horizontal?h:w,inner=horizontal?w:h,stride=horizontal?4:w*4;for(let line=0;line<outer;line++){const base=horizontal?line*w*4:line*4;for(let k=0;k<4;k++){let sum=0;for(let j=-r;j<=r;j++)sum+=a[base+clamp(j,0,inner-1)*stride+k];for(let j=0;j<inner;j++){b[base+j*stride+k]=sum/(2*r+1);sum+=a[base+Math.min(inner-1,j+r+1)*stride+k]-a[base+Math.max(0,j-r)*stride+k];}}}[a,b]=[b,a];}return a;}
function extract(data,p,halation=false){const out=new Float32Array(data.length),tint=FX.Optics===undefined?[1,1,1]:[1,3,5].map(i=>parseInt((halation?p.halationTint:p.bloomTint).slice(i,i+2),16)/255);for(let i=0;i<data.length;i+=4){const lum=halation?Math.max(data[i],data[i+1],data[i+2])/255:(data[i]*.2126+data[i+1]*.7152+data[i+2]*.0722)/255;const t=clamp(p.halationThreshold/100,0,.98),weight=halation?clamp((lum-t)/(1-t))**2:Optics.gateWeight(lum,p.bloomThreshold,p.bloomKnee);for(let k=0;k<3;k++)out[i+k]=(halation?255:data[i+k])*tint[k]*weight;out[i+3]=data[i+3]*weight;}return out;}
function screen(data,light,amount,inner=null){for(let i=0;i<data.length;i+=4)for(let k=0;k<3;k++){const v=light[i+k]*(inner?1-inner[i+3]/255*.78:1);data[i+k]+= (255-data[i+k])*v/255*amount;}return data;}
function diffuse(data,smooth,p){for(let i=0;i<data.length;i+=4){const lum=(data[i]*.2126+data[i+1]*.7152+data[i+2]*.0722)/255,protection=1-p.diffusionProtect/100*(1-lum)**2,mix=p.diffusion/100*(p.diffusionMode===2?.7:.25)*protection;for(let k=0;k<3;k++){data[i+k]+=(smooth[i+k]-data[i+k])*mix;if(p.diffusionMode===0)data[i+k]+=(255-data[i+k])*p.diffusion/100*.06*protection;}}return data;}
function detail(data,smooth,amount,weight,denoise=false){for(let i=0;i<data.length;i+=4){const mid=.4+.6*(1-Math.abs((data[i]+data[i+1]+data[i+2])/765-.5)*2);for(let k=0;k<3;k++)data[i+k]+=denoise?(smooth[i+k]-data[i+k])*amount/140:(data[i+k]-smooth[i+k])*amount/100*weight*mid;}return data;}
function mask(data,coverage,p){const local=data.slice();Imaging.pixels(local,{...p,fade:0});for(let i=0;i<data.length;i+=4)for(let k=0;k<3;k++)data[i+k]+=(local[i+k]-data[i+k])*coverage[i+3]/255;return data;}
function film(data,w,h,p,ow,oh){if(p.matte){const histogram=new Uint32Array(256);let count=0;for(let i=0;i<data.length;i+=16)if(data[i+3]){histogram[Math.round(clamp((data[i]*.2126+data[i+1]*.7152+data[i+2]*.0722)/255)*255)]++;count++;}let black=0,n=0;for(;black<255;black++){n+=histogram[black];if(n>=count*.08)break;}const dynamic=p.matteDynamic/100,lift=p.matte/100*.22*((1-dynamic)+dynamic*clamp((.32-black/255)/.32,.15,1)),range=.08+p.matteRange*.007,soft=.5+p.matteSoftness/50,tint=[1,3,5].map(i=>parseInt(p.matteColor.slice(i,i+2),16)/255),gray=tint[0]*.2126+tint[1]*.7152+tint[2]*.0722;for(let i=0;i<data.length;i+=4){const lum=(data[i]*.2126+data[i+1]*.7152+data[i+2]*.0722)/255,amount=lift*clamp(1-lum/range)**soft;for(let k=0;k<3;k++)data[i+k]+=255*amount*(1+(tint[k]-gray)*p.matteTint/100*3);}}FX.film(data,w,h,{...p,matte:0},ow,oh);}
return {point,blur,extract,screen,diffuse,detail,mask,film};})();
