// Float32 storage buffers keep image values on the GPU across color, optical and mask passes.
const FloatGPU=(()=>{let device,pipe,pending,failed=false;const cache={data:null,buffer:null};const pool=[];let pooledBytes=0;const maskBuffers=new Map();let maskBytes=0,frame=0;
const shader=`
struct Params { v:array<vec4f,32> };
@group(0) @binding(0) var<storage,read> src:array<vec4f>;
@group(0) @binding(1) var<storage,read_write> dst:array<vec4f>;
@group(0) @binding(2) var<storage,read> referenceImage:array<vec4f>;
@group(0) @binding(3) var<storage,read> aux:array<vec4f>;
@group(0) @binding(4) var<uniform> p:Params;
fn noise(x:i32,y:i32,ch:u32)->f32{var n=u32(x)*374761393u+u32(y)*668265263u+ch*1442695041u;n=(n^(n>>13u))*1274126177u;return f32(n)/4294967295.0-.5;}
fn smoothNoise(x:f32,y:f32,ch:u32)->f32{let ix=i32(floor(x));let iy=i32(floor(y));let fx=fract(x);let fy=fract(y);return mix(mix(noise(ix,iy,ch),noise(ix+1,iy,ch),fx),mix(noise(ix,iy+1,ch),noise(ix+1,iy+1,ch),fx),fy);}
fn tonal(rgb:vec3f)->vec3f{let lum=dot(rgb,vec3f(.2126,.7152,.0722));let low=1.0-lum;let tone=p.v[1].w*.0042*low*low+p.v[1].z*.0042*lum*lum;var c=(rgb*exp2(p.v[1].x)+tone-vec3f(.5))*(1.0+p.v[1].y/100.0)+vec3f(.5)+vec3f(p.v[2].x*.0011+p.v[2].y*.00035,-p.v[2].y*.00065,-p.v[2].x*.0011+p.v[2].y*.00035);let gray=dot(c,vec3f(.2126,.7152,.0722));let spread=max(c.r,max(c.g,c.b))-min(c.r,min(c.g,c.b));return vec3f(gray)+(c-vec3f(gray))*(1.0+p.v[2].z/100.0+p.v[2].w/100.0*(1.0-min(1.0,spread)));}
fn curve(x:f32)->f32{let points=array<f32,5>(clamp(p.v[3].x/100.0,0.0,1.0),clamp(.25+p.v[3].y/100.0,0.0,1.0),clamp(.5+p.v[3].z/100.0,0.0,1.0),clamp(.75+p.v[3].w/100.0,0.0,1.0),clamp(1.0+p.v[4].x/100.0,0.0,1.0));var d:array<f32,4>;for(var i=0;i<4;i++){d[i]=points[i+1]-points[i];}var slopes:array<f32,5>;slopes[0]=d[0];slopes[4]=d[3];for(var i=1;i<4;i++){slopes[i]=0;if(d[i-1]*d[i]>0){slopes[i]=2*d[i-1]*d[i]/(d[i-1]+d[i]);}}let at=clamp(x,0.0,1.0)*4;let lo=min(3,i32(floor(at)));let f=at-f32(lo);let f2=f*f;let f3=f2*f;return clamp((2*f3-3*f2+1)*points[lo]+(f3-2*f2+f)*slopes[lo]+(-2*f3+3*f2)*points[lo+1]+(f3-f2)*slopes[lo+1],0.0,1.0);}
fn hsl(c:vec3f)->vec3f{let hi=max(c.r,max(c.g,c.b));let low=min(c.r,min(c.g,c.b));let delta=hi-low;if(delta<.00001){return c;}var h=select(select((c.r-c.g)/delta+4,(c.b-c.r)/delta+2,hi==c.g),((c.g-c.b)/delta+6)%6,hi==c.r)*60;var l=(hi+low)/2;var sat=delta/(1-abs(2*l-1));var dh=0.0;var ds=0.0;var dl=0.0;let centers=array<f32,8>(0,30,60,120,180,240,275,315);for(var i=0;i<8;i++){let dist=abs(h-centers[i]);let weight=max(0.0,1-min(dist,360-dist)/select(50.0,38.0,i<3));dh+=p.v[8+i].x*weight;ds+=p.v[8+i].y*weight/100;dl+=p.v[8+i].z*weight/200;}h=(h+dh+360)%360;sat=clamp(sat*(1+ds),0.0,1.0);l=clamp(l+dl,0.0,1.0);let ch=(1-abs(2*l-1))*sat;let x=ch*(1-abs((h/60)%2-1));let m=l-ch/2;var out=vec3f(ch,x,0);if(h>=300){out=vec3f(ch,0,x);}else if(h>=240){out=vec3f(x,0,ch);}else if(h>=180){out=vec3f(0,x,ch);}else if(h>=120){out=vec3f(0,ch,x);}else if(h>=60){out=vec3f(x,ch,0);}return out+vec3f(m);}
fn grading(rgb:vec3f)->vec3f{let l=clamp(dot(rgb,vec3f(.2126,.7152,.0722))+p.v[5].x/250,0.0,1.0);let overlap=.5+p.v[5].y/100;var out=rgb;for(var i=0;i<4;i++){var weight=1.0;if(i==0){weight=pow(1-l,2/overlap);}else if(i==1){weight=pow(max(0.0,1-abs(l-.5)*2),1/overlap);}else if(i==2){weight=pow(l,2/overlap);}let tint=p.v[16+i];let gray=dot(tint.rgb,vec3f(.2126,.7152,.0722));out+=(tint.rgb-vec3f(gray))*tint.a/100*weight*.65;}return out;}
fn samplePrism(pos:vec2f,w:u32,h:u32)->vec4f{let q=clamp(pos,vec2f(0),vec2f(f32(w-1),f32(h-1)));let lo=vec2u(floor(q));let hi=min(lo+vec2u(1),vec2u(w-1,h-1));let f=fract(q);return mix(mix(src[lo.y*w+lo.x],src[lo.y*w+hi.x],f.x),mix(src[hi.y*w+lo.x],src[hi.y*w+hi.x],f.x),f.y);}
@compute @workgroup_size(64) fn main(@builtin(global_invocation_id) tid:vec3u){let w=u32(p.v[0].x);let h=u32(p.v[0].y);let i=tid.x;if(i>=w*h){return;}let op=u32(p.v[0].z);let a=src[i];var out=a;
if(op==0){var c=a.rgb/255;let mode=u32(p.v[0].w);if(mode==0||mode==1){if(p.v[4].y>0){c=tonal(c);}if(p.v[4].z>0){c=vec3f(curve(c.r),curve(c.g),curve(c.b));}if(p.v[22].x>0){let lum=max(c.r,max(c.g,c.b));let start=p.v[22].y/100;let room=1-start;if(lum>start){let x=lum-start;let compressed=start+room*x/(room+x);c*=mix(1.0,compressed/lum,p.v[22].x/100);}}}if((mode==0||mode==2)&&p.v[4].w>0){c=hsl(c);}if(mode==0||mode==3){c=grading(c);}out=vec4f(c*255,a.a);}
else if(op==1||op==2){let radius=i32(p.v[6].x);let x=i32(i%w);let y=i32(i/w);var sum=vec4f(0);for(var k=-radius;k<=radius;k++){let xx=select(x,clamp(x+k,0,i32(w)-1),op==1);let yy=select(clamp(y+k,0,i32(h)-1),y,op==1);sum+=src[u32(yy)*w+u32(xx)];}out=sum/f32(2*radius+1);}
else if(op==3){out=mix(referenceImage[i],a,p.v[6].x);}
else if(op==4){let halo=p.v[6].w>0;let lum=select(dot(a.rgb,vec3f(.2126,.7152,.0722))/255,max(a.r,max(a.g,a.b))/255,halo);var weight=0.0;if(halo){let t=clamp(p.v[6].x/100,0.0,.98);weight=pow(clamp((lum-t)/(1-t),0.0,1.0),2.0);}else{let knee=p.v[6].y/100;let t=p.v[6].x/100;if(knee<=.00001){weight=select(0.0,1.0,lum>t);}else{let f=clamp((lum-t)/knee,0.0,1.0);weight=f*f*(3-2*f);}}out=vec4f(select(a.rgb,vec3f(255),halo)*p.v[7].rgb*weight,a.a*weight);}
else if(op==5){let original=referenceImage[i];let protect=select(1.0,1-aux[i].a/255*.78,p.v[6].y>0);out=vec4f(original.rgb+(vec3f(255)-original.rgb)*a.rgb/255*p.v[6].x*protect,original.a);}
else if(op==6){let original=referenceImage[i];let lum=dot(original.rgb,vec3f(.2126,.7152,.0722))/255;let protection=1-p.v[6].z/100*pow(1-lum,2.0);let blend=p.v[6].x/100*select(.25,.7,p.v[6].y==2)*protection;var c=mix(original.rgb,a.rgb,blend);if(p.v[6].y==0){c+=(vec3f(255)-c)*p.v[6].x/100*.06*protection;}out=vec4f(c,original.a);}
else if(op==7){out=vec4f(mix(a.rgb,tonal(a.rgb/255)*255,referenceImage[i].a/255),a.a);}
else if(op==8){let original=referenceImage[i];let mid=.4+.6*(1-abs((original.r+original.g+original.b)/765-.5)*2);var c=original.rgb+(original.rgb-a.rgb)*p.v[6].x/100*p.v[6].y*mid;if(p.v[6].z>0){c=original.rgb+(a.rgb-original.rgb)*p.v[6].x/140;}out=vec4f(c,original.a);}
else if(op==9){var c=a.rgb*(1-p.v[20].y/100*.22)+vec3f(p.v[20].y/100*17.85);let cell=1+p.v[20].z/12;let xx=f32(i%w)/f32(w)*p.v[21].y/cell;let yy=f32(i/w)/f32(h)*p.v[21].z/cell;let mono=mix(smoothNoise(xx,yy,0u),noise(i32(floor(xx)),i32(floor(yy)),0u),p.v[20].w/100);let amount=p.v[20].x*.65;let color=p.v[21].x/100;c+=vec3f(mix(mono,smoothNoise(xx,yy,1u),color),mix(mono,smoothNoise(xx,yy,2u),color),mix(mono,smoothNoise(xx,yy,3u),color))*amount;out=vec4f(c,a.a);}
else if(op==10){let pos=vec2f(f32(i%w),f32(i/w));let size=vec2f(f32(w),f32(h));let center=p.v[24].yz/100*size;let radius=length((pos-center)/size);let protect=p.v[24].w/100*.6;let feather=max(.01,p.v[25].x/100*.6);let gate=smoothstep(0.0,1.0,clamp((radius-protect)/feather,0.0,1.0));let amount=gate*p.v[23].x/100;let mode=u32(p.v[23].y);let count=select(select(1u,2u,mode==2u),3u,mode==1u);var rgb=a.rgb;if(amount>0){for(var k=0u;k<3u;k++){var total=0.0;for(var j=0u;j<count;j++){let angle=p.v[23].w*.0174532925199433+select(f32(j)*3.14159265359,f32(j)*2.09439510239,mode==1u);let dir=vec2f(cos(angle),sin(angle));let offset=p.v[23].z/100*f32(min(w,h))*(1+(f32(k)-1)*p.v[24].x/250);var coord=pos+dir*offset;if(mode==2u){coord=pos-2*dot(pos-center,dir)*dir+dir*offset;}let value=samplePrism(coord,w,h);total+=value[k];}rgb[k]=mix(a[k],total/f32(count),amount);}}out=vec4f(rgb,a.a);}
else if(op==11){let paper=u32(p.v[26].w);var white=vec3f(1);var black=vec3f(0);if(paper==1u){white=vec3f(1,.965,.9);black=vec3f(.065,.052,.04);}else if(paper==2u){white=vec3f(.935,.97,1);black=vec3f(.035,.043,.065);}var c=(a.rgb/255*exp2(-p.v[26].xyz/100)*exp2(p.v[25].z)-vec3f(.5))*(1+p.v[25].w/100)+vec3f(.5);c=c*(1-p.v[27].x/100*.3)+vec3f(p.v[27].x/100*.065);c=c*(white-black)+black;out=vec4f(mix(a.rgb,c*255,p.v[25].y/100),a.a);}
dst[i]=out;}`;
async function init(){if(failed||!navigator.gpu)return false;if(pipe)return true;if(pending)return pending;pending=(async()=>{try{const adapter=await navigator.gpu.requestAdapter();if(!adapter)return false;device=await adapter.requestDevice();device.lost.then(()=>{pipe=null;failed=true;});device.addEventListener('uncapturederror',()=>failed=true);const module=device.createShaderModule({code:shader});const info=await module.getCompilationInfo();if(info.messages.some(m=>m.type==='error'))throw Error(info.messages.filter(m=>m.type==='error').map(m=>m.lineNum+': '+m.message).join('; '));pipe=await device.createComputePipelineAsync({layout:'auto',compute:{module,entryPoint:'main'}});return true;}catch(e){console.warn('Float GPU unavailable:',e.message);failed=true;return false;}})();return pending;}
function parameters(w,h,op,p={},mode=0){const a=new Float32Array(128);a.set([w,h,op,mode]);a.set([p.exposure||0,p.contrast||0,p.highlights||0,p.shadows||0],4);a.set([p.temperature||0,p.tint||0,p.saturation||0,p.vibrance||0],8);a.set([p.curveBlack||0,p.curveShadow||0,p.curveMid||0,p.curveHighlight||0],12);a.set([p.curveWhite||0,Number(['exposure','contrast','highlights','shadows','temperature','tint','saturation','vibrance'].some(k=>p[k])),Number(['curveBlack','curveShadow','curveMid','curveHighlight','curveWhite'].some(k=>p[k])),Number(FX.colorBands.some(([n])=>p['hsl'+n+'Hue']||p['hsl'+n+'Sat']||p['hsl'+n+'Lum']))],16);a.set([p.gradeBalance||0,p.gradeBlend??50],20);FX.colorBands.forEach(([name],i)=>a.set([p['hsl'+name+'Hue']||0,p['hsl'+name+'Sat']||0,p['hsl'+name+'Lum']||0,0],32+i*4));['Shadows','Midtones','Highlights','Global'].forEach((name,i)=>{const hex=p['grade'+name+'Color']||'#ffffff';a.set([...([1,3,5].map(j=>parseInt(hex.slice(j,j+2),16)/255)),p['grade'+name]||0],64+i*4);});a.set([p.grain||0,p.fade||0,p.grainSize??35,p.grainRoughness??50],80);a.set([p.grainColor||0,p.originalW||w,p.originalH||h,0],84);a.set([p.highlightCompression||0,p.compressionStart??65],88);a.set([p.prism||0,p.prismMode||0,p.prismDistance??22,p.prismAngle||0],92);a.set([p.prismDispersion??20,p.prismCenterX??50,p.prismCenterY??50,p.prismProtect??40],96);a.set([p.prismFeather??35,p.darkroom||0,p.printExposure||0,p.printContrast||0],100);a.set([p.printCyan||0,p.printMagenta||0,p.printYellow||0,p.printPaper||0],104);a.set([p.printFade||0],108);return a;}
async function create(data,w,h){if(!pipe){void init();return null;}if(failed||data.byteLength>Math.min(device.limits.maxStorageBufferBindingSize,64*1024*1024)||Math.ceil(w*h/64)>device.limits.maxComputeWorkgroupsPerDimension)return null;frame++;for(const [key,entry]of maskBuffers)if(entry.frame<frame-1){entry.buffer.destroy();maskBytes-=entry.bytes;maskBuffers.delete(key);}const resources=[];let allocated=0;const make=(bytes=data.byteLength,usage=GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC|GPUBufferUsage.COPY_DST)=>{allocated+=bytes;if(allocated>256*1024*1024)throw Error('GPU working-memory budget exceeded.');const index=pool.findIndex(e=>e.bytes===bytes&&e.usage===usage);let b;if(index>=0){const entry=pool.splice(index,1)[0];pooledBytes-=entry.bytes;b=entry.buffer;}else b=device.createBuffer({size:bytes,usage});resources.push({buffer:b,bytes,usage});return b;};const buffers=[make(),make()];let current=buffers[0],encoder=device.createCommandEncoder();if(cache.data!==data){cache.buffer?.destroy();cache.buffer=device.createBuffer({size:data.byteLength,usage:GPUBufferUsage.COPY_SRC|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(cache.buffer,0,data);cache.data=data;}encoder.copyBufferToBuffer(cache.buffer,0,current,0,data.byteLength);
function run(op,p={},extras=[],reference=current,aux=current,mode=0){const output=current===buffers[0]?buffers[1]:buffers[0],values=parameters(w,h,op,p,mode);values.set(extras,24);const uniform=make(values.byteLength,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);device.queue.writeBuffer(uniform,0,values);const pass=encoder.beginComputePass();pass.setPipeline(pipe);pass.setBindGroup(0,device.createBindGroup({layout:pipe.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:current}},{binding:1,resource:{buffer:output}},{binding:2,resource:{buffer:reference}},{binding:3,resource:{buffer:aux}},{binding:4,resource:{buffer:uniform}}]}));pass.dispatchWorkgroups(Math.ceil(w*h/64));pass.end();current=output;}
const save=()=>{const referenceImage=make();encoder.copyBufferToBuffer(current,0,referenceImage,0,data.byteLength);return referenceImage;};
async function read(){const staging=make(data.byteLength,GPUBufferUsage.MAP_READ|GPUBufferUsage.COPY_DST);encoder.copyBufferToBuffer(current,0,staging,0,data.byteLength);device.queue.submit([encoder.finish()]);await staging.mapAsync(GPUMapMode.READ);const result=new Float32Array(staging.getMappedRange().slice(0));staging.unmap();if(failed)throw Error('GPU processing failed.');encoder=device.createCommandEncoder();return result;}
return {backend:'webgpu-float32',save,prism:p=>run(10,p),printing:p=>run(11,p),blend:(referenceImage,amount)=>run(3,{},[amount],referenceImage),point:(p,mode)=>run(0,p,[],current,current,{all:0,light:1,color:2,grade:3}[mode]||0),blur:r=>{for(let i=0;i<3;i++){run(1,{},[Math.max(1,Math.round(r))]);run(2,{},[Math.max(1,Math.round(r))]);}},extract:(p,halo)=>{const hex=halo?p.halationTint:p.bloomTint;run(4,p,[halo?p.halationThreshold:p.bloomThreshold,p.bloomKnee,0,Number(halo),...[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255),0]);},screen:(referenceImage,amount,inner)=>run(5,{},[amount,Number(!!inner)],referenceImage,inner||referenceImage),diffuse:(referenceImage,p)=>run(6,p,[p.diffusion,p.diffusionMode,p.diffusionProtect],referenceImage),detail:(referenceImage,amount,weight,denoise)=>run(8,{},[amount,weight,Number(denoise)],referenceImage),film:(p,ow,oh)=>run(9,{...p,originalW:ow,originalH:oh}),mask:(coverage,p)=>{let entry=maskBuffers.get(coverage),referenceImage;if(entry){entry.frame=frame;referenceImage=entry.buffer;}else if(maskBytes+data.byteLength<=64*1024*1024){referenceImage=device.createBuffer({size:data.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(referenceImage,0,Float32Array.from(coverage));maskBuffers.set(coverage,{buffer:referenceImage,frame,bytes:data.byteLength});maskBytes+=data.byteLength;}else{referenceImage=make();device.queue.writeBuffer(referenceImage,0,Float32Array.from(coverage));}run(7,p,[],referenceImage);},async cpu(fn){const pixels=await read();fn(pixels);device.queue.writeBuffer(current,0,pixels);},read,destroy(){for(const entry of resources){if(!failed&&pooledBytes+entry.bytes<=96*1024*1024){pool.push(entry);pooledBytes+=entry.bytes;}else entry.buffer.destroy();}}};}
return {create};})();
