const FloatEngine=(()=>{
const coverageCache=new WeakMap();let prepared=null,sourceRef=null,preciseRef=null,preparedKey='';
function cpu(data,w,h){let pixels=data.slice();return {backend:'cpu-float32',transfer:linear=>RawColor.transfer(pixels,linear),prism:p=>Creative.prism(pixels,w,h,p),printing:p=>Creative.printing(pixels,p),save:()=>pixels.slice(),blend:(ref,mix)=>{for(let i=0;i<pixels.length;i++)pixels[i]=ref[i]+(pixels[i]-ref[i])*mix;},point:(p,mode)=>FloatKernels.point(pixels,p,mode),blur:r=>{pixels=FloatKernels.blur(pixels,w,h,r);},extract:(p,halo)=>{pixels=FloatKernels.extract(pixels,p,halo);},screen:(ref,amount,inner)=>{pixels=FloatKernels.screen(ref.slice(),pixels,amount,inner);},diffuse:(ref,p)=>{pixels=FloatKernels.diffuse(ref.slice(),pixels,p);},detail:(ref,amount,weight,denoise)=>{pixels=FloatKernels.detail(ref.slice(),pixels,amount,weight,denoise);},mask:(coverage,p)=>FloatKernels.mask(pixels,coverage,p),film:(p,ow,oh)=>FX.film(pixels,w,h,{...p,matte:0},ow,oh),cpu:fn=>fn(pixels),read:async()=>pixels,destroy(){}};}
function toCanvas(data,w,h){const canvas=new OffscreenCanvas(w,h);canvas.getContext('2d',{colorSpace:'srgb'}).putImageData(new ImageData(Uint8ClampedArray.from(data),w,h),0,0);return canvas;}
async function render(source,precise,input,max=0,original=false,backend='auto',region=null){const s=original?{...Imaging.defaults}:{...Imaging.defaults,...input};const key=JSON.stringify([max,region,...Imaging.compositionKeys.map(k=>s[k])]);if(sourceRef!==source||preciseRef!==precise||preparedKey!==key){prepared=PrecisionSource.prepare(source,precise,s,max,region);sourceRef=source;preciseRef=precise;preparedKey=key;}const {width:w,height:h,geometry:g}=prepared;let engine=backend==='cpu'?null:await FloatGPU.create(prepared.data,w,h);engine||=cpu(prepared.data,w,h);const selectedBackend=engine.backend,fw=g.width,fh=g.height;const blur=async r=>{const linear=precise?.colorSpace==='linear-rec2020';if(linear)engine.transfer(true);if(engine.backend==='webgpu-float32'&&r>24)await engine.cpu(d=>d.set(FloatKernels.blur(d,w,h,r)));else engine.blur(r);if(linear)engine.transfer(false);};
async function blend(amount,fn){amount=Math.max(0,Math.min(100,amount??100));if(!amount)return;const before=amount<100?engine.save():null;await fn();if(before)engine.blend(before,amount/100);}
async function optical(p,only){if((!only||only==='diffusion')&&p.diffusion){const before=engine.save();await blur(Math.max(fw,fh)*(.0004+p.diffusionRadius*.00006));engine.diffuse(before,p);if(p.diffusionScatter){const original=engine.save();engine.extract({...p,bloomThreshold:p.diffusionMode===1?55:30,bloomKnee:35,bloomTint:'#ffffff'},false);await blur(Math.max(fw,fh)*(.004+p.diffusionRadius*.00035));engine.screen(original,p.diffusion/100*p.diffusionScatter/100*.75);}}
if((!only||only==='halation')&&p.halation){const radius=Math.max(fw,fh)*(.001+p.halationRadius*.00035);for(const [mult,amount]of [[.22,p.halationTight],[1,p.halationMid],[3.1,p.halationWide]])if(amount){const original=engine.save();engine.extract(p,true);const inner=engine.save();await blur(Math.max(.7,radius*mult));engine.screen(original,Math.max(0,Math.min(1,p.halation/100*amount/100*.95)),inner);}}
if((!only||only==='glow')&&p.glow){const original=engine.save();engine.extract(p,false);await blur(Math.max(fw,fh)*(.001+p.glowRadius*.0004));engine.screen(original,p.glow/100*.9);}
if((!only||only==='flare')&&p.flare)await engine.cpu(data=>{const c=toCanvas(data,w,h),before=c.getContext('2d').getImageData(0,0,w,h).data;FX.Optics.flare(c,p);const after=c.getContext('2d').getImageData(0,0,w,h).data;for(let i=0;i<data.length;i+=4)for(let k=0;k<3;k++)data[i+k]+=after[i+k]-before[i+k];});}
async function operation(type,p){if((type==='develop'||Creative.Playful.types.includes(type))&&Creative.Playful.active(p))await engine.cpu(data=>Creative.Playful.apply(data,w,h,p,type==='develop'?null:type));if(['develop','light','color','grade'].includes(type))engine.point(p,type==='develop'?'all':type);if(type==='develop'||type==='detail'){if(p.denoise){const before=engine.save();await blur(Math.max(.5,Math.min(fw,fh)*.0015));engine.detail(before,p.denoise,1,true);}for(const [amount,radius,weight]of [[p.clarity,Math.min(fw,fh)*.014,1.3],[p.texture,Math.min(fw,fh)*.0023,1.2],[p.sharpen,Math.min(fw,fh)*.0008,1.8]])if(amount){const before=engine.save();await blur(Math.max(.5,radius));engine.detail(before,amount,weight,false);}}
if(type==='develop'||type==='masks')for(const mask of p.masks||[])if(mask.enabled!==false){const maskCanvas=Imaging.maskForImage(source,mask,s,max);let coverage=coverageCache.get(maskCanvas);if(!coverage){coverage=maskCanvas.getContext('2d').getImageData(0,0,w,h).data;coverageCache.set(maskCanvas,coverage);}engine.mask(coverage,{...Imaging.defaults,...mask.adjustments});}
if(type==='develop'||type==='bloom')await optical(p);else if(['diffusion','glow','halation','flare'].includes(type))await optical(p,type);
if(type==='develop'||type==='film'||['grain','fade','matte'].includes(type)){const q={...p};if(['grain','fade','matte'].includes(type))for(const k of ['grain','fade','matte'])if(k!==type)q[k]=0;if(q.matte)await engine.cpu(data=>FloatKernels.film(data,w,h,{...q,grain:0,fade:0},g.cw,g.ch));if(q.grain||q.fade)engine.film(q,g.cw,g.ch);}
if(type==='develop'||type==='prism')if(p.prism)engine.prism(p);
if(type==='develop'||type==='double')if(p.doubleAmount&&p.doubleSource)await engine.cpu(data=>Creative.double(data,w,h,p));
if(type==='develop'||type==='darkroom')if(p.darkroom)engine.printing(p);
if((type==='develop'||type==='vignette')&&p.vignette)await engine.cpu(data=>FX.vignette(data,w,h,p));}
async function node(n){if(n.enabled===false)return;await blend(n.mix,async()=>{if(n.legacyStage)await node(n.legacyStage);const p={...Imaging.defaults,...n.adjustments};for(const op of n.operations||[{type:n.operation||'develop',mix:100}])await blend(op.mix,()=>operation(op.type,p));for(const look of n.looks||[])if(look.enabled!==false)await blend(look.amount,async()=>{if(look.values?.recipeNodes){for(const part of look.values.recipeNodes)await node(part);}else await operation('develop',{...Imaging.defaults,...look.values});});});}
try{if(!original){await blend(s.developMix,()=>operation('develop',s));for(const n of s.nodes||[])await node(n);}let data=await engine.read(),width=w,height=h;
if(!original&&s.border){const b=FX.borderGeometry(w,h,s),scale=max?Math.min(1,max/Math.max(b.width,b.height)):1;const ow=Math.max(1,Math.round(b.width*scale)),oh=Math.max(1,Math.round(b.height*scale)),out=new Float32Array(ow*oh*4),color=[1,3,5].map(i=>parseInt(s.borderColor.slice(i,i+2),16));for(let y=0;y<oh;y++)for(let x=0;x<ow;x++){const sx=x/scale-b.inset,sy=y/scale-b.inset,i=(y*ow+x)*4;if(sx>=0&&sx<w&&sy>=0&&sy<h){const x0=Math.floor(sx),y0=Math.floor(sy),x1=Math.min(w-1,x0+1),y1=Math.min(h-1,y0+1),fx=sx-x0,fy=sy-y0;for(let k=0;k<4;k++)out[i+k]=(data[(y0*w+x0)*4+k]*(1-fx)+data[(y0*w+x1)*4+k]*fx)*(1-fy)+(data[(y1*w+x0)*4+k]*(1-fx)+data[(y1*w+x1)*4+k]*fx)*fy;}else out.set([...color,255],i);}data=out;width=ow;height=oh;}
if(!original&&((s.textLayers||[]).length||(s.nodes||[]).some(n=>n.enabled!==false&&n.adjustments?.textLayers?.length))){const layer=new OffscreenCanvas(width,height);TextFX.render(layer,s);const rgba=layer.getContext('2d').getImageData(0,0,width,height).data;for(let i=0;i<data.length;i+=4){const a=rgba[i+3]/255;for(let k=0;k<3;k++)data[i+k]=data[i+k]*(1-a)+rgba[i+k]*a;data[i+3]=data[i+3]+(255-data[i+3])*a;}}
return {data,width,height,canvas:toCanvas(data,width,height),backend:selectedBackend,precision:32,sourceBits:precise?16:8};}catch(e){if(selectedBackend==='webgpu-float32')return render(source,precise,s,max,original,'cpu',region);throw e;}finally{engine.destroy();}}
return {render,toCanvas};})();
