// Worker-owned GPU backend. Parameters and image preparation are independent of Electron.
// The first accelerated subset is tonal adjustment stacks; other edits use the CPU engine.
const GPUImageEngine=(()=>{
const tonal=['exposure','contrast','highlights','shadows','temperature','tint','saturation','vibrance'];
let device=null,initializing=null,failed=false,ready=false,pipeline,presentPipeline,context,canvas,inputTexture,outputTexture,uniform,params,sourceKey=null,sourceImage=null,width=0,height=0;
function plan(s,original){if(original||s.previewGate||s.border||s.borderBottom)return null;const stages=[];function add(p,mix=100){p={...Imaging.defaults,...p};if(Object.keys(Imaging.defaults).some(k=>!tonal.includes(k)&&!Imaging.compositionKeys.includes(k)&&!['nodes','_schema','developMix'].includes(k)&&JSON.stringify(p[k])!==JSON.stringify(Imaging.defaults[k])))return false;if(tonal.some(k=>p[k])&&mix>0)stages.push({...p,mix:Math.min(100,mix)});return true;}if(!add(s,s.developMix??100))return null;for(const n of s.nodes||[]){if(n.enabled===false||n.mix===0)continue;if(n.legacyStage)return null;const ops=n.operations||[{type:n.operation||'develop',mix:100}];if((n.mix??100)<100&&(ops[0]?.mix??100)<100)return null;if(ops.length!==1||!['develop','light'].includes(ops[0].type))return null;const looks=(n.looks||[]).filter(l=>l.enabled!==false);if(looks.length&&(n.mix??100)!==100)return null;if(!add(n.adjustments,(n.mix??100)*(ops[0].mix??100)/100))return null;for(const l of looks){if(l.values?.recipeNodes||!add(l.values,l.amount??100))return null;}}return stages.length&&stages.length<=32?stages:null;}
async function init(){if(failed||!navigator.gpu)return false;if(ready)return true;if(initializing)return initializing;initializing=(async()=>{try{const adapter=await navigator.gpu.requestAdapter({powerPreference:'high-performance'});if(!adapter)return false;device=await adapter.requestDevice();device.lost.then(()=>{failed=true;device=null;});device.addEventListener('uncapturederror',()=>{failed=true;});const compute=device.createShaderModule({code:`
struct Stage { a:vec4f, b:vec4f, c:vec4f }; struct Params { width:u32, height:u32, count:u32, pad:u32 };
@group(0) @binding(0) var src:texture_2d<f32>;
@group(0) @binding(1) var dst:texture_storage_2d<rgba16float,write>;
@group(0) @binding(2) var<uniform> stages:array<Stage,32>;
@group(0) @binding(3) var<uniform> params:Params;
fn quantize(v:vec3f)->vec3f { return round(clamp(v,vec3f(0),vec3f(1))*255.0)/255.0; }
@compute @workgroup_size(8,8) fn main(@builtin(global_invocation_id) id:vec3u){
 if(id.x>=params.width||id.y>=params.height){return;}let coord=vec2i(id.xy);var color=textureLoad(src,coord,0);
 for(var i=0u;i<params.count;i++){let s=stages[i];let before=color.rgb;let lum=dot(before,vec3f(.2126,.7152,.0722));let low=1.0-lum;let tone=s.a.w*.0042*low*low+s.a.z*.0042*lum*lum;
 var rgb=(before*exp2(s.a.x)+tone-vec3f(.5))*(1.0+s.a.y/100.0)+vec3f(.5)+vec3f(s.b.x*.0011+s.b.y*.00035,-s.b.y*.00065,-s.b.x*.0011+s.b.y*.00035);
 let gray=dot(rgb,vec3f(.2126,.7152,.0722));let spread=max(rgb.r,max(rgb.g,rgb.b))-min(rgb.r,min(rgb.g,rgb.b));let sat=1.0+s.b.z/100.0+s.b.w/100.0*(1.0-min(1.0,spread));rgb=quantize(vec3f(gray)+(rgb-vec3f(gray))*sat);color=vec4f(quantize(mix(before,rgb,s.c.x/100.0)),color.a);
 }textureStore(dst,coord,color);
}`});pipeline=await device.createComputePipelineAsync({layout:'auto',compute:{module:compute,entryPoint:'main'}});const display=device.createShaderModule({code:`
@group(0) @binding(0) var image:texture_2d<f32>;
@vertex fn vs(@builtin(vertex_index) i:u32)->@builtin(position) vec4f {var p=array<vec2f,3>(vec2f(-1,-1),vec2f(3,-1),vec2f(-1,3));return vec4f(p[i],0,1);}
@fragment fn fs(@builtin(position) p:vec4f)->@location(0) vec4f{return textureLoad(image,vec2i(p.xy),0);}`});presentPipeline=await device.createRenderPipelineAsync({layout:'auto',vertex:{module:display,entryPoint:'vs'},fragment:{module:display,entryPoint:'fs',targets:[{format:'rgba8unorm'}]},primitive:{topology:'triangle-list'}});uniform=device.createBuffer({size:32*48,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});params=device.createBuffer({size:16,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});canvas=new OffscreenCanvas(1,1);context=canvas.getContext('webgpu');ready=!!context;return ready;}catch{failed=true;return false;}})();const ok=await initializing;initializing=null;if(!ok)failed=true;return ok;}
async function render(source,s,max,original){const stages=plan(s,original);if(!stages||failed)return null;if(!ready){void init();return null;}const base=Imaging.prepareBase(source,s,max),w=base.g.width,h=base.g.height;if(w*h>8*1024*1024||w>device.limits.maxTextureDimension2D||h>device.limits.maxTextureDimension2D)return null;const key=JSON.stringify([w,h,max,...Imaging.compositionKeys.map(k=>s[k])]);if(source!==sourceImage||key!==sourceKey){for(let i=3;i<base.data.data.length;i+=4)if(base.data.data[i]!==255)return null;if(w!==width||h!==height){inputTexture?.destroy();outputTexture?.destroy();width=w;height=h;inputTexture=device.createTexture({size:[w,h],format:'rgba8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST});outputTexture=device.createTexture({size:[w,h],format:'rgba16float',usage:GPUTextureUsage.STORAGE_BINDING|GPUTextureUsage.TEXTURE_BINDING});canvas.width=w;canvas.height=h;context.configure({device,format:'rgba8unorm',alphaMode:'opaque'});}device.queue.writeTexture({texture:inputTexture},base.data.data,{bytesPerRow:w*4},[w,h]);sourceImage=source;sourceKey=key;}
const data=new Float32Array(32*12);stages.forEach((s,i)=>data.set([s.exposure,s.contrast,s.highlights,s.shadows,s.temperature,s.tint,s.saturation,s.vibrance,s.mix,0,0,0],i*12));device.queue.writeBuffer(uniform,0,data);device.queue.writeBuffer(params,0,new Uint32Array([w,h,stages.length,0]));const encoder=device.createCommandEncoder(),pass=encoder.beginComputePass();pass.setPipeline(pipeline);pass.setBindGroup(0,device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:inputTexture.createView()},{binding:1,resource:outputTexture.createView()},{binding:2,resource:{buffer:uniform}},{binding:3,resource:{buffer:params}}]}));pass.dispatchWorkgroups(Math.ceil(w/8),Math.ceil(h/8));pass.end();const draw=encoder.beginRenderPass({colorAttachments:[{view:context.getCurrentTexture().createView(),loadOp:'clear',clearValue:[0,0,0,1],storeOp:'store'}]});draw.setPipeline(presentPipeline);draw.setBindGroup(0,device.createBindGroup({layout:presentPipeline.getBindGroupLayout(0),entries:[{binding:0,resource:outputTexture.createView()}]}));draw.draw(3);draw.end();device.queue.submit([encoder.finish()]);await device.queue.onSubmittedWorkDone();if(failed)return null;return canvas;}
return {render,plan,warmup:init,disable(){failed=true;}};
})();
