(()=>{
const section=$('gradeShadows').closest('details'),grid=document.createElement('div');grid.className='grading-wheels';section.querySelector('summary').after(grid);const hint=document.createElement('p');hint.className='small muted';hint.textContent='Drag around for hue, outward for richer color. Center is neutral. Strength controls how much is applied.';grid.before(hint);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function hsv(h,s,v=1){const c=v*s,x=c*(1-Math.abs(h/60%2-1)),m=v-c,a=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];return a.map(n=>Math.round((n+m)*255));}
function decode(hex){const [r,g,b]=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255),max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=d?(max===r?(g-b)/d:max===g?(b-r)/d+2:(r-g)/d+4)*60:0;return {h:(h+360)%360,s:max?d/max:0};}
const toHex=(h,s)=>'#'+hsv(h,s).map(v=>v.toString(16).padStart(2,'0')).join('');
const size=192,center=96,radius=87,base=document.createElement('canvas');base.width=base.height=size;const bx=base.getContext('2d'),pixels=bx.createImageData(size,size);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const dx=x-center,dy=y-center,r=Math.hypot(dx,dy);if(r>radius)continue;const h=(Math.atan2(dy,dx)*180/Math.PI+450)%360,rgb=hsv(h,r/radius),i=(y*size+x)*4;pixels.data.set([...rgb,Math.min(255,(radius-r)*255)],i);}bx.putImageData(pixels,0,0);
const cards=[];
for(const [name,label,icon]of [['Shadows','Shadows','◕'],['Midtones','Midtones','◐'],['Highlights','Highlights','◔'],['Global','Overall','◉']]){
 const key='grade'+name,colorKey=key+'Color',picker=$(colorKey),oldRow=picker.closest('.color-row');oldRow.hidden=true;
 const card=document.createElement('div');card.className='grading-card';const heading=document.createElement('div');heading.className='grading-title';const title=document.createElement('strong');title.textContent=icon+' '+label;const reset=document.createElement('button');reset.textContent='↺';reset.title='Reset '+label.toLowerCase();reset.setAttribute('aria-label','Reset '+label+' grading');heading.append(title,reset);const canvas=document.createElement('canvas');canvas.id='wheel'+name;canvas.width=canvas.height=size;canvas.tabIndex=0;canvas.setAttribute('role','slider');canvas.setAttribute('aria-label',label+' color wheel');canvas.setAttribute('aria-valuemin','0');canvas.setAttribute('aria-valuemax','360');canvas.title='Drag to tint · Left/Right: hue · Up/Down: saturation · Double-click: reset';const readout=document.createElement('div');readout.className='wheel-readout';const color=document.createElement('span'),value=document.createElement('span');readout.append(color,value);card.append(heading,canvas,readout);const strength=$(key).closest('.slider-row');strength.querySelector('.slider-label').firstChild.textContent='Strength';card.append(strength);grid.append(card);
 let dragging=false,last='';
 function draw(){const hex=settings[colorKey],state=decode(hex),sig=hex+'|'+!!img;if(sig===last)return;last=sig;const cx=canvas.getContext('2d');cx.clearRect(0,0,size,size);cx.drawImage(base,0,0);const angle=(state.h-90)*Math.PI/180,x=center+Math.cos(angle)*state.s*radius,y=center+Math.sin(angle)*state.s*radius;cx.beginPath();cx.arc(x,y,7,0,Math.PI*2);cx.strokeStyle='#151515';cx.lineWidth=4;cx.stroke();cx.strokeStyle='#ffffff';cx.lineWidth=2;cx.stroke();color.style.backgroundColor=hex;value.textContent=Math.round(state.h)+'° · '+Math.round(state.s*100)+'%';canvas.setAttribute('aria-valuenow',String(Math.round(state.h)));canvas.setAttribute('aria-valuetext',Math.round(state.h)+' degrees hue, '+Math.round(state.s*100)+' percent saturation');canvas.setAttribute('aria-disabled',String(!img));canvas.tabIndex=img?0:-1;reset.disabled=!img;card.classList.toggle('wheel-disabled',!img);}
 function apply(h,s){settings[colorKey]=toHex(h,s);if(settings[key]===0&&s>.02)settings[key]=25;picker.value=settings[colorKey];$(key).value=settings[key];syncValues();draw();scheduleRender();}
 function at(e){const box=canvas.getBoundingClientRect(),dx=(e.clientX-box.left)/box.width*size-center,dy=(e.clientY-box.top)/box.height*size-center;apply((Math.atan2(dy,dx)*180/Math.PI+450)%360,clamp(Math.hypot(dx,dy)/radius,0,1));}
 canvas.onpointerdown=e=>{if(!img||e.button!==0)return;e.preventDefault();canvas.focus();pushHistory();dragging=true;canvas.setPointerCapture(e.pointerId);at(e);};canvas.onpointermove=e=>{if(dragging)at(e);};canvas.onpointerup=canvas.onpointercancel=()=>{if(!dragging)return;dragging=false;save();render();};
 reset.onclick=canvas.ondblclick=()=>{if(img)mutate(()=>{settings[colorKey]=Imaging.defaults[colorKey];settings[key]=0;});};canvas.onkeydown=e=>{if(!img||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(e.key))return;e.preventDefault();e.stopPropagation();pushHistory();const state=decode(settings[colorKey]),step=e.shiftKey?10:2;if(e.key==='Home')apply(state.h,0);else apply((state.h+(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0)+360)%360,clamp(state.s+(e.key==='ArrowUp'?step/100:e.key==='ArrowDown'?-step/100:0),0,1));save();render();};cards.push({draw});
}
window.gradingWheels={sync:()=>cards.forEach(c=>c.draw())};window.gradingWheels.sync();
})();
