const fs=require('node:fs/promises'),path=require('node:path'),Imaging=require('./processing.js');
const creativeRanges={highlightCompression:[0,100],compressionStart:[10,95],prism:[0,100],prismMode:[0,2],prismDistance:[0,100],prismAngle:[-180,180],prismDispersion:[0,100],prismCenterX:[0,100],prismCenterY:[0,100],prismProtect:[0,100],prismFeather:[0,100],darkroom:[0,100],printCyan:[-100,100],printMagenta:[-100,100],printYellow:[-100,100],printExposure:[-2,2],printContrast:[-60,60],printPaper:[0,2],printFade:[0,100],doubleAmount:[0,100],doubleMode:[0,3],doubleScale:[10,300],doubleX:[-100,100],doubleY:[-100,100],doubleRotation:[-180,180],doubleTarget:[0,2],doubleSoftness:[0,100]};
const LIMIT=2_000_000,types=new Set(['prism','double','darkroom','develop','light','color','grade','detail','masks','bloom','film','vignette','diffusion','glow','flare','halation','grain','fade','matte']);
function normalize(input){
 if(!input||typeof input!=='object'||JSON.stringify(input).length>LIMIT)throw Error('This look is invalid or too large (maximum 2 MB).');
 const text=(v,max)=>typeof v==='string'?v.trim().slice(0,max):'';
 const name=text(input.name,60);if(!name)throw Error('Give the look a name.');
 let count=0;const number=(v,fallback,min=-1000,max=1000)=>{if(v===undefined)return fallback;if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw Error('This look contains an unsupported setting.');return v;};
 function adjustments(value={}){const out={};for(const [k,def]of Object.entries(Imaging.defaults)){if(k==='doubleSource'||k==='doubleName'||Imaging.compositionKeys.includes(k)||k.startsWith('_')||Array.isArray(def))continue;const v=value?.[k];if(v===undefined)continue;if(typeof def==='number')out[k]=number(v,def,creativeRanges[k]?.[0]??(k==='exposure'?-10:-1000),creativeRanges[k]?.[1]??(k==='exposure'?10:1000));else if(typeof def==='string'){if(typeof v!=='string'||!/^#[0-9a-f]{6}$/i.test(v))throw Error('Invalid look color.');out[k]=v;}else if(typeof def==='boolean')out[k]=v===true;}return out;}
 function recipe(list,depth=0){if(depth>6||!Array.isArray(list)||list.length>24||!list.length)throw Error('This look has too many nested effects or no nodes.');return list.map(n=>{if(++count>128||!n||typeof n!=='object')throw Error('This look has too many effects.');const operation=n.operation||'develop';if(!types.has(operation))throw Error('Unsupported effect type.');const out={label:text(n.label,60)||'Shared look',operation,enabled:n.enabled!==false,mix:number(n.mix,100,0,100),adjustments:adjustments(n.adjustments),frame:{},looks:[]};if(n.operations){if(!Array.isArray(n.operations)||n.operations.length>24)throw Error('Too many operations.');out.operations=n.operations.map(o=>{if(!types.has(o.type))throw Error('Unsupported effect type.');return {type:o.type,mix:number(o.mix,100,0,100)};});}if(n.legacyStage)out.legacyStage=recipe([n.legacyStage],depth+1)[0];if(n.looks){if(!Array.isArray(n.looks)||n.looks.length>100)throw Error('Too many layered looks.');out.looks=n.looks.map((l,i)=>({id:i+1,name:text(l.name,60),enabled:l.enabled!==false,amount:number(l.amount,100,0,100),values:l.values?.recipeNodes?{recipeNodes:recipe(l.values.recipeNodes,depth+1)}:adjustments(l.values)}));}return out;});}
 return {name,description:text(input.description,2000),author:text(input.author,80),recipe:recipe(input.recipe)};
}
function decode(raw){if(Buffer.byteLength(raw)>LIMIT)throw Error('Look files must be smaller than 2 MB.');let data;try{data=JSON.parse(raw);}catch{throw Error('This is not a valid Lith look file.');}if(data.format!=='lith-look'||data.version!==1)throw Error('Unsupported look format or version. Update Lith and try again.');return normalize(data);}
function encode(look){return JSON.stringify({format:'lith-look',version:1,...normalize(look)},null,2);}
function setup({ipcMain,dialog,getWindow,root}){
 ipcMain.handle('look-file-import',async()=>{const picked=await dialog.showOpenDialog(getWindow(),{title:'Import a community look',properties:['openFile'],filters:[{name:'Lith look',extensions:['lithlook']}]});if(picked.canceled)return null;const file=await fs.open(picked.filePaths[0],'r');try{if((await file.stat()).size>LIMIT)throw Error('Look files must be smaller than 2 MB.');return decode(await file.readFile('utf8'));}finally{await file.close();}});
 ipcMain.handle('look-file-export',async(_,look)=>{const clean=normalize(look),body=encode(clean);const picked=await dialog.showSaveDialog(getWindow(),{title:'Share look',defaultPath:clean.name.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_')+'.lithlook',filters:[{name:'Lith look',extensions:['lithlook']}]});if(picked.canceled)return false;const target=picked.filePath.toLowerCase().endsWith('.lithlook')?picked.filePath:picked.filePath+'.lithlook';const parent=await fs.realpath(path.dirname(target)),relative=path.relative(await fs.realpath(root),parent);if(!relative||(!relative.startsWith('..'+path.sep)&&relative!=='..'&&!path.isAbsolute(relative)))throw Error('Choose a folder outside the photo library.');await fs.writeFile(target,body,'utf8');return true;});
}
module.exports={normalize,decode,encode,setup};
