(()=>{
const builtinCount=looks.length;let installed=0,photo=null,worker=null,thumbnailIndex=0,thumbnailGeneration=0,thumbnailTimer=null,navigating=false;
const node=()=>documentSettings.nodes.find(n=>n.uid===activeNodeUid);
const heading=[...document.querySelectorAll('.left .section-title')].find(e=>e.textContent.includes('LOOKS'));const add=document.createElement('button');add.id='saveCustomLook';add.textContent='＋ Save';add.title='Save your edits as a custom look';heading.append(add);
const browse=document.createElement('button');browse.id='browseLooks';browse.textContent='↕ Browse looks';browse.title='Focus a look, then use arrow keys to audition one at a time';$('lookSearch').before(browse);browse.onclick=()=>{const list=visibleLooks();(list.find(b=>b.classList.contains('active'))||list[0])?.focus();};
const hint=document.querySelector('.look-instruction');hint.textContent='Click to layer · Arrows to audition one look · Right-click for strength';
$('presetFamily').append(new Option('My looks','custom'));
const dialog=document.createElement('dialog');dialog.id='customLookDialog';dialog.innerHTML='<form id="customLookForm"><div class="dialog-top"><strong>Save custom look</strong><button type="button" id="cancelCustomLook" aria-label="Close custom look">✕</button></div><label>Name<input id="customLookName" maxlength="60" required placeholder="My golden hour"></label><p class="small muted">Saves color, effects and layered looks from all enabled nodes. Text, masks, crop and borders stay with the photo.</p><button id="confirmCustomLook" class="primary">Save look</button></form>';document.body.append(dialog);
add.onclick=()=>{if(!img)return;$('customLookName').value='';dialog.showModal();$('customLookName').focus();};$('cancelCustomLook').onclick=()=>dialog.close();
function cleanRecipe(n){const copy=structuredClone(n);copy.frame={};if(copy.adjustments){copy.adjustments.masks=[];copy.adjustments.textLayers=[];copy.adjustments.nodes=[];for(const k of Imaging.compositionKeys)copy.adjustments[k]=Imaging.defaults[k];}if(copy.legacyStage)copy.legacyStage=cleanRecipe(copy.legacyStage);for(const l of copy.looks||[])if(l.values?.recipeNodes)l.values.recipeNodes=l.values.recipeNodes.map(cleanRecipe);return copy;}
$('customLookForm').onsubmit=async e=>{e.preventDefault();const name=$('customLookName').value.trim();if(!name||!img)return;const button=$('confirmCustomLook');button.disabled=true;try{catalog.customLooks=await api.saveLook({name,recipe:documentSettings.nodes.filter(n=>n.enabled!==false).map(cleanRecipe)});installLooks();dialog.close();$('presetFamily').value='custom';filterLooks();toast('Saved “'+name+'” to My looks.');}catch(e){fail(e);}finally{button.disabled=false;}};
function installLooks(){for(const saved of (catalog.customLooks||[]).slice(installed)){const id=looks.length;looks.push([saved.name,'My look',{recipeNodes:saved.recipe}]);const b=document.createElement('button');b.className='preset';const swatch=document.createElement('span');swatch.className='swatch';const label=document.createElement('span');label.textContent=saved.name;const sub=document.createElement('small');sub.textContent='My look';label.append(sub);b.append(swatch,label);$('presets').append(b);window.nodeFlowUI.bindLook(b,id);installed++;}heading.querySelector('span').textContent=looks.length+' LOOKS';}
function filterLooks(){const family=$('presetFamily').value,q=$('lookSearch').value.toLowerCase();document.querySelectorAll('.preset').forEach(b=>{const id=Number(b.dataset.lookId),text=looks[id][0].toLowerCase();const match=family==='all'||family==='custom'&&id>=builtinCount||family==='stock'&&text.includes('inspired')||family==='dream'&&text.startsWith('dream')||family==='35mm'&&text.startsWith('35mm')||family==='vintage'&&text.startsWith('vintage');b.hidden=!match||!text.includes(q);});}
$('presetFamily').onchange=$('lookSearch').oninput=filterLooks;
function visibleLooks(){return [...document.querySelectorAll('.preset')].filter(b=>!b.hidden&&!b.disabled);}
function audition(button){const id=Number(button.dataset.lookId);if(!img||!node())return;mutate(()=>{const n=node();n.looks||=[];for(const l of n.looks)l.enabled=false;if(id){let look=n.looks.find(l=>l.id===id);if(!look){look={id,name:looks[id][0],values:structuredClone(looks[id][2]),amount:100};n.looks.push(look);}look.enabled=true;}});button.focus({preventScroll:true});button.scrollIntoView({block:'nearest'});}
$('presets').addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const b=e.target.closest('.preset'),list=visibleLooks();if(!b||!list.length)return;e.preventDefault();e.stopPropagation();const at=list.indexOf(b),next=e.key==='Home'?0:e.key==='End'?list.length-1:Math.max(0,Math.min(list.length-1,at+(['ArrowUp','ArrowLeft'].includes(e.key)?-1:1)));audition(list[next]);});
// Thumbnail rendering has its own low-resolution worker, separate from the main preview.
async function beginThumbnails(){const image=img,generation=++thumbnailGeneration;photo=image;worker?.terminate();clearTimeout(thumbnailTimer);worker=null;thumbnailIndex=0;document.querySelectorAll('.look-thumb').forEach(c=>c.remove());if(!image)return;const scale=Math.min(1,512/Math.max(image.naturalWidth,image.naturalHeight));const bitmap=await createImageBitmap(image,{resizeWidth:Math.max(1,Math.round(image.naturalWidth*scale)),resizeHeight:Math.max(1,Math.round(image.naturalHeight*scale)),resizeQuality:'high'});if(generation!==thumbnailGeneration){bitmap.close();return;}const local=new Worker('render-worker.js');worker=local;local.postMessage({type:'source',bitmap},[bitmap]);local.onmessage=({data})=>{if(generation!==thumbnailGeneration){data.bitmap?.close();return;}const b=document.querySelector('.preset[data-look-id="'+data.id+'"]');if(data.bitmap&&b){const canvas=document.createElement('canvas');canvas.className='look-thumb';canvas.width=data.bitmap.width;canvas.height=data.bitmap.height;canvas.getContext('2d').drawImage(data.bitmap,0,0);data.bitmap.close();const swatch=b.querySelector('.swatch');swatch.style.filter='none';swatch.classList.add('photo-swatch');swatch.replaceChildren(canvas);b.dataset.previewPhoto=current?.id||'';}if(data.error)console.warn('Look preview:',data.error);thumbnailTimer=setTimeout(nextThumbnail,25);};local.onerror=e=>console.warn('Look previews unavailable:',e.message);nextThumbnail();}
function nextThumbnail(){if(!worker||thumbnailIndex>=looks.length)return;const id=thumbnailIndex++,s=structuredClone(Imaging.defaults);s.nodes=id?[{enabled:true,operation:'develop',adjustments:structuredClone(Imaging.defaults),looks:[{id,values:looks[id][2],amount:100,enabled:true}]}]:[];worker.postMessage({type:'preview',id,settings:s,max:120,original:false});}
const rating=document.createElement('div');rating.id='photoRating';rating.setAttribute('aria-label','Photo rating');$('favorite').before(rating);for(let i=1;i<=5;i++){const b=document.createElement('button');b.textContent='☆';b.title='Rate '+i+' star'+(i>1?'s':'')+' ('+i+')';b.setAttribute('aria-label','Rate '+i+' stars');b.onclick=()=>rate(current?.rating===i?0:i);rating.append(b);}function rate(value){if(!current)return;current.rating=value;save();refresh();}
async function navigatePhoto(step){if(navigating||!current)return;const photos=visible(),at=photos.findIndex(p=>p.id===current.id),p=photos[at+step];if(!p)return;navigating=true;try{setMode('edit');await select(p.id);}catch(e){fail(e);}finally{navigating=false;}}
const help=document.createElement('dialog');help.id='shortcutHelp';help.innerHTML='<form method="dialog"><div class="dialog-top"><strong>Keyboard shortcuts</strong><button aria-label="Close shortcuts">✕</button></div><dl><dt>↑ ↓ / ← → in Looks</dt><dd>Audition one look at a time</dd><dt>← / → elsewhere</dt><dd>Previous / next photo</dd><dt>0–5</dt><dd>Clear / set star rating</dd><dt>P / U</dt><dd>Favorite / unmark favorite</dd><dt>M</dt><dd>Open Masks</dd><dt>O</dt><dd>Toggle mask overlay</dd><dt>F or F11 / Esc</dt><dd>Toggle / exit fullscreen</dd><dt>Tab</dt><dd>Toggle Focus view (from photo area)</dd><dt>Ctrl+Z / Ctrl+Shift+Z</dt><dd>Undo / redo</dd><dt>Ctrl+O / Ctrl+Shift+E</dt><dd>Import / export</dd><dt>Y / \\</dt><dd>Side comparison / original</dd><dt>?</dt><dd>Show this list</dd></dl></form>';document.body.append(help);const helpButton=document.createElement('button');helpButton.id='keyboardHelp';helpButton.textContent='⌨';helpButton.title='Keyboard shortcuts (?)';document.querySelector('.canvas-tools').firstElementChild.append(helpButton);helpButton.onclick=()=>help.showModal();
document.addEventListener('keydown',e=>{if(e.defaultPrevented||e.target.closest('input,select,textarea,[contenteditable="true"]')||document.querySelector('dialog[open]'))return;if(e.key==='?'&&!e.ctrlKey&&!e.metaKey){e.preventDefault();help.showModal();return;}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='e'){e.preventDefault();$('export').click();return;}if(e.ctrlKey||e.metaKey||e.altKey)return;const key=e.key.toLowerCase();if(['f','f11'].includes(key)){e.preventDefault();api.fullscreen().catch(fail);}else if(key==='escape'){api.fullscreen(false).catch(fail);}else if(/^[0-5]$/.test(key)){e.preventDefault();rate(Number(key));}else if(key==='p'||key==='u'){if(current){current.favorite=key==='p';save();refresh();}}else if(key==='m'){e.preventDefault();window.advancedUI.setTool('mask');}else if(key==='o'){e.preventDefault();$('maskOverlay').checked=!$('maskOverlay').checked;window.maskUI.overlay();}else if(['ArrowLeft','ArrowRight'].includes(e.key)&&!e.target.closest('#nodeTargets,#nodeGraph,.color-chips,#wipeDivider')){e.preventDefault();navigatePhoto(e.key==='ArrowLeft'?-1:1);}else if(e.key==='Tab'&&(e.target===document.body||e.target.closest('#stage'))){e.preventDefault();$('focusView').click();}});
function syncBrowser(){const before=looks.length;installLooks();add.disabled=!img;browse.disabled=!img;for(const [i,b]of [...rating.children].entries()){b.disabled=!current;b.textContent=(current?.rating||0)>i?'★':'☆';b.setAttribute('aria-pressed',String((current?.rating||0)>i));}document.querySelectorAll('.preset').forEach(b=>b.disabled=!img);if(photo!==img)beginThumbnails().catch(fail);else if(before!==looks.length){nextThumbnail();filterLooks();}}
window.lookBrowserUI={sync:syncBrowser};syncBrowser();
})();
