(()=>{
const communityIds=new Set();
for(const saved of window.LithCommunityLooks||[]){const id=looks.length;communityIds.add(id);looks.push([saved.name,saved.description,{recipeNodes:structuredClone(saved.recipe)},{category:'user-made',author:saved.author,collection:saved.collection}]);const b=document.createElement('button');b.className='preset';b.dataset.category='user-made';const swatch=document.createElement('span');swatch.className='swatch';const label=document.createElement('span');label.textContent=saved.name;const sub=document.createElement('small');sub.className='user-made-badge';sub.textContent='User-made · '+saved.author;label.append(sub);b.append(swatch,label);$('presets').append(b);window.nodeFlowUI.bindLook(b,id);b.title=saved.name+' · User-made by '+saved.author+'\n'+saved.description+'\n'+b.title;}
const builtinCount=looks.length;let installed=0,photo=null,worker=null,thumbnailIndex=0,thumbnailGeneration=0,thumbnailTimer=null,navigating=false,thumbnailBusy=false;const completedThumbnails=new Set();
const node=()=>documentSettings.nodes.find(n=>n.uid===activeNodeUid);
const heading=[...document.querySelectorAll('.left .section-title')].find(e=>e.textContent.includes('LOOKS'));const add=document.createElement('button');add.id='saveCustomLook';add.textContent='＋ Save';add.title='Save your edits as a custom look';heading.append(add);
const browse=document.createElement('button');browse.id='browseLooks';browse.textContent='↕ Browse looks';browse.title='Focus a look, then use arrow keys to audition one at a time';$('lookSearch').before(browse);browse.onclick=()=>{const list=visibleLooks();(list.find(b=>b.classList.contains('active'))||list[0])?.focus();};
const hint=document.querySelector('.look-instruction');hint.textContent='Click to layer · Adjust strength in Selected looks · Arrows to audition';
$('presetFamily').append(new Option('User-made · All collections','user-made'),new Option('User-made · Dream Bloom','collection:Dream Bloom'),new Option('User-made · Light Studies','collection:Light Studies'),new Option('My looks','custom'));
const dialog=document.createElement('dialog');dialog.id='customLookDialog';dialog.innerHTML='<form id="customLookForm"><div class="dialog-top"><strong>Save custom look</strong><button type="button" id="cancelCustomLook" aria-label="Close custom look">✕</button></div><label>Name<input id="customLookName" maxlength="60" required placeholder="My golden hour"></label><label>Description<textarea id="customLookDescription" maxlength="2000" placeholder="The mood, best lighting, and tips for using this look"></textarea></label><label>Creator (optional)<input id="customLookAuthor" maxlength="80" placeholder="Your name or handle"></label><p class="small muted">Saves color, effects and layered looks from all enabled nodes. Text, masks, crop, borders and second-exposure photos stay with the photo.</p><button id="confirmCustomLook" class="primary">Save look</button></form>';document.body.append(dialog);
add.onclick=()=>{if(!img)return;$('customLookName').value='';$('customLookDescription').value='';$('customLookAuthor').value='';dialog.showModal();$('customLookName').focus();};$('cancelCustomLook').onclick=()=>dialog.close();
function cleanRecipe(n){const copy=structuredClone(n);copy.frame={};if(copy.adjustments){copy.adjustments.doubleSource='';copy.adjustments.doubleName='';copy.adjustments.masks=[];copy.adjustments.textLayers=[];copy.adjustments.nodes=[];for(const k of Imaging.compositionKeys)copy.adjustments[k]=Imaging.defaults[k];}if(copy.legacyStage)copy.legacyStage=cleanRecipe(copy.legacyStage);for(const l of copy.looks||[])if(l.values?.recipeNodes)l.values.recipeNodes=l.values.recipeNodes.map(cleanRecipe);return copy;}
$('customLookForm').onsubmit=async e=>{e.preventDefault();const name=$('customLookName').value.trim();if(!name||!img)return;const button=$('confirmCustomLook');button.disabled=true;try{catalog.customLooks=await api.saveLook({name,description:$('customLookDescription').value,author:$('customLookAuthor').value,recipe:documentSettings.nodes.filter(n=>n.enabled!==false).map(cleanRecipe)});installLooks();dialog.close();$('presetFamily').value='custom';filterLooks();toast('Saved “'+name+'” to My looks.');}catch(e){fail(e);}finally{button.disabled=false;}};
function installLooks(){for(const saved of (catalog.customLooks||[]).slice(installed)){const id=looks.length;looks.push([saved.name,saved.description||'My look',{recipeNodes:saved.recipe},{category:'custom',id:saved.id}]);const b=document.createElement('button');b.className='preset';const swatch=document.createElement('span');swatch.className='swatch';const label=document.createElement('span');label.textContent=saved.name;const sub=document.createElement('small');sub.textContent=saved.author?'By '+saved.author:'My look';b.title=[saved.name,saved.description,saved.author?'By '+saved.author:''].filter(Boolean).join('\n');label.append(sub);b.append(swatch,label);$('presets').append(b);window.nodeFlowUI.bindLook(b,id);b.title=[saved.name,saved.description,saved.author?'By '+saved.author:'',b.title].filter(Boolean).join('\n');installed++;}heading.querySelector('span').textContent=looks.length+' LOOKS';}
function filterLooks(){const family=$('presetFamily').value,q=$('lookSearch').value.toLowerCase();document.querySelectorAll('.preset').forEach(b=>{const id=Number(b.dataset.lookId),text=looks[id][0].toLowerCase(),searchable=[looks[id][0],looks[id][1],communityIds.has(id)?'user-made '+looks[id][3].collection+' '+looks[id][3].author:''].join(' ').toLowerCase();const match=family==='all'||family==='custom'&&id>=builtinCount||family==='user-made'&&communityIds.has(id)||family.startsWith('collection:')&&looks[id][3]?.collection===family.slice(11)||family==='stock'&&text.includes('inspired')||family==='dream'&&text.startsWith('dream')||family==='35mm'&&text.startsWith('35mm')||family==='vintage'&&text.startsWith('vintage');b.hidden=!match||!searchable.includes(q)||!!window.lookFavorites?.only()&&!window.lookFavorites.isFavorite(id);});window.lookFavorites?.sync();requestAnimationFrame(nextThumbnail);}
$('presetFamily').onchange=$('lookSearch').oninput=filterLooks;
function visibleLooks(){return [...document.querySelectorAll('.preset')].filter(b=>!b.hidden&&!b.disabled&&b.getClientRects().length);}
function audition(button){const id=Number(button.dataset.lookId);if(window.lookPreviewUI){window.lookPreviewUI.choose(id);button.focus({preventScroll:true});button.scrollIntoView({block:'nearest'});return;}if(!img||!node())return;mutate(()=>{const n=node();n.looks||=[];for(const l of n.looks)l.enabled=false;if(id){let look=n.looks.find(l=>l.id===id);if(!look){look={id,name:looks[id][0],values:structuredClone(looks[id][2]),amount:100};n.looks.push(look);}look.enabled=true;}});button.focus({preventScroll:true});button.scrollIntoView({block:'nearest'});}
$('presets').addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const b=e.target.closest('.preset'),list=visibleLooks();if(!b||!list.length)return;e.preventDefault();e.stopPropagation();const at=list.indexOf(b),next=e.key==='Home'?0:e.key==='End'?list.length-1:Math.max(0,Math.min(list.length-1,at+(['ArrowUp','ArrowLeft'].includes(e.key)?-1:1)));audition(list[next]);});
// Thumbnail rendering has its own low-resolution worker, separate from the main preview.
async function beginThumbnails(){const image=img,generation=++thumbnailGeneration;photo=image;worker?.terminate();clearTimeout(thumbnailTimer);worker=null;thumbnailIndex=0;thumbnailBusy=false;completedThumbnails.clear();document.querySelectorAll('.look-thumb').forEach(c=>c.remove());if(!image)return;await new Promise(resolve=>setTimeout(resolve,250));if(generation!==thumbnailGeneration)return;const scale=Math.min(1,512/Math.max(image.naturalWidth,image.naturalHeight));const bitmap=await createImageBitmap(image,{resizeWidth:Math.max(1,Math.round(image.naturalWidth*scale)),resizeHeight:Math.max(1,Math.round(image.naturalHeight*scale)),resizeQuality:'high'});if(generation!==thumbnailGeneration){bitmap.close();return;}const local=new Worker('render-worker.js');worker=local;local.postMessage({type:'source',bitmap},[bitmap]);local.onmessage=({data})=>{if(generation!==thumbnailGeneration){data.bitmap?.close();return;}thumbnailBusy=false;completedThumbnails.add(data.id);const b=document.querySelector('.preset[data-look-id="'+data.id+'"]');if(data.bitmap&&b){const canvas=document.createElement('canvas');canvas.className='look-thumb';canvas.width=data.bitmap.width;canvas.height=data.bitmap.height;canvas.getContext('2d').drawImage(data.bitmap,0,0);data.bitmap.close();const swatch=b.querySelector('.swatch');swatch.style.filter='none';swatch.classList.add('photo-swatch');swatch.replaceChildren(canvas);b.dataset.previewPhoto=current?.id||'';}if(data.error)console.warn('Look preview:',data.error);thumbnailTimer=setTimeout(nextThumbnail,25);};local.onerror=e=>console.warn('Look previews unavailable:',e.message);nextThumbnail();}
function nextThumbnail(){if(!worker||thumbnailBusy)return;const viewport=$('presets').getBoundingClientRect();const button=visibleLooks().find(b=>{const r=b.getBoundingClientRect();return !completedThumbnails.has(Number(b.dataset.lookId))&&r.bottom>=Math.max(0,viewport.top)-100&&r.top<=Math.min(innerHeight,viewport.bottom)+100;});if(!button)return;const id=Number(button.dataset.lookId),s=structuredClone(Imaging.defaults);s.precision=documentSettings.precision;s.nodes=id?[{enabled:true,operation:'develop',adjustments:structuredClone(Imaging.defaults),looks:[{id,values:looks[id][2],amount:100,enabled:true}]}]:[];thumbnailBusy=true;worker.postMessage({type:'preview',id,settings:s,max:120,original:false});}
document.addEventListener('scroll',()=>{clearTimeout(thumbnailTimer);thumbnailTimer=setTimeout(nextThumbnail,70);},true);window.addEventListener('resize',()=>nextThumbnail());
const rating=document.createElement('div');rating.id='photoRating';rating.setAttribute('aria-label','Photo rating');$('favorite').before(rating);for(let i=1;i<=5;i++){const b=document.createElement('button');b.textContent='☆';b.title='Rate '+i+' star'+(i>1?'s':'')+' ('+i+')';b.setAttribute('aria-label','Rate '+i+' stars');b.onclick=()=>rate(current?.rating===i?0:i);rating.append(b);}function rate(value){if(!current)return;current.rating=value;save();refresh();}
async function navigatePhoto(step){if(navigating||!current)return;const photos=visible(),at=photos.findIndex(p=>p.id===current.id),p=photos[at+step];if(!p)return;navigating=true;try{setMode('edit');await select(p.id);}catch(e){fail(e);}finally{navigating=false;}}
const helpButton=document.createElement('button');helpButton.id='keyboardHelp';helpButton.textContent='⌨';helpButton.title='Keyboard shortcut settings';helpButton.setAttribute('aria-label','Keyboard shortcut settings');document.querySelector('.canvas-tools').firstElementChild.append(helpButton);helpButton.onclick=()=>window.keyboardSettings.open();
Shortcuts.register('export','Export photo','Photos',['mod+shift+e'],()=>$('export').click());
Shortcuts.register('fullscreen','Toggle fullscreen','View',['f','f11'],()=>window.previewUI?.active()?window.previewUI.exit():api.fullscreen().catch(fail));
Shortcuts.register('exitFullscreen','Exit fullscreen','View',['escape'],()=>window.previewUI?.active()?window.previewUI.exit():api.fullscreen(false).catch(fail));
for(let i=0;i<=5;i++)Shortcuts.register('rating'+i,i?'Rate '+i+' stars':'Clear rating','Ratings',[i?'alt+'+i:'0'],()=>rate(i),()=>!!current);
for(const [id,label,key,value]of [['favorite','Mark favorite','p',true],['unfavorite','Unmark favorite','u',false]])Shortcuts.register(id,label,'Ratings',[key],()=>{current.favorite=value;save();refresh();},()=>!!current);
Shortcuts.register('masks','Open Masks','Editing',['m'],()=>window.advancedUI.setTool('mask'),()=>!!img);
Shortcuts.register('overlay','Toggle mask overlay','Editing',['o'],()=>{$('maskOverlay').checked=!$('maskOverlay').checked;window.maskUI.overlay();},()=>!!img);
for(const [id,label,key,step]of [['previousPhoto','Previous photo','arrowleft',-1],['nextPhoto','Next photo','arrowright',1]])Shortcuts.register(id,label,'Photos',[key],()=>navigatePhoto(step),e=>!!current&&!e.target.closest('#nodeTargets,#nodeGraph,.color-chips,#wipeDivider'));
Shortcuts.register('focus','Toggle Focus view','View',['tab'],()=>$('focusView').click(),e=>Shortcuts.key(e)!=='tab'||e.target===document.body||!!e.target.closest('#stage'));
function syncBrowser(){const before=looks.length;installLooks();
// Bundled collections must not make a previously saved personal look point at another recipe.
let rebound=false;for(const n of documentSettings.nodes||[])for(const l of n.looks||[]){if(looks[l.id]?.[0]===l.name)continue;const id=looks.findIndex(v=>v[0]===l.name);if(id>=0){l.id=id;rebound=true;}else if(l.id>=0){l.id=-Math.abs(l.id||1);rebound=true;}}if(rebound)window.nodeFlowUI?.sync();
add.disabled=!img;browse.disabled=!img;for(const [i,b]of [...rating.children].entries()){b.disabled=!current;b.textContent=(current?.rating||0)>i?'★':'☆';b.setAttribute('aria-pressed',String((current?.rating||0)>i));}document.querySelectorAll('.preset').forEach(b=>b.disabled=!img);if(photo!==img)beginThumbnails().catch(fail);else if(before!==looks.length){nextThumbnail();filterLooks();}}
window.lookBrowserUI={sync:syncBrowser,filter:filterLooks,refreshThumbnails:nextThumbnail,recipe:()=>documentSettings.nodes.filter(n=>n.enabled!==false).map(cleanRecipe)};syncBrowser();
})();
