const {app,BrowserWindow,ipcMain,dialog,nativeImage}=require('electron');
const fs=require('node:fs/promises');
const path=require('node:path');
const crypto=require('node:crypto');
const {pathToFileURL}=require('node:url');
const Projects=require('./projects.cjs');
const Formats=require('./photo-formats.cjs'),Raw=require('./raw-service.cjs');
const {libraryRoot,importLibrary}=require('./library.cjs');
const root=libraryRoot(app,process.env,__dirname);
app.setPath('userData',app.isPackaged&&!process.env.LUMA_DATA_DIR?path.join(app.getPath('appData'),'Lith','settings'):path.join(root,'settings'));
if(app.isPackaged)app.setAppUserModelId?.('io.github.skarn03.lith');
app.setName?.('Lith');
const ownsLibrary=app.requestSingleInstanceLock?.()??true;
if(!ownsLibrary)app.quit();
let win; let catalog={photos:[],selected:null}; let queue=Promise.resolve();
app.on('second-instance',()=>{if(win){if(win.isMinimized())win.restore();win.focus();}});
const persist=()=>{const snapshot=JSON.stringify(catalog); queue=queue.catch(()=>{}).then(async()=>{await fs.writeFile(path.join(root,'catalog.tmp'),snapshot);await fs.rename(path.join(root,'catalog.tmp'),path.join(root,'catalog.json'));});return queue;};
async function ingest(paths){const project=Projects.project(catalog,catalog.activeProjectId);const added=[];const errors=[];for(const source of paths){try{const ext=path.extname(source).toLowerCase();if(!Formats.all.includes(ext))throw Error('Use a supported camera RAW, JPEG, PNG, or WebP file');const stat=await fs.stat(source);if(stat.size>150*1024*1024)throw Error('File exceeds 150 MB');const id=crypto.randomUUID();await fs.copyFile(source,path.join(root,'originals',id+ext));const p={id,projectId:project.id,name:path.basename(source),ext,size:stat.size,settings:{precision:"float32"},favorite:false};catalog.photos.push(p);added.push(p);}catch(e){errors.push(path.basename(source)+': '+e.message);}}if(added.length){project.selected=added[added.length-1].id;if(catalog.activeProjectId===project.id)catalog.selected=project.selected;}await persist();return {catalog,errors};}
app.whenReady().then(async()=>{if(!ownsLibrary)return;await fs.mkdir(path.join(root,'originals'),{recursive:true});try{catalog=JSON.parse(await fs.readFile(path.join(root,'catalog.json'),'utf8'));}catch(e){if(e.code!=='ENOENT'){await dialog.showMessageBox({type:'error',message:'The photo library could not be read.',detail:'Your files have been preserved. '+e.message});app.quit();return;}}
Projects.normalize(catalog);await persist();
require('./batch-service.cjs').setup({ipcMain,getCatalog:()=>catalog,persist,root,chooseExportFolder});
ipcMain.handle('catalog',()=>catalog);
ipcMain.handle('project',async(_,action)=>{
 if(action.type==='create'){const name=String(action.name||'Untitled project').trim().slice(0,60)||'Untitled project';const p={id:crypto.randomUUID(),name,settings:Projects.defaults(),selected:null};catalog.projects.push(p);catalog.activeProjectId=p.id;catalog.selected=null;}
 else if(action.type==='switch'){const p=Projects.project(catalog,action.id);catalog.activeProjectId=p.id;catalog.selected=p.selected||null;}
 else if(action.type==='update'){const p=Projects.project(catalog,action.id);p.name=String(action.name||p.name).trim().slice(0,60)||p.name;p.settings=Projects.settings(action.settings||p.settings);}
 else if(action.type==='move'){const target=Projects.project(catalog,action.id),photo=catalog.photos.find(p=>p.id===action.photoId);if(!photo)throw Error('Photo not found');const source=Projects.project(catalog,photo.projectId);photo.projectId=target.id;target.selected=photo.id;if(source.selected===photo.id)source.selected=catalog.photos.find(p=>p.projectId===source.id)?.id||null;catalog.selected=Projects.project(catalog,catalog.activeProjectId).selected||null;}
 else throw Error('Unknown project action');await persist();return catalog;
});
const thumbnailJobs=new Map();let thumbnailQueue=Promise.resolve();
ipcMain.handle('thumbnail',(_,id)=>{if(thumbnailJobs.has(id))return thumbnailJobs.get(id);const job=thumbnailQueue.catch(()=>{}).then(async()=>{const p=catalog.photos.find(p=>p.id===id);if(!p)throw Error('Photo not found');const dir=path.join(root,'thumbnails'),target=path.join(dir,(p.sourceId||p.id)+'.jpg');try{await fs.access(target);}catch{await fs.mkdir(dir,{recursive:true});const image=await nativeImage.createThumbnailFromPath(Formats.isRaw(p.ext)?await Raw.image(root,{...p,id:p.sourceId||p.id},true):path.join(root,'originals',(p.sourceId||p.id)+p.ext),{width:240,height:240});await fs.writeFile(target,image.toJPEG(75));}return pathToFileURL(target).href;});thumbnailQueue=job;thumbnailJobs.set(id,job);job.finally(()=>thumbnailJobs.delete(id)).catch(()=>{});return job;});
ipcMain.handle('library-import',async()=>{if(catalog.photos.length||catalog.customLooks?.length)throw Error('Restore requires an empty library. Your existing photos and looks are unchanged.');const picked=await dialog.showOpenDialog(win,{title:'Choose your previous Luma Library folder',properties:['openDirectory']});if(picked.canceled)return false;await queue;catalog=await importLibrary(picked.filePaths[0],root);win.reload();return true;});
ipcMain.handle('virtual-copy',async(_,id)=>{const original=catalog.photos.find(p=>p.id===id);if(!original)throw Error('Photo not found');const sourceId=original.sourceId||original.id;const number=1+Math.max(0,...catalog.photos.filter(p=>(p.sourceId||p.id)===sourceId).map(p=>p.copyNumber||0));const name=original.originalName||original.name;const copy={...structuredClone(original),id:crypto.randomUUID(),sourceId,originalName:name,copyNumber:number,name:name.replace(/\.[^.]+$/,'')+' · Copy '+number+original.ext};catalog.photos.splice(catalog.photos.indexOf(original)+1,0,copy);await persist();return {catalog,id:copy.id};});
require('./effect-assets.cjs').setup({ipcMain,dialog,getWindow:()=>win,root});
require('./look-sharing.cjs').setup({ipcMain,dialog,getWindow:()=>win,root});
ipcMain.handle('save-look',async(_,look)=>{const item=require('./look-sharing.cjs').normalize(look);catalog.customLooks||=[];const base=item.name;let suffix=2;while(catalog.customLooks.some(l=>l.name===item.name))item.name=base+' ('+suffix+++')';catalog.customLooks.push(item);try{await persist();}catch(e){catalog.customLooks.splice(catalog.customLooks.indexOf(item),1);throw e;}return catalog.customLooks;});
ipcMain.handle('fullscreen',(_,value)=>{win.setFullScreen(typeof value==='boolean'?value:!win.isFullScreen());return win.isFullScreen();});
ipcMain.handle('import',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile','multiSelections'],filters:[{name:'Photos',extensions:Formats.all.map(ext=>ext.slice(1))}]});return r.canceled?{catalog,errors:[]}:ingest(r.filePaths);});
ipcMain.handle('drop',(_,paths)=>ingest(paths));
ipcMain.handle('raw-data',async(_,id,raw)=>{const p=catalog.photos.find(p=>p.id===id);if(!p||!Formats.isRaw(p.ext))return null;return fs.readFile(await Raw.image(root,{...p,id:p.sourceId||p.id},false,raw));});
ipcMain.handle('image',async(_,id,raw)=>{const p=catalog.photos.find(p=>p.id===id);if(!p)throw Error('Photo not found');return pathToFileURL(Formats.isRaw(p.ext)?(await Raw.image(root,{...p,id:p.sourceId||p.id},false,raw))+(require('./raw-color.js').normalize(raw)?'.display.png':''):path.join(root,'originals',(p.sourceId||p.id)+p.ext)).href;});
ipcMain.handle('save',async(_,update)=>{const p=catalog.photos.find(p=>p.id===update.id);if(!p)return; if(update.settings)p.settings=update.settings;if(typeof update.favorite==='boolean')p.favorite=update.favorite;if(Number.isInteger(update.rating)&&update.rating>=0&&update.rating<=5)p.rating=update.rating;const project=Projects.project(catalog,p.projectId);project.selected=p.id;if(catalog.activeProjectId===project.id)catalog.selected=p.id;await persist();});
async function chooseExportFolder(projectId){const project=Projects.project(catalog,projectId);const result=await dialog.showOpenDialog(win,{title:'Choose a folder for exported photos',properties:['openDirectory','createDirectory'],defaultPath:project.exportFolder||app.getPath('pictures')});if(result.canceled)return null;const folder=await fs.realpath(result.filePaths[0]);const library=await fs.realpath(root);if(folder.toLowerCase()===library.toLowerCase()||folder.toLowerCase().startsWith(library.toLowerCase()+path.sep))throw Error('Choose a location outside the internal photo library.');project.exportFolder=folder;await persist();return folder;}
ipcMain.handle('export-folder',(_,id)=>chooseExportFolder(id));
ipcMain.handle('quick-export',async(_,data)=>{const photo=catalog.photos.find(p=>p.id===data.photoId);if(!photo||!['jpeg','png','webp'].includes(data.format)||!(data.bytes instanceof Uint8Array||data.bytes instanceof ArrayBuffer))throw Error('Invalid export');const project=Projects.project(catalog,data.projectId);const folder=project.exportFolder||await chooseExportFolder(project.id);if(!folder)return null;const realFolder=await fs.realpath(folder),library=await fs.realpath(root);if(realFolder.toLowerCase()===library.toLowerCase()||realFolder.toLowerCase().startsWith(library.toLowerCase()+path.sep))throw Error('Choose a location outside the internal photo library.');const stem=path.basename(photo.name).replace(/\.[^.]+$/,'').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,120)||'Photo',ext=data.format==='jpeg'?'jpg':data.format;const bytes=Buffer.from(data.bytes);for(let i=0;i<10000;i++){const file=path.join(realFolder,stem+'-edited'+(i?' ('+(i+1)+')':'')+'.'+ext);try{await fs.writeFile(file,bytes,{flag:'wx'});return {file,folder};}catch(e){if(e.code!=='EEXIST')throw e;}}throw Error('Too many exports with this name. Choose another folder.');});
ipcMain.handle('export',async(_,data)=>{if(!['png','jpeg','webp'].includes(data.format)||typeof data.base64!=='string')throw Error('Invalid export');const result=await dialog.showSaveDialog(win,{defaultPath:data.name.replace(/\.[^.]+$/,'')+'-edited.'+(data.format==='jpeg'?'jpg':data.format),filters:[{name:'Edited image',extensions:[data.format==='jpeg'?'jpg':data.format]}]});if(result.canceled)return false;const target=path.resolve(result.filePath);if(target.toLowerCase().startsWith(path.resolve(root).toLowerCase()+path.sep))throw Error('Choose a location outside the internal photo library.');await fs.writeFile(target,Buffer.from(data.base64,'base64'));if(data.projectId){Projects.project(catalog,data.projectId).exportFolder=path.dirname(target);await persist();}return true;});
win=new BrowserWindow({width:1480,height:960,minWidth:1000,minHeight:720,backgroundColor:'#292929',title:'Lith — Photo Studio',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});
require('./second-display.cjs').setupSecondDisplay(win);
let closing=false;win.on('close',event=>{if(closing)return;event.preventDefault();win.webContents.executeJavaScript('typeof flush === "function" ? flush() : Promise.resolve()').then(()=>{closing=true;win.close();}).catch(error=>dialog.showMessageBox(win,{type:'error',message:'Edits could not be saved. Please try closing again.',detail:error.message}));});
win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());require('./updater.cjs').setupUpdates(win,async()=>{await win.webContents.executeJavaScript("typeof flush === 'function' ? flush() : Promise.resolve()");await queue;closing=true;});await win.loadFile(path.join(__dirname,'index.html'));
});
app.on('window-all-closed',()=>app.quit());
