(()=>{
let selected=null,selectedPart=null,photoId=null,drawing=false,stroke=null,pointer=null,brushSize=8,overlayFrame=0,toolActive=false;
const frame=document.createElement('div');frame.id='photoFrame';$('photo').before(frame);frame.append($('photo'));const overlay=document.createElement('canvas');overlay.id='maskCanvas';overlay.setAttribute('aria-label','Draw a mask on the photograph');frame.append(overlay);
const selectedGroup=()=>settings.masks?.find(m=>m.id===selected);
const selectedMask=()=>selectedGroup()?.components?.find(m=>m.id===selectedPart)||selectedGroup();
const colorAdd=document.createElement('button');colorAdd.id='maskAddColor';colorAdd.textContent='◉ Color range';document.querySelector('.mask-add').append(colorAdd);colorAdd.onclick=()=>add('color');
const colorPanel=document.createElement('div');colorPanel.id='colorMaskControls';$('maskSliders').before(colorPanel);for(const [key,label,type,min,max]of [['color','Sampled color','color'],['tolerance','Color tolerance','range',1,180],['minSaturation','Minimum saturation','range',0,100],['minLuma','Minimum lightness','range',0,100],['maxLuma','Maximum lightness','range',0,100]]){const lab=document.createElement('label');lab.className='color-row';lab.textContent=label;const input=document.createElement('input');input.id='maskColor-'+key;input.type=type;if(type==='range'){input.min=min;input.max=max;}input.onchange=()=>mutate(()=>{const m=selectedMask();if(m)m[key]=type==='color'?input.value:Number(input.value);});lab.append(input);colorPanel.append(lab);}
const combinations=document.createElement('section');combinations.id='maskCombinations';combinations.innerHTML='<div class="mask-combine-heading">Combine this mask</div><p class="small muted">Add expands · Subtract removes · Intersect keeps overlap. Adjustments apply once to the combined result.</p><label>Editing shape<select id="maskComponent" aria-label="Mask shape"></select></label><div class="mask-component-options"><label>Blend<select id="maskComponentMode" aria-label="Selected shape combination"><option value="add">＋ Add</option><option value="subtract">− Subtract</option><option value="intersect">∩ Intersect</option></select></label><label><input id="maskComponentEnabled" type="checkbox"> Shape enabled</label><button id="removeMaskComponent">Remove shape</button></div><label>New shape mode<select id="newMaskComponentMode" aria-label="New mask shape combination"><option value="add">＋ Add to mask</option><option value="subtract">− Subtract from mask</option><option value="intersect">∩ Intersect with mask</option></select></label><div id="maskComponentTools" class="mask-add"></div><label><input id="maskCombinedInvert" type="checkbox"> Invert combined result</label><p id="maskGroupHint" class="small muted"></p>';$('maskProperties').prepend(combinations);
for(const [type,label]of [['brush','✎ Brush'],['linear','▥ Gradient'],['radial','◎ Radial'],['color','◉ Color range']]){const button=document.createElement('button');button.textContent=label;button.dataset.componentType=type;button.onclick=()=>{const group=selectedGroup();if(!group||(group.components?.length||0)>=11)return;mutate(()=>{const part={id:crypto.randomUUID(),type,combine:$('newMaskComponentMode').value,enabled:true,invert:false,feather:65,strokes:[]};group.components||=[];group.components.push(part);selectedPart=part.id;drawing=true;});$('maskOverlay').checked=true;queueOverlay();};$('maskComponentTools').append(button);}
function syncComponents(){const group=selectedGroup(),part=selectedMask(),picker=$('maskComponent');picker.replaceChildren();if(!group)return;picker.append(new Option('Base · '+group.type,''));for(const [i,p]of (group.components||[]).entries())picker.append(new Option((i+1)+'. '+({add:'＋',subtract:'−',intersect:'∩'}[p.combine]||'＋')+' '+p.type+(p.enabled===false?' (off)':''),p.id));picker.value=selectedPart||'';$('maskCombinedInvert').checked=!!group.combinedInvert;const extra=!!selectedPart;$('maskComponentMode').disabled=!extra;$('maskComponentMode').value=part.combine||'add';$('maskComponentEnabled').disabled=!extra;$('maskComponentEnabled').checked=part.enabled!==false;$('removeMaskComponent').disabled=!extra;for(const b of $('maskComponentTools').children)b.disabled=!img||(group.components?.length||0)>=11;$('maskGroupHint').textContent=extra?'Feather, color and Invert edit this shape. Local adjustments affect the whole combined mask.':'Editing the base shape. Invert shape affects the base only. Enabled switches the whole mask on/off.';}
$('maskInvert').parentElement.lastChild.textContent=' Invert shape';$('maskCombinedInvert').onchange=()=>mutate(()=>{if(selectedGroup())selectedGroup().combinedInvert=$('maskCombinedInvert').checked;});
$('maskComponent').onchange=()=>{selectedPart=$('maskComponent').value||null;drawing=false;syncMasks();};$('maskComponentMode').onchange=()=>mutate(()=>{if(selectedPart)selectedMask().combine=$('maskComponentMode').value;});$('maskComponentEnabled').onchange=()=>mutate(()=>{if(selectedPart)selectedMask().enabled=$('maskComponentEnabled').checked;});$('removeMaskComponent').onclick=()=>mutate(()=>{const group=selectedGroup();if(group&&selectedPart)group.components=group.components.filter(p=>p.id!==selectedPart);selectedPart=null;drawing=false;});
const rows=[['size','Brush radius',1,30,1],['feather','Feather',0,100,1],['exposure','Local exposure',-3,3,.05],['contrast','Local contrast',-100,100,1],['temperature','Local temperature',-100,100,1],['saturation','Local saturation',-100,100,1]];
for(const [key,label,min,max,step]of rows){const row=document.createElement('div');row.className='slider-row';row.id='maskRow-'+key;const lab=document.createElement('label');lab.className='slider-label';lab.htmlFor='mask-'+key;lab.append(document.createTextNode(label));const out=document.createElement('output');out.id='maskValue-'+key;lab.append(out);const input=document.createElement('input');Object.assign(input,{type:'range',id:'mask-'+key,min,max,step});let started=false;input.oninput=()=>{const m=selectedMask();if(!m)return;if(key==='size'){brushSize=Number(input.value);}else{if(!started){pushHistory();started=true;}if(key==='feather')m.feather=Number(input.value);else selectedGroup().adjustments[key]=Number(input.value);scheduleRender();}out.textContent=key==='exposure'?Number(input.value).toFixed(2):input.value;queueOverlay();};input.onchange=()=>{started=false;save();render();};row.append(lab,input);$('maskSliders').append(row);}
function syncMasks(){const active=!!img&&!!current;const photoKey=(current?.id||'')+'|'+(window.nodeUI?.targetId()||'');if(photoId!==photoKey){photoId=photoKey;selected=null;selectedPart=null;drawing=false;stroke=null;}const masks=settings.masks||[];if(!masks.some(m=>m.id===selected))selected=masks.at(-1)?.id||null;const list=$('maskList');const signature=masks.map(m=>m.id).join(',');if(list.dataset.signature!==signature){list.replaceChildren();for(const m of masks){const option=document.createElement('option');option.value=m.id;option.textContent=m.name;list.append(option);}list.dataset.signature=signature;}list.value=selected||'';list.hidden=!masks.length;if(!selectedGroup()?.components?.some(m=>m.id===selectedPart))selectedPart=null;syncComponents();const m=selectedMask();$('maskProperties').hidden=!m;$('maskCount').textContent=masks.length;for(const id of ['addBrush','addLinear','addRadial'])$(id).disabled=!active||masks.length>=12;colorPanel.hidden=m?.type!=='color';if(m?.type==='color')for(const k of ['color','tolerance','minSaturation','minLuma','maxLuma'])$('maskColor-'+k).value=m[k]??({color:'#e0a060',tolerance:25,maxLuma:100}[k]??0);if(m){$('maskEnabled').checked=selectedGroup().enabled!==false;$('maskInvert').checked=!!m.invert;for(const [key]of rows){const value=key==='size'?brushSize:key==='feather'?m.feather:selectedGroup().adjustments[key]||0;$('mask-'+key).value=value;$('maskValue-'+key).textContent=key==='exposure'?Number(value).toFixed(2):Math.round(value);} $('maskRow-size').hidden=m.type!=='brush';$('maskErase').disabled=m.type!=='brush';$('maskDone').textContent=drawing?'Done drawing':'Edit shape';}
$('maskHint').textContent=!m?'Add a mask, then draw directly on the photograph.':!drawing?'Adjust only the masked area. Choose Edit shape to draw again.':m.type==='color'?'Click a color in the photograph to select similar colors. Adjust tolerance and feather.':m.type==='brush'?'Paint on the photo. Erase removes strokes from this mask.':m.type==='radial'?'Drag from the center outward to create a soft ellipse.':'Drag from the strongest adjustment toward the unmasked area.';queueOverlay();}
function drawOverlay(){overlayFrame=0;const c=$('photo'),m=selectedGroup();overlay.width=c.width;overlay.height=c.height;overlay.hidden=!toolActive||!img||comparing||!m;overlay.style.pointerEvents=toolActive&&drawing&&!comparing&&m?'auto':'none';frame.classList.toggle('painting',toolActive&&drawing&&!comparing);if(!toolActive||!img||comparing||!m||!$('maskOverlay').checked)return;const ctx=overlay.getContext('2d');const g=Imaging.geometry(img.naturalWidth,img.naturalHeight,settings),b=FX.borderGeometry(g.width,g.height,settings),scale=c.width/b.width;const mask=Imaging.maskForImage(img,m,settings,Math.max(c.width,c.height));ctx.drawImage(mask,b.inset*scale,b.inset*scale,g.width*scale,g.height*scale);ctx.globalCompositeOperation='source-in';ctx.fillStyle='rgba(238,95,117,0.42)';ctx.fillRect(0,0,c.width,c.height);}
function queueOverlay(){if(!overlayFrame)overlayFrame=requestAnimationFrame(drawOverlay);}
function add(type){if(!img||(settings.masks||[]).length>=12)return;mutate(()=>{const m={id:crypto.randomUUID(),name:(type==='color'?'Color':type==='brush'?'Brush':type==='radial'?'Radial':'Linear')+' '+((settings.masks?.length||0)+1),type,feather:65,enabled:true,invert:false,adjustments:{exposure:.3,contrast:0,temperature:0,saturation:0},strokes:[]};settings.masks||=[];settings.masks.push(m);selected=m.id;selectedPart=null;drawing=true;});$('maskOverlay').checked=true;syncMasks();}
$('addBrush').onclick=()=>add('brush');$('addLinear').onclick=()=>add('linear');$('addRadial').onclick=()=>add('radial');$('maskList').onchange=()=>{selected=$('maskList').value;selectedPart=null;drawing=false;syncMasks();};$('maskDone').onclick=()=>{drawing=!drawing;syncMasks();};$('deleteMask').onclick=()=>mutate(()=>{settings.masks=settings.masks.filter(m=>m.id!==selected);selected=null;drawing=false;});for(const [id,key]of [['maskEnabled','enabled'],['maskInvert','invert']])$(id).onchange=()=>mutate(()=>{const m=key==='enabled'?selectedGroup():selectedMask();if(m)m[key]=$(id).checked;});$('maskOverlay').onchange=queueOverlay;
function position(e){const r=overlay.getBoundingClientRect();const g=Imaging.geometry(img.naturalWidth,img.naturalHeight,settings),b=FX.borderGeometry(g.width,g.height,settings);return Imaging.sourcePoint(Math.max(0,Math.min(1,((e.clientX-r.left)/r.width*b.width-b.inset)/g.width)),Math.max(0,Math.min(1,((e.clientY-r.top)/r.height*b.height-b.inset)/g.height)),img.naturalWidth,img.naturalHeight,settings);}
overlay.onpointerdown=e=>{if(e.button!==0||!drawing||!img||comparing)return;const m=selectedMask();if(!m)return;e.preventDefault();overlay.setPointerCapture(e.pointerId);pointer=e.pointerId;pushHistory();const p=position(e);if(m.type==='color'){const sample=document.createElement('canvas');sample.width=sample.height=1;const cx=sample.getContext('2d');cx.drawImage(img,Math.max(0,Math.min(img.naturalWidth-1,p.x*img.naturalWidth)),Math.max(0,Math.min(img.naturalHeight-1,p.y*img.naturalHeight)),1,1,0,0,1,1);const pixel=cx.getImageData(0,0,1,1).data;m.color='#'+[...pixel].slice(0,3).map(v=>v.toString(16).padStart(2,'0')).join('');drawing=false;pointer=null;save();render();syncMasks();return;}if(m.type==='brush'){stroke={size:brushSize/100,erase:$('maskErase').checked,points:[p]};m.strokes.push(stroke);}else{m.start=p;m.end=p;}queueOverlay();};
overlay.onpointermove=e=>{if(pointer!==e.pointerId)return;const m=selectedMask();if(!m)return;const p=position(e);if(stroke){const last=stroke.points.at(-1);if(Math.hypot(p.x-last.x,p.y-last.y)<.001)return;stroke.points.push(p);}else m.end=p;queueOverlay();scheduleRender();};
function finish(e){if(pointer!==e.pointerId)return;pointer=null;stroke=null;save();render();queueOverlay();}overlay.onpointerup=finish;overlay.onpointercancel=finish;
window.maskUI={isEditing:()=>toolActive&&drawing,sync:syncMasks,overlay:queueOverlay,setActive:value=>{toolActive=value;queueOverlay();}};
const theme=$('theme');try{theme.value=localStorage.getItem('luma-theme')||'dark';}catch{}document.documentElement.dataset.theme=theme.value;theme.onchange=()=>{document.documentElement.dataset.theme=theme.value;try{localStorage.setItem('luma-theme',theme.value);}catch{}};
syncMasks();
})();
