(()=>{
const target=document.createElement('div');target.id='nodeTargets';target.setAttribute('role','tablist');target.setAttribute('aria-label','Edit target');document.querySelector('.target-picker').before(target);document.querySelector('.target-picker').hidden=true;
$('nodeSetup').querySelector('summary').textContent='Node settings';$('nodeOperation').closest('label').hidden=true;$('blendPanel').hidden=true;$('nodeHelp').hidden=true;
const strength=document.createElement('label');strength.className='node-strength';strength.textContent='Node strength';const amount=document.createElement('input');amount.type='range';amount.min=0;amount.max=100;amount.setAttribute('aria-label','Node strength');const output=document.createElement('output');strength.append(output,amount);$('nodeSetup').append(strength);let strengthStarted=false;
const currentNode=()=>documentSettings.nodes.find(n=>n.uid===activeNodeUid);
amount.oninput=()=>{const n=currentNode();if(!n)return;if(!strengthStarted){pushHistory();strengthStarted=true;}n.mix=Number(amount.value);output.textContent=amount.value+'%';scheduleRender();};amount.onchange=()=>{strengthStarted=false;save();render();};
const lookHint=document.createElement('p');lookHint.className='look-instruction';lookHint.textContent='Click to layer or remove · Right-click for strength';$('lookSearch').before(lookHint);
const stack=document.createElement('details');stack.id='selectedLooks';stack.open=true;stack.innerHTML='<summary>Selected looks <span id="selectedLookCount">0</span></summary><div id="lookLayers"></div>';$('nodeSetup').after(stack);
const pop=document.createElement('dialog');pop.id='lookStrengthDialog';pop.innerHTML='<form method="dialog"><div class="dialog-top"><strong id="lookStrengthTitle"></strong><button aria-label="Close look strength">✕</button></div><p class="small muted">Blend this look into the current node.</p><label>Strength <output id="lookStrengthValue">100%</output><input id="lookStrength" type="range" min="0" max="100" value="100"></label><button type="button" id="toggleLookInDialog">Enable look</button></form>';document.body.append(pop);let popLook=null,popTarget=null,started=false;
function findLook(id,n=currentNode()){return n?.looks?.find(l=>l.id===id);}
function toggleLook(id){if(!img)return;mutate(()=>{const n=currentNode();if(!n)return;n.looks||=[];const old=findLook(id,n);if(old)old.enabled=!old.enabled;else n.looks.push({id,name:looks[id][0],values:structuredClone(looks[id][2]),amount:100,enabled:true});});}
function editLook(id){if(!img||id===0)return;popLook=id;popTarget=activeNodeUid;const item=findLook(id);$('lookStrengthTitle').textContent=looks[id][0];$('lookStrength').value=item?.amount??100;$('lookStrengthValue').textContent=(item?.amount??100)+'%';$('toggleLookInDialog').textContent=item?.enabled!==false&&item?'Deselect look':'Select look';pop.showModal();}
$('lookStrength').oninput=()=>{if(popTarget!==activeNodeUid){pop.close();return;}const n=currentNode();if(!n)return;if(!started){pushHistory();started=true;}n.looks||=[];let item=findLook(popLook,n);if(!item){item={id:popLook,name:looks[popLook][0],values:structuredClone(looks[popLook][2]),enabled:true,amount:100};n.looks.push(item);}item.amount=Number($('lookStrength').value);$('lookStrengthValue').textContent=item.amount+'%';scheduleRender();};$('lookStrength').onchange=()=>{started=false;render();save();};$('toggleLookInDialog').onclick=()=>{toggleLook(popLook);$('toggleLookInDialog').textContent=findLook(popLook)?.enabled?'Deselect look':'Select look';};pop.addEventListener('close',()=>{if(started){started=false;save();render();}});
function bindLook(b,id){b.dataset.lookId=id;b.setAttribute('aria-pressed','false');b.title=id?'Click to toggle; right-click to blend.':'Deselect all looks in this node; manual edits remain.';b.onclick=()=>{if(id===0)mutate(()=>{for(const look of currentNode()?.looks||[])look.enabled=false;});else toggleLook(id);};b.oncontextmenu=e=>{e.preventDefault();editLook(id);};b.onkeydown=e=>{if(e.key==='ContextMenu'||e.shiftKey&&e.key==='F10'){e.preventDefault();editLook(id);}};}document.querySelectorAll('.preset').forEach((b,id)=>bindLook(b,id));
let signature='',targetSignature='';function syncFlow(){const n=currentNode();const key=JSON.stringify([activeNodeUid,n?.looks,!!img]);if(key!==signature){signature=key;const selected=(n?.looks||[]).filter(l=>l.enabled!==false);$('selectedLookCount').textContent=selected.length;stack.hidden=!selected.length;const rows=$('lookLayers');rows.replaceChildren();for(const look of selected){const row=document.createElement('div');row.className='look-layer';const label=document.createElement('button');label.textContent=look.name;label.title='Adjust look strength';label.onclick=()=>editLook(look.id);const mix=document.createElement('output');mix.textContent=(look.amount??100)+'%';const slider=document.createElement('input');slider.type='range';slider.min=0;slider.max=100;slider.value=look.amount??100;slider.setAttribute('aria-label',look.name+' strength');let dragging=false;slider.oninput=()=>{if(!dragging){pushHistory();dragging=true;}look.amount=Number(slider.value);mix.textContent=look.amount+'%';scheduleRender();};slider.onchange=()=>{dragging=false;save();render();};slider.ondblclick=()=>mutate(()=>look.amount=100);const remove=document.createElement('button');remove.textContent='×';remove.setAttribute('aria-label','Deselect '+look.name);remove.onclick=()=>toggleLook(look.id);row.append(label,mix,remove,slider);rows.append(row);}document.querySelectorAll('.preset').forEach((b,id)=>{const l=findLook(id,n),enabled=id===0?!selected.length:!!l&&l.enabled!==false;b.classList.toggle('active',enabled);b.setAttribute('aria-pressed',String(enabled));});}
const nodes=documentSettings.nodes||[],tk=JSON.stringify([activeNodeUid,nodes.map(n=>[n.uid,n.label,n.enabled])]);if(tk!==targetSignature){targetSignature=tk;target.replaceChildren();nodes.forEach((n,i)=>{const b=document.createElement('button');b.textContent=String(i+1).padStart(2,'0')+' '+n.label;b.dataset.target=n.uid;b.setAttribute('role','tab');b.setAttribute('aria-selected',String(n.uid===activeNodeUid));b.className=n.uid===activeNodeUid?'active':'';b.title=n.enabled?'Edit '+n.label:n.label+' (disabled)';b.onclick=()=>window.nodeUI.choose(n.uid);b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?nodes.length-1:(i+(e.key==='ArrowRight'?1:-1)+nodes.length)%nodes.length;window.nodeUI.choose(nodes[j].uid);target.querySelector('[aria-selected="true"]')?.focus();};target.append(b);});}
amount.disabled=!img;amount.value=n?.mix??100;output.textContent=amount.value+'%';document.querySelectorAll('.effect-node').forEach(b=>{const node=nodes.find(n=>n.uid===b.dataset.node);const badge=b.querySelector('.node-edits');if(badge&&node?.looks?.some(l=>l.enabled!==false))badge.textContent+=' ✧';});}
// Keep each tool family readable: one expanded section at a time, advanced rows tucked away.
const sections=[...document.querySelectorAll('details[data-toolgroup]')];for(const section of sections){section.open=section.dataset.toolgroup==='light'&&section.contains($('exposure'));section.addEventListener('toggle',()=>{if(!section.open)return;for(const other of sections)if(other!==section&&other.dataset.toolgroup===section.dataset.toolgroup&&!other.closest('.floating-tool')&&!section.closest('.floating-tool'))other.open=false;});}
const advancedKeys=['halationThreshold','halationRadius','halationTight','halationMid','halationWide','diffusionRadius','diffusionScatter','diffusionProtect','flareThreshold','flareWidth','flareAngle','flareGhosts','matteRange','matteSoftness','matteDynamic','grainSize','grainRoughness','grainColor','gradeBalance','gradeBlend'];const bySection=new Map();for(const key of advancedKeys){const row=$(key)?.closest('.slider-row'),parent=row?.closest('details[data-toolgroup]');if(!parent)continue;if(!bySection.has(parent)){const details=document.createElement('details');details.className='fine-controls';details.innerHTML='<summary>Fine controls</summary>';parent.append(details);bySection.set(parent,details);}bySection.get(parent).append(row);}
const oldSetTool=window.advancedUI.setTool;window.advancedUI.setTool=tool=>{oldSetTool(tool);const visible=sections.filter(s=>s.dataset.toolgroup===tool&&!s.hidden);if(visible.length&&!visible.some(s=>s.open))(tool==='frame'?$('crop').closest('details'):visible[0]).open=true;};document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>window.advancedUI.setTool(b.dataset.tool));
window.nodeFlowUI={sync:syncFlow,bindLook,toggleLook,editLook};sync();
})();
