(function(scope){
const defaults={diffusion:0,diffusionMode:0,diffusionRadius:35,diffusionScatter:40,diffusionProtect:75,bloomThreshold:30,bloomKnee:70,bloomTint:'#ffffff',flare:0,flareThreshold:80,flareLength:70,flareWidth:15,flareAngle:0,flareTint:'#79bfff',flareSource:0,flareX:70,flareY:30,flareGhosts:15,matte:0,matteRange:45,matteSoftness:65,matteDynamic:75,matteColor:'#968f87',matteTint:0,cropScale:100,customAspectW:4,customAspectH:5,straighten:0,flipV:false};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const canvasFor=(w,h)=>{const c=typeof document==='undefined'?new OffscreenCanvas(w,h):document.createElement('canvas');c.width=w;c.height=h;return c;};
const rgb=hex=>[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255);
function blur(c,r){const out=canvasFor(c.width,c.height),x=out.getContext('2d');x.filter='blur('+Math.max(.1,r)+'px)';x.drawImage(c,0,0);return out;}
function gateWeight(value,threshold,knee){const t=threshold/100,k=knee/100;if(k<=.00001)return value>t?1:0;const f=clamp((value-t)/k);return f*f*(3-2*f);}
function extract(c,threshold,knee,tint='#ffffff',grayscale=false){const out=canvasFor(c.width,c.height),ctx=out.getContext('2d'),im=c.getContext('2d',{willReadFrequently:true}).getImageData(0,0,c.width,c.height),color=rgb(tint);for(let i=0;i<im.data.length;i+=4){const lum=(im.data[i]*.2126+im.data[i+1]*.7152+im.data[i+2]*.0722)/255,g=gateWeight(lum,threshold,knee);if(grayscale){im.data[i]=im.data[i+1]=im.data[i+2]=g*255;}else{for(let k=0;k<3;k++)im.data[i+k]*=color[k];im.data[i+3]*=g;}}ctx.putImageData(im,0,0);return out;}
function gatePreview(c,s){return extract(c,s.bloomThreshold,s.bloomKnee,'#ffffff',true);}
function bloom(c,s){if(!s.glow)return;const ctx=c.getContext('2d'),light=extract(c,s.bloomThreshold,s.bloomKnee,s.bloomTint);ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=s.glow/100*.9;ctx.drawImage(blur(light,Math.max(c.width,c.height)*(.001+s.glowRadius*.0004)),0,0);ctx.restore();}
function diffusion(c,s){if(!s.diffusion)return;const w=c.width,h=c.height,ctx=c.getContext('2d',{willReadFrequently:true}),original=ctx.getImageData(0,0,w,h);const smooth=blur(c,Math.max(w,h)*(.0004+s.diffusionRadius*.00006)).getContext('2d').getImageData(0,0,w,h),mix=s.diffusion/100;for(let i=0;i<original.data.length;i+=4){const lum=(original.data[i]*.2126+original.data[i+1]*.7152+original.data[i+2]*.0722)/255,protection=1-s.diffusionProtect/100*Math.pow(1-lum,2);const blend=mix*(s.diffusionMode===2?.7:.25)*protection;for(let k=0;k<3;k++){original.data[i+k]+=(smooth.data[i+k]-original.data[i+k])*blend;if(s.diffusionMode===0)original.data[i+k]+=(255-original.data[i+k])*mix*.06*protection;}}ctx.putImageData(original,0,0);if(s.diffusionScatter){const light=extract(c,s.diffusionMode===1?55:30,35);ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=mix*s.diffusionScatter/100*.75;ctx.drawImage(blur(light,Math.max(w,h)*(.004+s.diffusionRadius*.00035)),0,0);ctx.restore();}}
function flare(c,s){if(!s.flare)return;const w=c.width,h=c.height,ctx=c.getContext('2d'),source=canvasFor(128,128),sx=source.getContext('2d',{willReadFrequently:true});sx.drawImage(c,0,0,128,128);const data=sx.getImageData(0,0,128,128).data;const points=[];
if(s.flareSource===1)points.push({x:s.flareX/100*w,y:s.flareY/100*h,power:1});else{const candidates=[];for(let y=1;y<127;y+=2)for(let x=1;x<127;x+=2){const i=(y*128+x)*4,lum=(data[i]*.2126+data[i+1]*.7152+data[i+2]*.0722)/255;if(data[i+3]&&lum>s.flareThreshold/100)candidates.push({x,y,lum});}candidates.sort((a,b)=>b.lum-a.lum);for(const p of candidates){if(points.some(q=>Math.hypot(q.x/w*128-p.x,q.y/h*128-p.y)<18))continue;points.push({x:p.x/128*w,y:p.y/128*h,power:clamp((p.lum-s.flareThreshold/100)/Math.max(.01,1-s.flareThreshold/100))});if(points.length===4)break;}}
const color=rgb(s.flareTint).map(v=>Math.round(v*255)),colorAt=a=>'rgba('+color.join(',')+','+a+')';ctx.save();ctx.globalCompositeOperation='screen';for(const p of points){const amount=s.flare/100*p.power;const length=Math.max(w,h)*(.05+s.flareLength*.008),thickness=Math.max(1,Math.min(w,h)*(.0006+s.flareWidth*.0003));ctx.save();ctx.translate(p.x,p.y);ctx.rotate(s.flareAngle*Math.PI/180);ctx.scale(length,thickness);const g=ctx.createRadialGradient(0,0,0,0,0,1);g.addColorStop(0,colorAt(amount*.95));g.addColorStop(.08,colorAt(amount*.65));g.addColorStop(.4,colorAt(amount*.2));g.addColorStop(1,colorAt(0));ctx.fillStyle=g;ctx.fillRect(-1,-1,2,2);ctx.restore();if(s.flareGhosts){for(let n=1;n<=3;n++){const gx=p.x+(w/2-p.x)*n*.7,gy=p.y+(h/2-p.y)*n*.7,r=Math.min(w,h)*(.015+n*.008);const g=ctx.createRadialGradient(gx,gy,0,gx,gy,r);g.addColorStop(0,colorAt(0));g.addColorStop(.7,colorAt(amount*s.flareGhosts/100*.13));g.addColorStop(1,colorAt(0));ctx.fillStyle=g;ctx.fillRect(gx-r,gy-r,r*2,r*2);}}}ctx.restore();}
function matte(data,w,h,s){if(!s.matte)return;const hist=new Uint32Array(256);let count=0;for(let i=0;i<data.length;i+=16){if(!data[i+3])continue;hist[Math.round(data[i]*.2126+data[i+1]*.7152+data[i+2]*.0722)]++;count++;}let black=0,n=0;for(;black<255;black++){n+=hist[black];if(n>=count*.08)break;}const dynamic=s.matteDynamic/100,target=s.matte/100*.22,baseline=black/255,auto=clamp((.32-baseline)/.32,.15,1),lift=target*((1-dynamic)+dynamic*auto),range=.08+s.matteRange*.007,soft=.5+s.matteSoftness/50,tint=rgb(s.matteColor),tintLum=.2126*tint[0]+.7152*tint[1]+.0722*tint[2];for(let i=0;i<data.length;i+=4){const lum=(data[i]*.2126+data[i+1]*.7152+data[i+2]*.0722)/255,weight=Math.pow(clamp(1-lum/range),soft),amount=lift*weight;for(let k=0;k<3;k++)data[i+k]+=255*amount*(1+(tint[k]-tintLum)*s.matteTint/100*3);}}
const api={defaults,gateWeight,gatePreview,bloom,diffusion,flare,matte};if(typeof module!=='undefined')module.exports=api;else scope.Optics=api;
})(globalThis);
