// Bounded caches: at most 160 MiB of decoded originals and 64 MiB of rendered previews.
const PhotoCache=(()=>{
const sources=new Map(),pending=new Map(),previews=new Map();let sourceBytes=0,previewBytes=0,prefetchTimer;
function touch(map,key,value){map.delete(key);map.set(key,value);}
async function load(id){id=catalog.photos.find(p=>p.id===id)?.sourceId||id;if(sources.has(id)){const item=sources.get(id);touch(sources,id,item);return item.image;}if(pending.has(id))return pending.get(id);const promise=(async()=>{const image=new Image();image.lithPhotoId=id;image.decoding='async';image.src=await api.image(id);await image.decode();const bytes=image.naturalWidth*image.naturalHeight*4;if(bytes<=160*1024*1024){while(sourceBytes+bytes>160*1024*1024||sources.size>=3){const key=sources.keys().next().value;sourceBytes-=sources.get(key).bytes;sources.delete(key);}sources.set(id,{image,bytes});sourceBytes+=bytes;}return image;})();pending.set(id,promise);try{return await promise;}finally{pending.delete(id);}}
function preview(id,key){const item=previews.get(id);if(item?.key!==key)return null;touch(previews,id,item);return item.canvas;}
function rememberPreview(id,key,bitmap){const bytes=bitmap.width*bitmap.height*4;if(bytes>64*1024*1024)return;const previous=previews.get(id);if(previous){previewBytes-=previous.bytes;previews.delete(id);}while(previewBytes+bytes>64*1024*1024||previews.size>=6){const oldest=previews.keys().next().value;previewBytes-=previews.get(oldest).bytes;previews.delete(oldest);}const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);previews.set(id,{key,canvas,bytes});previewBytes+=bytes;}
function prefetch(id){clearTimeout(prefetchTimer);prefetchTimer=setTimeout(()=>{if(current?.id!==id||pending.size)return;const list=visible(),at=list.findIndex(p=>p.id===id),next=list[at+1]||list[at-1];if(next&&!sources.has(next.id))load(next.id).catch(()=>{});},500);}
return {load,preview,rememberPreview,prefetch,stats:()=>({sourceBytes,previewBytes,sources:sources.size,previews:previews.size})};
})();
