(()=>{
'use strict';
const cards=[];let mode=null,stroke=null,target='',last=null;
function card(id,title,description,rows){const c=advancedUI.section(title,'effects',rows);c.id=id;c.open=false;c.dataset.effectFamily='creative';c.classList.add('creative-card');const text=document.createElement('p');text.className='creative-help';text.textContent=description;c.querySelector('summary').after(text);cards.push(c);return c;}
function color(c,id,label){const row=document.createElement('label');row.className='color-row';row.textContent=label;const input=document.createElement('input');input.type='color';input.id=id;input.setAttribute('aria-label',label);input.onchange=()=>{if(img)mutate(()=>settings[id]=input.value);};row.append(input);c.append(row);}
function button(c,id,label,fn){const b=document.createElement('button');b.id=id;b.type='button';b.textContent=label;b.onclick=fn;c.append(b);return b;}
function more(c,title,keys){const el=document.createElement('details'),summary=document.createElement('summary');summary.textContent=title;el.append(summary);for(const key of keys)el.append($(key).closest('.slider-row'));c.append(el);}
function reset(c){button(c,c.id+'Reset','Reset this effect',()=>{if(img)mutate(()=>{for(const input of c.querySelectorAll('input[id],select[id]'))if(Object.hasOwn(Imaging.defaults,input.id))settings[input.id]=structuredClone(Imaging.defaults[input.id]);});});}
function hidden(c,id){const e=document.createElement('input');e.type='hidden';e.id=id;c.append(e);}
function finish(){if(stroke){stroke=null;render();save();}last=null;}
function cancel(){finish();mode=null;target='';$('stage').classList.remove('placing-light');sync();}
function begin(value){if(!img)return;if(mode===value){cancel();return;}finish();if($('reviewMode').value!=='edited'){$('reviewMode').value='edited';$('reviewMode').dispatchEvent(new Event('change'));}mode=value;target=current.id+':'+activeNodeUid;$('stage').classList.add('placing-light');sync();toast(value==='bokeh'?'Paint or click to place bokeh. Escape finishes.':value==='relight'?'Click to place a soft light. Escape finishes.':'Click the photo to set the center.');}
const shutter=card('shutterCard','Shutter drag','Stretch the scene into directional motion while protecting a soft area around your subject.',[['shutter','Strength',0,100,1],['shutterLength','Trail length',0,100,1],['shutterAngle','Direction',-180,180,1],['shutterProtect','Keep subject sharp',0,100,1],['shutterX','Subject · horizontal',0,100,1],['shutterY','Subject · vertical',0,100,1]]);button(shutter,'placeShutter','⌖ Place sharp area',()=>begin('shutter'));more(shutter,'Fine positioning',['shutterX','shutterY']);reset(shutter);
const fish=card('fisheyeCard','Fisheye lens','Bend the scene around a movable lens center. A creative lens simulation, not a camera correction.',[['fisheye','Lens strength',0,100,1],['fisheyeX','Lens center · horizontal',0,100,1],['fisheyeY','Lens center · vertical',0,100,1]]);button(fish,'placeFisheye','⌖ Place lens center',()=>begin('fisheye'));more(fish,'Fine positioning',['fisheyeX','fisheyeY']);reset(fish);
const bleed=card('bleedCard','Color bleeding','Spread color across nearby edges while retaining the original brightness detail.',[['colorBleed','Strength',0,100,1],['bleedRadius','Color spread',0,100,1]]);reset(bleed);
const leak=card('leakCard','Darkroom light leaks','Place a soft, elongated wash of colored light. Start at an edge for a light-fogged film feel.',[['lightLeak','Strength',0,100,1],['leakSize','Spread',1,100,1],['leakAngle','Direction',-180,180,1],['leakX','Position · horizontal',0,100,1],['leakY','Position · vertical',0,100,1]]);color(leak,'leakColor','Leak color');button(leak,'placeLeak','⌖ Place light leak',()=>begin('lightLeak'));more(leak,'Fine positioning',['leakX','leakY']);reset(leak);
const bokeh=card('bokehCard','Bokeh painter','Paint luminous discs onto the photo. Positions belong to this node; Undo removes the last stroke.',[['bokeh','Strength',0,100,1],['bokehSize','Disc size',1,40,1],['bokehSoftness','Soft edges',0,100,1]]);color(bokeh,'bokehColor','Bokeh color');const shape=document.createElement('label');shape.className='select-row';shape.textContent='Aperture shape';const choose=document.createElement('select');choose.id='bokehShape';choose.append(new Option('Round','0'),new Option('Hexagonal','1'));choose.onchange=()=>{if(img)mutate(()=>settings.bokehShape=Number(choose.value));};shape.append(choose);bokeh.append(shape);hidden(bokeh,'bokehPoints');button(bokeh,'paintBokeh','✦ Paint bokeh',()=>begin('bokeh'));button(bokeh,'undoBokehPoint','Remove last disc',()=>{if(img)mutate(()=>settings.bokehPoints=(settings.bokehPoints||[]).slice(0,-1));});reset(bokeh);
const light=card('relightCard','Artificial light placement','Click to add soft, colored pools of light. This is a creative overlay; it does not infer depth or cast physical shadows.',[['relight','Strength',0,100,1],['relightSize','Light spread',1,100,1]]);color(light,'relightColor','Light color');hidden(light,'relightPoints');button(light,'placeRelight','☀ Place lights',()=>begin('relight'));button(light,'undoRelightPoint','Remove last light',()=>{if(img)mutate(()=>settings.relightPoints=(settings.relightPoints||[]).slice(0,-1));});reset(light);
const status=document.createElement('p');status.id='placementStatus';status.className='creative-help';status.setAttribute('role','status');const done=document.createElement('button');done.id='finishPlacement';done.textContent='Done placing · Esc';done.onclick=cancel;
function sync(){if(mode&&(!img||target!==current?.id+':'+activeNodeUid||document.querySelector('[data-tool].active')?.dataset.tool!=='effects')){mode=null;stroke=null;last=null;$('stage').classList.remove('placing-light');}for(const c of cards){for(const e of c.querySelectorAll('button,input,select'))e.disabled=!img;c.classList.toggle('creative-modified',[...c.querySelectorAll('input[id],select[id]')].some(e=>JSON.stringify(settings[e.id])!==JSON.stringify(Imaging.defaults[e.id])));}for(const [id,value]of [['paintBokeh','bokeh'],['placeRelight','relight'],['placeShutter','shutter'],['placeFisheye','fisheye'],['placeLeak','lightLeak']])$(id).setAttribute('aria-pressed',String(mode===value));$('undoBokehPoint').disabled=!img||!(settings.bokehPoints||[]).length;$('undoRelightPoint').disabled=!img||!(settings.relightPoints||[]).length;status.hidden=done.hidden=!mode;if(mode){const c={bokeh,relight:light,shutter,fisheye:fish,lightLeak:leak}[mode];c.append(status,done);status.textContent=mode==='bokeh'?(settings.bokehPoints||[]).length+' / 160 discs · paint on the photo':mode==='relight'?(settings.relightPoints||[]).length+' / 16 lights · click on the photo':'Click the photo to place the center.';}}
function point(e){const r=$('photo').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)return null;return {x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};}
function add(p){const key=mode==='bokeh'?'bokehPoints':'relightPoints',points=settings[key]||[],limit=mode==='bokeh'?160:16;if(points.length>=limit)return;if(last&&Math.hypot(p.x-last.x,p.y-last.y)<settings.bokehSize/100*.45)return;settings[key]=[...points,{...p,size:.65+((points.length*37+11)%83)/100,strength:1}];if(!settings[mode])settings[mode]=65;last=p;scheduleRender();sync();}
$('stage').addEventListener('pointerdown',e=>{if(!mode||!img||e.button!==0)return;const p=point(e);if(!p)return;e.preventDefault();e.stopImmediatePropagation();if(['bokeh','relight'].includes(mode)){const key=mode==='bokeh'?'bokehPoints':'relightPoints',limit=mode==='bokeh'?160:16;if((settings[key]||[]).length>=limit){toast('Placement limit reached. Remove a light or start another node.');return;}pushHistory();stroke=e.pointerId;last=null;add(p);$('stage').setPointerCapture(e.pointerId);}else{const keys={shutter:['shutterX','shutterY'],fisheye:['fisheyeX','fisheyeY'],lightLeak:['leakX','leakY']}[mode];mutate(()=>{settings[keys[0]]=p.x*100;settings[keys[1]]=p.y*100;if(!settings[mode])settings[mode]=50;});cancel();}},true);
$('stage').addEventListener('pointermove',e=>{if(stroke!==e.pointerId)return;e.preventDefault();e.stopImmediatePropagation();if(mode==='bokeh'){const p=point(e);if(p)add(p);}},true);
for(const name of ['pointerup','pointercancel','lostpointercapture'])$('stage').addEventListener(name,e=>{if(stroke!==e.pointerId)return;e.stopImmediatePropagation();finish();},true);
document.addEventListener('keydown',e=>{if(mode&&e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();cancel();}},true);
document.addEventListener('click',e=>{if(mode&&e.target.closest('[data-effect-family-button]')?.dataset.effectFamilyButton!=='creative'&&e.target.closest('[data-effect-family-button]'))cancel();});
const originalSync=creativeUI.sync;creativeUI.sync=()=>{originalSync();sync();};window.playfulUI={cancel,sync};sync();
})();
