(function(scope){
'use strict';
const defaults={shutter:0,shutterLength:30,shutterAngle:0,shutterProtect:30,shutterX:50,shutterY:50,fisheye:0,fisheyeX:50,fisheyeY:50,colorBleed:0,bleedRadius:25,lightLeak:0,leakX:0,leakY:50,leakSize:55,leakAngle:0,leakColor:'#ff853c',bokeh:0,bokehSize:6,bokehSoftness:35,bokehShape:0,bokehColor:'#ffe2a6',bokehPoints:[],relight:0,relightSize:40,relightColor:'#ffe4b8',relightPoints:[]};
const ranges={shutter:[0,100],shutterLength:[0,100],shutterAngle:[-180,180],shutterProtect:[0,100],shutterX:[0,100],shutterY:[0,100],fisheye:[0,100],fisheyeX:[0,100],fisheyeY:[0,100],colorBleed:[0,100],bleedRadius:[0,100],lightLeak:[0,100],leakX:[0,100],leakY:[0,100],leakSize:[1,100],leakAngle:[-180,180],bokeh:[0,100],bokehSize:[1,40],bokehSoftness:[0,100],bokehShape:[0,1],relight:[0,100],relightSize:[1,100]};
const types=['shutter','fisheye','colorBleed','lightLeak','bokeh','relight'];
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const rgb=c=>/^#[a-f\d]{6}$/i.test(c)?[1,3,5].map(i=>parseInt(c.slice(i,i+2),16)/255):[1,1,1];
function active(p){return types.some(k=>p[k]>0);}
function sample(d,w,h,x,y,k){x=clamp(x,0,w-1);y=clamp(y,0,h-1);const a=Math.floor(x),b=Math.floor(y),u=x-a,v=y-b,c=Math.min(w-1,a+1),e=Math.min(h-1,b+1);return (d[(b*w+a)*4+k]*(1-u)+d[(b*w+c)*4+k]*u)*(1-v)+(d[(e*w+a)*4+k]*(1-u)+d[(e*w+c)*4+k]*u)*v;}
// Sliding sums along integer rays: linear pixel cost rather than samples per pixel.
function motion(d,w,h,p){const angle=p.shutterAngle*Math.PI/180,dx=Math.cos(angle),dy=Math.sin(angle),vertical=Math.abs(dy)>Math.abs(dx),major=vertical?h:w,minor=vertical?w:h,slope=vertical?dx/dy:dy/dx,r=Math.round(Math.min(w,h)*.002*p.shutterLength*Math.max(Math.abs(dx),Math.abs(dy)));if(!r)return;
 const src=d.slice(),pad=Math.ceil(Math.abs(slope)*major),n=2*r+1,mix=p.shutter/100,protect=p.shutterProtect/100*.5;
 const at=(t,line)=>{const a=clamp(t,0,major-1),b=clamp(line+Math.round(slope*t),0,minor-1);return (vertical?a*w+b:b*w+a)*4;};
 for(let line=-pad;line<minor+pad;line++){const start=Math.max(0,slope>0?Math.ceil(-line/slope):slope<0?Math.ceil((minor-1-line)/slope):0),end=Math.min(major-1,slope>0?Math.floor((minor-1-line)/slope):slope<0?Math.floor(-line/slope):major-1);if(start>end)continue;const sum=[0,0,0];for(let t=start-r;t<=start+r;t++){const i=at(t,line);for(let k=0;k<3;k++)sum[k]+=src[i+k];}
 for(let a=start;a<=end;a++){const b=line+Math.round(slope*a);if(b>=0&&b<minor){const x=vertical?b:a,y=vertical?a:b,i=(y*w+x)*4,dist=Math.hypot((x/w-p.shutterX/100)*w/Math.min(w,h),(y/h-p.shutterY/100)*h/Math.min(w,h)),gate=protect?clamp((dist-protect)/.15):1,amount=mix*gate*gate*(3-2*gate);for(let k=0;k<3;k++)d[i+k]=src[i+k]+(sum[k]/n-src[i+k])*amount;}
 const add=at(a+r+1,line),sub=at(a-r,line);for(let k=0;k<3;k++)sum[k]+=src[add+k]-src[sub+k];}}
}
function warp(d,w,h,p){const src=d.slice(),cx=p.fisheyeX/100*(w-1),cy=p.fisheyeY/100*(h-1),scale=Math.max(w,h)/2,amount=p.fisheye/100*1.8;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const dx=(x-cx)/scale,dy=(y-cy)/scale,r=Math.hypot(dx,dy),factor=r?Math.atan(amount*r)/(amount*r):1,i=(y*w+x)*4;for(let k=0;k<4;k++)d[i+k]=sample(src,w,h,cx+dx*scale*factor,cy+dy*scale*factor,k);}}
function box(src,w,h,r,vertical){const out=new Float32Array(src.length),major=vertical?h:w,minor=vertical?w:h,n=r*2+1;for(let b=0;b<minor;b++){const sums=[0,0,0],at=a=>(vertical?clamp(a,0,major-1)*w+b:b*w+clamp(a,0,major-1))*4;for(let a=-r;a<=r;a++){const i=at(a);for(let k=0;k<3;k++)sums[k]+=src[i+k];}for(let a=0;a<major;a++){const i=at(a);for(let k=0;k<3;k++)out[i+k]=sums[k]/n;out[i+3]=src[i+3];const add=at(a+r+1),sub=at(a-r);for(let k=0;k<3;k++)sums[k]+=src[add+k]-src[sub+k];}}return out;}
function bleed(d,w,h,p){const r=Math.max(1,Math.round(Math.min(w,h)*p.bleedRadius*.0008)),blur=box(box(d,w,h,r,false),w,h,r,true),mix=p.colorBleed/100;for(let i=0;i<d.length;i+=4){const lum=d[i]*.2126+d[i+1]*.7152+d[i+2]*.0722,blurLum=blur[i]*.2126+blur[i+1]*.7152+blur[i+2]*.0722;for(let k=0;k<3;k++)d[i+k]+=(lum+blur[i+k]-blurLum-d[i+k])*mix;}}
// Screen-style exposure preserves alpha and does not force float highlights to 8-bit.
function lightPixel(d,i,color,amount){for(let k=0;k<3;k++)d[i+k]+=Math.max(0,255-d[i+k])*clamp(color[k]*amount);}
function leak(d,w,h,p){const color=rgb(p.leakColor),cx=p.leakX/100*w,cy=p.leakY/100*h,size=Math.max(1,Math.min(w,h)*p.leakSize/100),a=p.leakAngle*Math.PI/180,c=Math.cos(a),s=Math.sin(a);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const dx=x-cx,dy=y-cy,u=(dx*c+dy*s)/size,v=(-dx*s+dy*c)/(size*1.8),weight=Math.exp(-3*(u*u+v*v))*p.lightLeak/100;lightPixel(d,(y*w+x)*4,color,weight);}}
function spots(d,w,h,p,bokeh){const points=(bokeh?p.bokehPoints:p.relightPoints)||[],color=rgb(bokeh?p.bokehColor:p.relightColor),size=(bokeh?p.bokehSize:p.relightSize)/100*Math.min(w,h),strength=(bokeh?p.bokeh:p.relight)/100;
 for(const point of points.slice(0,bokeh?160:16)){const cx=point.x*w,cy=point.y*h,r=Math.max(1,size*(point.size??1)),bound=bokeh?r:r*2;for(let y=Math.max(0,Math.floor(cy-bound));y<Math.min(h,Math.ceil(cy+bound));y++)for(let x=Math.max(0,Math.floor(cx-bound));x<Math.min(w,Math.ceil(cx+bound));x++){const dx=(x-cx)/r,dy=(y-cy)/r,dist=Math.hypot(dx,dy);let weight;
 if(bokeh){let edge=dist;if(p.bokehShape===1){const angle=Math.atan2(dy,dx),sector=((angle%(Math.PI/3))+Math.PI/3)%(Math.PI/3)-Math.PI/6;edge=dist*Math.cos(sector)/Math.cos(Math.PI/6);}const softness=Math.max(.02,p.bokehSoftness/100);weight=clamp((1-edge)/softness);weight=weight*weight*(3-2*weight)*(.65+.35*clamp(edge));}else weight=Math.exp(-2.5*dist*dist);
 lightPixel(d,(y*w+x)*4,color,weight*strength*(point.strength??1));}}}
function apply(d,w,h,p,type=null){if((!type||type==='shutter')&&p.shutter>0)motion(d,w,h,p);if((!type||type==='fisheye')&&p.fisheye>0)warp(d,w,h,p);if((!type||type==='colorBleed')&&p.colorBleed>0)bleed(d,w,h,p);if((!type||type==='lightLeak')&&p.lightLeak>0)leak(d,w,h,p);if((!type||type==='bokeh')&&p.bokeh>0)spots(d,w,h,p,true);if((!type||type==='relight')&&p.relight>0)spots(d,w,h,p,false);}
const api={defaults,ranges,types,active,apply};if(typeof module!=='undefined')module.exports=api;else scope.Playful=api;
})(globalThis);
