(function(scope){
const FX=typeof module!=="undefined"?require("./effects.js"):scope.FX;
const TextFX=typeof module!=="undefined"?require("./text-effects.js"):scope.TextFX;
const defaults={textLayers:[],developMix:100,exposure:0,contrast:0,highlights:0,shadows:0,temperature:0,tint:0,saturation:0,vibrance:0,fade:0,grain:0,glow:0,halation:0,rotation:0,flip:false,crop:0,cropX:50,cropY:50,masks:[],...FX.extraDefaults};
const canvasFor=(w,h)=>{const c=typeof document==='undefined'?new OffscreenCanvas(w,h):document.createElement('canvas');c.width=w;c.height=h;return c;};
function pixels(data,input){const s={...defaults,...input},exposure=2**s.exposure,contrast=1+s.contrast/100,fade=s.fade/100;for(let i=0;i<data.length;i+=4){let r=data[i]/255,g=data[i+1]/255,b=data[i+2]/255;const lum=.2126*r+.7152*g+.0722*b,low=1-lum;const tone=s.shadows*.0042*low*low+s.highlights*.0042*lum*lum;r=(r*exposure+tone-.5)*contrast+.5+s.temperature*.0011+s.tint*.00035;g=(g*exposure+tone-.5)*contrast+.5-s.tint*.00065;b=(b*exposure+tone-.5)*contrast+.5-s.temperature*.0011+s.tint*.00035;const gray=.2126*r+.7152*g+.0722*b,spread=Math.max(r,g,b)-Math.min(r,g,b),sat=1+s.saturation/100+s.vibrance/100*(1-Math.min(1,spread));data[i]=((gray+(r-gray)*sat)*(1-fade*.22)+fade*.07)*255;data[i+1]=((gray+(g-gray)*sat)*(1-fade*.22)+fade*.07)*255;data[i+2]=((gray+(b-gray)*sat)*(1-fade*.22)+fade*.07)*255;}return data;}
function geometry(w,h,s,max=0){const rotated=s.rotation%180!==0;const rw=rotated?h:w,rh=rotated?w:h,angle=Math.abs(s.straighten||0)*Math.PI/180,safe=1/(Math.cos(angle)+Math.max(rw/rh,rh/rw)*Math.sin(angle));const sw=rw*safe,sh=rh*safe;let cw=sw,ch=sh;const ratio=s.crop===-1?Math.max(.01,(s.customAspectW||4)/(s.customAspectH||5)):s.crop;if(ratio>0){if(sw/sh>ratio)cw=sh*ratio;else ch=sw/ratio;}const cropScale=Math.max(.01,Math.min(1,(s.cropScale??100)/100));cw*=cropScale;ch*=cropScale;const x=(rw-sw)/2+(sw-cw)*s.cropX/100,y=(rh-sh)/2+(sh-ch)*s.cropY/100,scale=max?Math.min(1,max/Math.max(cw,ch)):1;return {rw,rh,cw,ch,x,y,width:Math.max(1,Math.round(cw*scale)),height:Math.max(1,Math.round(ch*scale))};}

function transform(ctx,w,h,s,g){ctx.scale(g.width/g.cw,g.height/g.ch);ctx.translate(-g.x,-g.y);ctx.translate(g.rw/2,g.rh/2);ctx.rotate((s.rotation+(s.straighten||0))*Math.PI/180);ctx.scale(s.flip?-1:1,s.flipV?-1:1);ctx.translate(-w/2,-h/2);}
function sourcePoint(x,y,w,h,s){const g=geometry(w,h,s),a=(s.rotation+(s.straighten||0))*Math.PI/180,dx=g.x+x*g.cw-g.rw/2,dy=g.y+y*g.ch-g.rh/2;return {x:((dx*Math.cos(a)+dy*Math.sin(a))*(s.flip?-1:1)+w/2)/w,y:((-dx*Math.sin(a)+dy*Math.cos(a))*(s.flipV?-1:1)+h/2)/h};}
function colorMask(mask,data){const c=canvasFor(data.width,data.height),ctx=c.getContext('2d'),out=ctx.createImageData(c.width,c.height);const rgb=mask.color||'#e0a060',target=[1,3,5].map(i=>parseInt(rgb.slice(i,i+2),16)/255);function hue(r,g,b){const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;return {h:d?((max===r?(g-b)/d+(g<b?6:0):max===g?(b-r)/d+2:(r-g)/d+4)*60):0,s:max?d/max:0,l:(max+min)/2};}const t=hue(...target),range=(mask.tolerance??25),soft=Math.max(1,(mask.feather??65)/100*range);for(let i=0;i<data.data.length;i+=4){const v=hue(data.data[i]/255,data.data[i+1]/255,data.data[i+2]/255);let d=Math.abs(v.h-t.h);d=Math.min(d,360-d);if(t.s<.12)d=Math.abs(v.l-t.l)*180;let a=Math.max(0,Math.min(1,(range-d)/soft));if(v.s<(mask.minSaturation||0)/100||v.l<(mask.minLuma||0)/100||v.l>(mask.maxLuma??100)/100)a=0;if(mask.invert)a=1-a;out.data[i]=out.data[i+1]=out.data[i+2]=255;out.data[i+3]=a*data.data[i+3];}ctx.putImageData(out,0,0);return c;}
function maskForImage(img,mask,s,max){if(mask.components?.length||mask.combinedInvert){const root={...mask,components:undefined,combinedInvert:false},out=maskForImage(img,root,s,max),ctx=out.getContext('2d');for(const part of mask.components||[]){if(part.enabled===false)continue;const layer=maskForImage(img,{...part,components:undefined,combinedInvert:false},s,max);ctx.globalCompositeOperation=part.combine==='subtract'?'destination-out':part.combine==='intersect'?'destination-in':'source-over';ctx.drawImage(layer,0,0);}if(mask.combinedInvert){ctx.globalCompositeOperation='source-out';ctx.fillStyle='white';ctx.fillRect(0,0,out.width,out.height);}ctx.globalCompositeOperation='source-over';return out;}return mask.type==='color'?colorMask(mask,base(img,s,max).data):maskCanvas(mask,img.naturalWidth||img.width,img.naturalHeight||img.height,s,max);}
function maskCanvas(mask,w,h,s,max){const g=geometry(w,h,s,max),c=canvasFor(g.width,g.height),ctx=c.getContext('2d',{willReadFrequently:true});transform(ctx,w,h,s,g);const f=Math.max(.01,Math.min(1,(mask.feather??65)/100));if(mask.type==='brush'){for(const stroke of mask.strokes||[]){ctx.globalCompositeOperation=stroke.erase?'destination-out':'source-over';const radius=stroke.size*Math.min(w,h);const stamp=p=>{const gradient=ctx.createRadialGradient(p.x*w,p.y*h,radius*(1-f),p.x*w,p.y*h,radius);gradient.addColorStop(0,'white');gradient.addColorStop(1,'#ffffff00');ctx.fillStyle=gradient;ctx.fillRect(p.x*w-radius,p.y*h-radius,radius*2,radius*2);};for(let i=0;i<stroke.points.length;i++){const p=stroke.points[i],last=stroke.points[i-1];if(last){const n=Math.ceil(Math.hypot((p.x-last.x)*w,(p.y-last.y)*h)/Math.max(1,radius*.25));for(let k=1;k<n;k++)stamp({x:last.x+(p.x-last.x)*k/n,y:last.y+(p.y-last.y)*k/n});}stamp(p);}}}else if(mask.start&&mask.end){const a=mask.start,b=mask.end;if(mask.type==='linear'){if(Math.hypot(a.x-b.x,a.y-b.y)>.0001){const gradient=ctx.createLinearGradient(a.x*w,a.y*h,b.x*w,b.y*h);gradient.addColorStop(.5-f/2,'white');gradient.addColorStop(.5+f/2,'#ffffff00');ctx.fillStyle=gradient;ctx.fillRect(0,0,w,h);}}else{const rx=Math.max(.001,Math.abs(a.x-b.x))*w,ry=Math.max(.001,Math.abs(a.y-b.y))*h;ctx.save();ctx.translate(a.x*w,a.y*h);ctx.scale(rx,ry);const gradient=ctx.createRadialGradient(0,0,1-f,0,0,1);gradient.addColorStop(0,'white');gradient.addColorStop(1,'#ffffff00');ctx.fillStyle=gradient;ctx.fillRect(-1,-1,2,2);ctx.restore();}}ctx.setTransform(1,0,0,1,0,0);if(mask.invert){ctx.globalCompositeOperation='source-out';ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);}return c;}
const baseCache=new WeakMap();
function base(img,s,max){const w=img.naturalWidth||img.width,h=img.naturalHeight||img.height,key=JSON.stringify([max,s.rotation,s.straighten,s.flip,s.flipV,s.crop,s.cropX,s.cropY,s.cropScale,s.customAspectW,s.customAspectH]);let cache=baseCache.get(img);if(!cache){cache=new Map();baseCache.set(img,cache);}if(cache.has(key))return cache.get(key);const g=geometry(w,h,s,max),c=canvasFor(g.width,g.height),ctx=c.getContext('2d',{willReadFrequently:true});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';transform(ctx,w,h,s,g);ctx.drawImage(img,0,0);ctx.setTransform(1,0,0,1,0,0);const result={g,data:ctx.getImageData(0,0,c.width,c.height)};if(cache.size>=3)cache.delete(cache.keys().next().value);cache.set(key,result);return result;}
const compositionKeys=['rotation','straighten','flip','flipV','crop','cropX','cropY','cropScale','customAspectW','customAspectH','border','borderBottom','borderColor'];
function normalizeOld(raw={}){if(raw._schema===4)return structuredClone({...defaults,...raw});if(Array.isArray(raw.nodes)){const result=structuredClone(defaults);for(const key of compositionKeys)result[key]=raw[key]??defaults[key];result.nodes=raw.nodes.map((node,i)=>({uid:'legacy-'+i+'-'+node.id,label:FX.nodeTypes.find(t=>t[0]===node.id)?.[1]||'Adjustment '+(i+1),operation:node.id,enabled:node.enabled!==false,adjustments:{...structuredClone(defaults),...structuredClone(raw),nodes:[]}}));return result;}return structuredClone({...defaults,...raw,_schema:4,nodes:[]});}
function newNode(label='Node 1'){return {uid:globalThis.crypto.randomUUID(),label,operation:'develop',enabled:true,mix:100,adjustments:structuredClone(defaults),looks:[],frame:{}};}
function normalizeSettings(raw={}){if(raw._schema===6){const result=structuredClone({...defaults,...raw});if(!result.nodes.length)result.nodes=[newNode()];return result;}const old=normalizeOld(raw),result=structuredClone(defaults);result._schema=6;result.nodes=[];const nonFrame=Object.keys(defaults).filter(k=>!compositionKeys.includes(k)&&!['nodes','_schema'].includes(k));if(!old.nodes.length||nonFrame.some(k=>JSON.stringify(old[k])!==JSON.stringify(defaults[k]))){const n=newNode();n.adjustments=structuredClone(old);n.adjustments.nodes=[];n.mix=old.developMix??100;n.adjustments.developMix=100;result.nodes.push(n);}for(const previous of old.nodes){const n=newNode(previous.label);n.uid=previous.uid;n.enabled=previous.enabled;n.legacyStage=structuredClone(previous);result.nodes.push(n);}if(!result.nodes.length)result.nodes=[newNode()];for(const k of compositionKeys){result[k]=old[k];result.nodes[0].frame[k]=old[k];}return result;}
function resolveFrame(s){if(s._schema!==6)return s;for(const k of compositionKeys)s[k]=defaults[k];for(const n of s.nodes||[])if(n.enabled!==false)Object.assign(s,n.frame||{});return s;}
function render(img,input,max=0,original=false){const s=original?structuredClone(defaults):{...defaults,...input};const w=img.naturalWidth||img.width,h=img.naturalHeight||img.height,{g,data}=base(img,s,max),canvas=canvasFor(g.width,g.height),ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.putImageData(data,0,0);if(original)return canvas;
const modify=fn=>{const im=ctx.getImageData(0,0,g.width,g.height);fn(im.data);ctx.putImageData(im,0,0);};
function run(operation,p){switch(operation){
case 'diffusion':FX.Optics.diffusion(canvas,p);break;
case 'glow':if(input.previewGate)ctx.drawImage(FX.Optics.gatePreview(canvas,p),0,0);else FX.Optics.bloom(canvas,p);break;
case 'flare':FX.Optics.flare(canvas,p);break;
case 'halation':FX.bloom(canvas,{...p,diffusion:0,glow:0,flare:0});break;
case 'grain':case 'fade':case 'matte':modify(d=>FX.film(d,g.width,g.height,{...p,grain:operation==='grain'?p.grain:0,fade:operation==='fade'?p.fade:0,matte:operation==='matte'?p.matte:0},g.cw,g.ch));break;
case 'light':{const tonal=['exposure','contrast','highlights','shadows','temperature','tint','saturation','vibrance'].some(k=>p[k]);const curve=['curveBlack','curveShadow','curveMid','curveHighlight','curveWhite'].some(k=>p[k]);if(tonal||curve)modify(d=>{if(tonal)pixels(d,{...p,fade:0});if(curve)FX.curves(d,p);});break;}
case 'color':if(FX.colorBands.some(([n])=>p['hsl'+n+'Hue']||p['hsl'+n+'Sat']||p['hsl'+n+'Lum']))modify(d=>FX.hsl(d,p));break;
case 'grade':if(p.gradeShadows||p.gradeMidtones||p.gradeHighlights||p.gradeGlobal)modify(d=>FX.grade(d,p));break;
case 'detail':FX.detail(canvas,p);break;
case 'masks':for(const mask of p.masks||[]){if(mask.enabled===false)continue;const alpha=maskForImage(img,mask,s,max).getContext('2d',{willReadFrequently:true}).getImageData(0,0,g.width,g.height).data;modify(d=>{const local=new Uint8ClampedArray(d);pixels(local,mask.adjustments||{});for(let i=0;i<local.length;i+=4){const a=alpha[i+3]/255;for(let k=0;k<3;k++)d[i+k]+=(local[i+k]-d[i+k])*a;}});}break;
case 'bloom':if(input.previewGate){const gate=FX.Optics.gatePreview(canvas,p);ctx.drawImage(gate,0,0);}else FX.bloom(canvas,p);break;
case 'film':if(p.fade||p.grain||p.matte)modify(d=>FX.film(d,g.width,g.height,p,g.cw,g.ch));break;
case 'vignette':if(p.vignette)modify(d=>FX.vignette(d,g.width,g.height,p));break;
}}
function blend(amount,action){amount=Math.max(0,Math.min(100,amount??100));if(!amount)return false;const before=amount<100?ctx.getImageData(0,0,g.width,g.height):null;const gate=action();if(before&&!gate){const after=ctx.getImageData(0,0,g.width,g.height);for(let i=0;i<after.data.length;i++)after.data[i]=before.data[i]+(after.data[i]-before.data[i])*amount/100;ctx.putImageData(after,0,0);}return gate;}
function chain(operation,p,uid){const ops=operation==='develop'?FX.nodeTypes.map(t=>t[0]):[operation];for(const op of ops){const showGate=input.previewGate&&(input.gateTarget||null)===(uid||null)&&['bloom','glow'].includes(op);const beforeGate=input.previewGate;input.previewGate=showGate;run(op,p);input.previewGate=beforeGate;if(showGate)return true;}return false;}
if(blend(s.developMix,()=>chain('develop',s,null)))return FX.border(canvas,s,max);
function stage(node,uid){const p={...defaults,...node.adjustments};return blend(node.mix,()=>{if(node.legacyStage)stage(node.legacyStage,uid);for(const effect of node.operations||[{type:node.operation||'develop',mix:100}])if(blend(effect.mix,()=>chain(effect.type,p,uid)))return true;for(const look of node.looks||[])if(look.enabled!==false)blend(look.amount,()=>{if(look.values?.recipeNodes){for(const part of look.values.recipeNodes)if(part.enabled!==false)stage(part,'recipe-'+look.id);}else chain('develop',{...defaults,...look.values},'look-'+look.id);return false;});return false;});}
for(const node of s.nodes||[]){if(node.enabled!==false&&stage(node,node.uid))break;}
return TextFX.render(FX.border(canvas,s,max),s);}

const api={defaults,compositionKeys,newNode,resolveFrame,normalizeSettings,pixels,geometry,sourcePoint,maskCanvas,maskForImage,render};if(typeof module!=='undefined')module.exports=api;else scope.Imaging=api;
})(globalThis);
