(()=>{
const panel=document.createElement('section');panel.id='projectPanel';panel.innerHTML='<div class="section-title">PROJECT <button id="newProject" title="Create project">＋ New</button></div><label class="project-picker"><select id="projectPicker" aria-label="Current project"></select><button id="projectSettings" title="Project settings" aria-label="Project settings">⚙</button></label><p id="projectSummary" class="small muted"></p>';
document.querySelector('.left').prepend(panel);
const dialog=document.createElement('dialog');dialog.id='projectDialog';dialog.innerHTML='<form id="projectForm"><div class="dialog-top"><strong id="projectDialogTitle">Project settings</strong><button type="button" id="closeProject" aria-label="Close project settings">✕</button></div><label>Project name<input id="projectName" required maxlength="60" placeholder="Weekend in the city"></label><label>Notes<textarea id="projectNotes" maxlength="2000" rows="3" placeholder="Ideas for this collection"></textarea></label><p class="small muted">Photos and edits stay in this project. Custom looks are shared across projects.</p><fieldset id="projectExportSettings"><legend>Default export</legend><label>Format<select id="projectFormat"><option value="jpeg">JPEG</option><option value="png">PNG</option><option value="webp">WebP</option></select></label><label>Quality<input id="projectQuality" type="number" min="10" max="100" value="100"></label><label>Longest edge<select id="projectSize"><option value="0">Original resolution</option><option value="3840">3840 px</option><option value="2048">2048 px</option><option value="1080">1080 px</option></select></label></fieldset><button class="primary" id="saveProject">Save project</button></form>';document.body.append(dialog);
const move=document.createElement('button');move.id='moveToProject';move.textContent='Move to project';move.title='Move the current photo and all its edits to another project';$('favorite').before(move);
const moveDialog=document.createElement('dialog');moveDialog.id='moveProjectDialog';moveDialog.innerHTML='<form id="moveProjectForm"><div class="dialog-top"><strong>Move photo to project</strong><button type="button" id="cancelMoveProject">✕</button></div><label>Destination<select id="moveProjectTarget"></select></label><p class="muted small">Your original, edits, nodes and rating move together.</p><button class="primary">Move photo</button></form>';document.body.append(moveDialog);
let creating=false,busy=false;
const active=()=>catalog.projects?.find(p=>p.id===catalog.activeProjectId);
function syncProjects(){const p=active();if(!p)return;const picker=$('projectPicker');if(picker.dataset.options!==JSON.stringify(catalog.projects.map(p=>[p.id,p.name]))){picker.replaceChildren(...catalog.projects.map(p=>new Option(p.name,p.id)));picker.dataset.options=JSON.stringify(catalog.projects.map(p=>[p.id,p.name]));}picker.value=p.id;picker.disabled=busy;$('newProject').disabled=busy;$('projectSettings').disabled=busy;move.disabled=busy||!current||catalog.projects.length<2;$('projectSummary').textContent=projectPhotos().length+' photos · Saved locally';const s=p.settings;$('exportFormat').value=s.format;$('quality').value=s.quality;$('qualityValue').textContent=s.quality+'%';$('quality').disabled=s.format==='png';$('exportSize').value=s.size;}
async function transition(action){if(busy)return;busy=true;syncProjects();try{await flush();++selection;clearTimeout(settleTimer);if(renderTimer){cancelAnimationFrame(renderTimer);renderTimer=null;}catalog=await api.project(action);current=null;img=null;window.secondDisplayUI?.clear();Renderer.clear();history=[];future=[];restoreDocument(Imaging.normalizeSettings({}));$('photo').hidden=true;$('empty').hidden=false;$('loading').hidden=true;$('originalLabel').hidden=true;$('photoName').textContent=active().name;$('dimensions').textContent='';$('saveStatus').textContent='Project saved locally';$('histogram').getContext('2d').clearRect(0,0,260,76);sync();setMode('edit');await refresh();if(catalog.selected)await select(catalog.selected);}catch(e){fail(e);}finally{busy=false;syncProjects();}}
$('projectPicker').onchange=()=>transition({type:'switch',id:$('projectPicker').value});
function open(create){creating=create;const p=active();$('projectDialogTitle').textContent=create?'New project':'Project settings';$('projectName').value=create?'':p.name;$('projectNotes').value=create?'':p.settings.notes;$('projectFormat').value=create?'jpeg':p.settings.format;$('projectQuality').value=create?100:p.settings.quality;$('projectSize').value=create?0:p.settings.size;$('projectExportSettings').hidden=create;$('saveProject').textContent=create?'Create project':'Save settings';dialog.showModal();$('projectName').focus();}
$('newProject').onclick=()=>open(true);$('projectSettings').onclick=()=>open(false);$('closeProject').onclick=()=>dialog.close();
$('projectForm').onsubmit=async e=>{e.preventDefault();const name=$('projectName').value.trim();if(!name)return;$('saveProject').disabled=true;try{if(creating){await transition({type:'create',name});if($('projectNotes').value)catalog=await api.project({type:'update',id:catalog.activeProjectId,settings:{...active().settings,notes:$('projectNotes').value}});}else catalog=await api.project({type:'update',id:catalog.activeProjectId,name,settings:{...active().settings,format:$('projectFormat').value,quality:Number($('projectQuality').value),size:Number($('projectSize').value),notes:$('projectNotes').value}});syncProjects();dialog.close();}catch(e){fail(e);}finally{$('saveProject').disabled=false;}};
move.onclick=()=>{$('moveProjectTarget').replaceChildren(...catalog.projects.filter(p=>p.id!==catalog.activeProjectId).map(p=>new Option(p.name,p.id)));moveDialog.showModal();};$('cancelMoveProject').onclick=()=>moveDialog.close();$('moveProjectForm').onsubmit=async e=>{e.preventDefault();const photoId=current?.id;if(!photoId)return;moveDialog.close();await transition({type:'move',id:$('moveProjectTarget').value,photoId});};
for(const id of ['exportFormat','quality','exportSize'])$(id).addEventListener('change',async()=>{const p=active();if(!p)return;const settings={...p.settings,format:$('exportFormat').value,quality:Number($('quality').value),size:Number($('exportSize').value)};p.settings=settings;try{await api.project({type:'update',id:p.id,settings});}catch(e){fail(e);}});
window.projectUI={sync:syncProjects};syncProjects();
})();
