const {parentPort,workerData}=require('node:worker_threads');
const fs=require('node:fs/promises'),path=require('node:path'),{pathToFileURL}=require('node:url'),{PNG}=require('pngjs'),Color=require('./raw-color.js');
(async()=>{const dir=path.dirname(require.resolve('libraw-wasm'));const {default:initialize}=await import(pathToFileURL(path.join(dir,'libraw.js')));const module=await initialize({wasmBinary:await fs.readFile(path.join(dir,'libraw.wasm'))});let decoder=new module.LibRaw();try{const input=new Uint8Array(await fs.readFile(workerData.source)),raw=Color.normalize(workerData.raw);let options={useCameraWb:true,outputColor:1,outputBps:16,userQual:3,noAutoBright:false};decoder.open(input,options);const metadata=decoder.metadata(true);if(!metadata.width||!metadata.height||metadata.width*metadata.height>60000000)throw Error('This RAW exceeds the current 60-megapixel development limit.');
if(raw&&!workerData.thumbnail){options={...options,outputColor:8,gamm:[1,1],noAutoBright:true,useCameraMatrix:3,useCameraWb:raw.wb==='camera',useAutoWb:raw.wb==='auto'||raw.wb==='spot',highlight:raw.highlight,expCorrec:true,expShift:2**raw.exposure,expPreser:1};
 if(raw.wb==='custom'){const base=metadata.color_data?.cam_mul,valid=base?.[0]>0&&base?.[1]>0&&base?.[2]>0,m=valid?base:metadata.color_data?.pre_mul;if(!m||!m[0]||!m[1]||!m[2])throw Error('Custom white balance is unavailable for this camera; use As Shot or Auto.');options.userMul=[m[0]*2**(raw.temperature/100),m[1]*2**(-raw.tint/150),m[2]*2**(-raw.temperature/100),(m[3]||m[1])*2**(-raw.tint/150)];}
 if(raw.wb==='spot'&&raw.spot){let [x,y]=raw.spot;switch(metadata.flip){case 3:x=1-x;y=1-y;break;case 5:[x,y]=[1-y,x];break;case 6:[x,y]=[y,1-x];break;}const w=metadata.width,h=metadata.height,size=Math.max(8,Math.round(Math.min(w,h)*.015));options.greybox=[Math.max(0,Math.min(w-size,Math.round(x*w-size/2))),Math.max(0,Math.min(h-size,Math.round(y*h-size/2))),size,size];}
 decoder.delete();decoder=new module.LibRaw();decoder.open(input,options);
}
let bytes;if(workerData.thumbnail){try{const thumbnail=decoder.thumbnailData();if(thumbnail?.data?.length&&thumbnail.data[0]===255&&thumbnail.data[1]===216)bytes=Buffer.from(thumbnail.data);}catch{}}
if(!bytes){const image=decoder.imageData();if(!image||image.colors!==3||![8,16].includes(image.bits)||image.data.length!==image.width*image.height*3)throw Error('The RAW decoder did not return a supported RGB image.');bytes=PNG.sync.write({width:image.width,height:image.height,data:image.data},{bitDepth:image.bits,inputColorType:2,colorType:2,inputHasAlpha:false,deflateLevel:3});
 if(raw&&!workerData.thumbnail){const display=Buffer.alloc(image.width*image.height*4);for(let i=0,j=0;i<image.data.length;i+=3,j+=4){const rgb=Color.from2020(image.data[i]/65535,image.data[i+1]/65535,image.data[i+2]/65535);for(let c=0;c<3;c++)display[j+c]=Math.round(Math.max(0,Math.min(1,Color.encode(rgb[c])))*255);display[j+3]=255;}const png=PNG.sync.write({width:image.width,height:image.height,data:display},{deflateLevel:3});await fs.writeFile(workerData.target+'.display.png.tmp',png);await fs.rename(workerData.target+'.display.png.tmp',workerData.target+'.display.png');}
}
await fs.writeFile(workerData.target+'.tmp',bytes);await fs.rename(workerData.target+'.tmp',workerData.target);parentPort.postMessage({ok:true});
}finally{decoder.delete();}})().catch(error=>parentPort.postMessage({error:'This RAW could not be decoded or developed. '+error.message}));
