// Separate workers keep interactive feedback independent of full-quality refinement.
const Renderer=(()=>{
let interactiveSize=1280,lastStats=null,fastFrames=0;
async function assetsFor(worker,settings,max,original,known){const refs=original?[]:Creative.refs(settings),size=max||0;for(const id of refs){const key=id+':'+size+':'+settings.precision;if(known.get(id)===key)continue;const image=new Image();image.src=await api.effectAsset(id);await image.decode();const scale=size?Math.min(1,size/Math.max(image.naturalWidth,image.naturalHeight)):1;const [bitmap,raw]=await Promise.all([createImageBitmap(image,{resizeWidth:Math.max(1,Math.round(image.naturalWidth*scale)),resizeHeight:Math.max(1,Math.round(image.naturalHeight*scale)),resizeQuality:'high'}),settings.precision==='float32'?api.effectAsset(id,true):null]);worker.postMessage({type:'effect-source',assetId:id,bitmap,raw},[bitmap,...(raw?[raw.buffer]:[])]);known.set(id,key);}worker.postMessage({type:'effect-prune',ids:refs});for(const id of known.keys())if(!refs.includes(id))known.delete(id);}

function lane(interactive=false){
let known=new Map(),worker=null,source=null,sourcePrecision=null,ready=null,active=null,queued=null,sequence=0;
function timeoutError(){const e=Error('Preview renderer timed out');e.code='RENDER_TIMEOUT';return e;}
function stop(error=null){worker?.terminate();worker=null;source=null;ready=null;for(const job of [active,queued])if(job){clearTimeout(job.timer);error?job.reject(error):job.resolve(null);}active=null;queued=null;}
async function start(){if(active||!queued)return;const job=active=queued,local=worker;queued=null;job.started=performance.now();job.timer=setTimeout(()=>{if(active===job)stop(timeoutError());},interactive?10000:30000);try{await assetsFor(local,job.message.settings,job.message.max,job.message.original,known);if(active!==job||worker!==local)return;if(job.superseded){clearTimeout(job.timer);active=null;job.resolve(null);start();return;}local.postMessage(job.message);}catch(e){if(active!==job)return;clearTimeout(job.timer);active=null;job.reject(e);start();}}
function reset(image,precision){stop();known=new Map();sourcePrecision=precision;source=image;const local=new Worker('render-worker.js');worker=local;local.onmessage=({data})=>{if(worker!==local){data.bitmap?.close();return;}lastStats={backend:data.backend,renderMs:data.renderMs};const job=active;if(!job||data.id!==job.message.id){data.bitmap?.close();return;}clearTimeout(job.timer);active=null;if(interactive&&!data.error&&!data.cancelled&&!job.superseded){const ms=performance.now()-job.started;if(ms>100){interactiveSize=Math.max(640,Math.round(interactiveSize*.8/128)*128);fastFrames=0;}else if(ms<25&&++fastFrames>=12){interactiveSize=Math.min(2048,interactiveSize+128);fastFrames=0;}else if(ms>=25)fastFrames=0;}if(data.cancelled||job.superseded){data.bitmap?.close();job.resolve(null);}else if(data.error)job.reject(Error(data.error));else job.resolve(data.bitmap);start();};local.onerror=e=>{if(worker===local)stop(Error(e.message||'Photo renderer failed'));};ready=Promise.all([createImageBitmap(image),precision==='float32'&&image.lithPhotoId?api.rawData(image.lithPhotoId,image.lithRawSettings):null]).then(([bitmap,raw])=>{if(worker!==local){bitmap.close();return false;}local.postMessage({type:'source',bitmap,raw,rawSettings:image.lithRawSettings},[bitmap,...(raw?[raw.buffer]:[])]);return true;});}
return {clear:()=>stop(),cancelActive(){queued?.resolve(null);queued=null;if(active){active.superseded=true;worker?.postMessage({type:'cancel-preview'});}},async preview(image,settings,max,original,region=null,backend=null){if(image!==source||settings.precision!==sourcePrecision)reset(image,settings.precision);const expected=worker;let timer;try{const ok=await Promise.race([ready,new Promise((_,reject)=>{timer=setTimeout(()=>reject(timeoutError()),30000);})]);if(!ok||worker!==expected)return null;}catch(e){if(worker===expected)stop(e);throw e;}finally{clearTimeout(timer);}return new Promise((resolve,reject)=>{queued?.resolve(null);if(active&&!active.superseded){active.superseded=true;worker.postMessage({type:'cancel-preview'});}queued={resolve,reject,message:{type:'preview',id:++sequence,settings,max,original,region,backend}};start();});}};
}
// Export lanes serialize jobs and keep a decoded source/device warm between photos.
let exportsRunning=0;const exportStats={workers:0,sources:0,completed:0};
function exportLane(thumbnail=false){let worker=null,source=null,precision=null,known=new Map(),tail=Promise.resolve(),idleTimer,sequence=0;
function reset(){clearTimeout(idleTimer);worker?.terminate();worker=null;source=null;precision=null;known=new Map();}
return function enqueue(image,settings,max,format,quality,sharpening,signal){const run=async()=>{if(signal?.aborted)throw Error('Export cancelled');clearTimeout(idleTimer);if(!thumbnail)exportsRunning++;let rejectActive;const abort=()=>{reset();rejectActive?.(Error('Export cancelled'));};signal?.addEventListener('abort',abort,{once:true});try{
if(!thumbnail&&image.lithPhotoId&&image.lithRawKey!==RawColor.key(settings.rawDevelop))image=await PhotoCache.load(image.lithPhotoId,settings.rawDevelop??null);
if(signal?.aborted)throw Error('Export cancelled');if(!worker){worker=new Worker('render-worker.js');exportStats.workers++;}const local=worker;
const high=!thumbnail&&settings.precision==='float32';if(source!==image||precision!==high){const [bitmap,raw]=await Promise.all([createImageBitmap(image),high&&image.lithPhotoId?api.rawData(image.lithPhotoId,image.lithRawSettings):null]);if(signal?.aborted||worker!==local){bitmap.close();throw Error('Export cancelled');}local.postMessage({type:'source',bitmap,raw,rawSettings:image.lithRawSettings},[bitmap,...(raw?[raw.buffer]:[])]);source=image;precision=high;exportStats.sources++;}
await assetsFor(local,settings,max,false,known);if(signal?.aborted||worker!==local)throw Error('Export cancelled');const result=await new Promise((resolve,reject)=>{rejectActive=reject;const id=++sequence;local.onmessage=({data})=>{if(data.id!==id)return;data.error?reject(Error(data.error)):resolve(new Blob([data.bytes],{type:data.mime}));};local.onerror=e=>reject(Error(e.message||'Export failed'));local.postMessage({type:'export',id,settings,max,format,quality,sharpening});});exportStats.completed++;return result;
}catch(e){reset();throw e;}finally{signal?.removeEventListener('abort',abort);if(!thumbnail)exportsRunning--;idleTimer=setTimeout(reset,thumbnail?5000:30000);}};
const result=tail.then(run,run);tail=result.catch(()=>{});return result;};}
const fullExport=exportLane(),thumbnailExport=exportLane(true);
const fast=lane(true),final=lane();
return {cancelRefinement:()=>final.cancelActive(),detail:(image,settings,region)=>final.preview(image,settings,0,false,region),stats:()=>lastStats,interactiveSize:()=>interactiveSize,clear(){fast.clear();final.clear();},preview(image,settings,max,original,interactive=false,backend=null){return (interactive?fast:final).preview(image,settings,max,original,null,backend);},exportBusy:()=>exportsRunning>0,exportStats:()=>({...exportStats}),export(image,settings,max,format,quality,sharpening=null,thumbnail=false,signal=null){return (thumbnail?thumbnailExport:fullExport)(image,structuredClone(settings),max,format,quality,structuredClone(sharpening),signal);}};
})();
