// Separate workers keep interactive feedback independent of full-quality refinement.
const Renderer=(()=>{
let interactiveSize=2048,lastStats=null;
async function assetsFor(worker,settings,max,original,known){const refs=original?[]:Creative.refs(settings),size=max||0;for(const id of refs){const key=id+':'+size+':'+settings.precision;if(known.get(id)===key)continue;const image=new Image();image.src=await api.effectAsset(id);await image.decode();const scale=size?Math.min(1,size/Math.max(image.naturalWidth,image.naturalHeight)):1;const [bitmap,raw]=await Promise.all([createImageBitmap(image,{resizeWidth:Math.max(1,Math.round(image.naturalWidth*scale)),resizeHeight:Math.max(1,Math.round(image.naturalHeight*scale)),resizeQuality:'high'}),settings.precision==='float32'?api.effectAsset(id,true):null]);worker.postMessage({type:'effect-source',assetId:id,bitmap,raw},[bitmap,...(raw?[raw.buffer]:[])]);known.set(id,key);}worker.postMessage({type:'effect-prune',ids:refs});for(const id of known.keys())if(!refs.includes(id))known.delete(id);}

function lane(interactive=false){
let known=new Map(),worker=null,source=null,sourcePrecision=null,ready=null,active=null,queued=null,sequence=0;
function timeoutError(){const e=Error('Preview renderer timed out');e.code='RENDER_TIMEOUT';return e;}
function stop(error=null){worker?.terminate();worker=null;source=null;ready=null;for(const job of [active,queued])if(job){clearTimeout(job.timer);error?job.reject(error):job.resolve(null);}active=null;queued=null;}
async function start(){if(active||!queued)return;const job=active=queued,local=worker;queued=null;job.started=performance.now();job.timer=setTimeout(()=>{if(active===job)stop(timeoutError());},interactive?10000:30000);try{await assetsFor(local,job.message.settings,job.message.max,job.message.original,known);if(active!==job||worker!==local)return;local.postMessage(job.message);}catch(e){if(active!==job)return;clearTimeout(job.timer);active=null;job.reject(e);start();}}
function reset(image,precision){stop();known=new Map();sourcePrecision=precision;source=image;const local=new Worker('render-worker.js');worker=local;local.onmessage=({data})=>{if(worker!==local){data.bitmap?.close();return;}lastStats={backend:data.backend,renderMs:data.renderMs};const job=active;if(!job||data.id!==job.message.id){data.bitmap?.close();return;}clearTimeout(job.timer);active=null;if(interactive&&!data.error){const ms=performance.now()-job.started;if(ms>90)interactiveSize=Math.max(1280,Math.round(interactiveSize*.85));else if(ms<35)interactiveSize=Math.min(2560,Math.round(interactiveSize*1.1));}if(data.error)job.reject(Error(data.error));else job.resolve(data.bitmap);start();};local.onerror=e=>{if(worker===local)stop(Error(e.message||'Photo renderer failed'));};ready=Promise.all([createImageBitmap(image),precision==='float32'&&image.lithPhotoId?api.rawData(image.lithPhotoId,image.lithRawSettings):null]).then(([bitmap,raw])=>{if(worker!==local){bitmap.close();return false;}local.postMessage({type:'source',bitmap,raw,rawSettings:image.lithRawSettings},[bitmap,...(raw?[raw.buffer]:[])]);return true;});}
return {clear:()=>stop(),cancelActive(){if(active||queued)stop();},async preview(image,settings,max,original,region=null,backend=null){if(image!==source||settings.precision!==sourcePrecision)reset(image,settings.precision);const expected=worker;let timer;try{const ok=await Promise.race([ready,new Promise((_,reject)=>{timer=setTimeout(()=>reject(timeoutError()),30000);})]);if(!ok||worker!==expected)return null;}catch(e){if(worker===expected)stop(e);throw e;}finally{clearTimeout(timer);}return new Promise((resolve,reject)=>{queued?.resolve(null);queued={resolve,reject,message:{type:'preview',id:++sequence,settings,max,original,region,backend}};start();});}};
}
const fast=lane(true),final=lane();
return {cancelRefinement:()=>final.cancelActive(),detail:(image,settings,region)=>final.preview(image,settings,0,false,region),stats:()=>lastStats,interactiveSize:()=>interactiveSize,clear(){fast.clear();final.clear();},preview(image,settings,max,original,interactive=false,backend=null){return (interactive?fast:final).preview(image,settings,max,original,null,backend);},async export(image,settings,max,format,quality,sharpening=null,thumbnail=false,signal=null){if(signal?.aborted)throw Error('Export cancelled');if(!thumbnail&&image.lithPhotoId&&image.lithRawKey!==RawColor.key(settings.rawDevelop))image=await PhotoCache.load(image.lithPhotoId,settings.rawDevelop??null);const local=new Worker('render-worker.js');let abortReject;const abort=()=>{local.terminate();abortReject?.(Error('Export cancelled'));};signal?.addEventListener('abort',abort,{once:true});try{const [bitmap,raw]=await Promise.all([createImageBitmap(image),!thumbnail&&settings.precision==='float32'&&image.lithPhotoId?api.rawData(image.lithPhotoId,image.lithRawSettings):null]);local.postMessage({type:'source',bitmap,raw,rawSettings:image.lithRawSettings},[bitmap,...(raw?[raw.buffer]:[])]);if(signal?.aborted)throw Error('Export cancelled');await assetsFor(local,settings,max,false,new Map());if(signal?.aborted)throw Error('Export cancelled');return await new Promise((resolve,reject)=>{abortReject=reject;local.onmessage=({data})=>data.error?reject(Error(data.error)):resolve(new Blob([data.bytes],{type:data.mime}));local.onerror=e=>reject(Error(e.message||'Export failed'));local.postMessage({type:'export',id:1,settings,max,format,quality,sharpening});});}finally{signal?.removeEventListener('abort',abort);local.terminate();}}};
})();
