(()=>{
let tool='light',family='optics',view='edited',split=50,gate=false,cropping=false,cropRect=null,cropPointer=null,cropStart=null,lastGateTarget=null,referenceKey='',referenceImage=null,referenceRequest=0;
const section=window.advancedUI.section;
const findSection=text=>[...document.querySelectorAll('details')].find(d=>d.querySelector('summary')?.textContent===text);
const filmLegacy=findSection('Film & atmosphere'),grain=findSection('Grain structure'),halation=findSection('Layered halation'),vignette=findSection('Vignette');
function moveRow(id,target){const row=$(id)?.closest('.slider-row');if(row)target.querySelector('summary').after(row);}
const diffusion=section('Diffusion / mist','effects',[['diffusion','Filter strength',0,100,1],['diffusionRadius','Softness / radius',0,100,1],['diffusionScatter','Highlight scattering',0,100,1],['diffusionProtect','Preserve dark tones',0,100,1]]);
const bloom=section('Bloom & threshold gate','effects',[['bloomThreshold','Threshold',0,100,1],['bloomKnee','Soft knee',0,100,1]]);moveRow('glowRadius',bloom);moveRow('glow',bloom);const bloomLabel=$('glow').closest('.slider-row').querySelector('label');bloomLabel.firstChild.textContent='Bloom amount';
moveRow('halation',halation);halation.querySelector('p').textContent='Three tinted highlight layers: tight edges, medium halos, and wide diffusion.';
const flare=section('Anamorphic lens flare','effects',[['flare','Flare intensity',0,100,1],['flareThreshold','Source highlight threshold',0,100,1],['flareLength','Horizontal streak length',0,100,1],['flareWidth','Streak thickness',0,100,1],['flareAngle','Streak angle',-90,90,1],['flareGhosts','Lens ghosts',0,100,1],['flareX','Manual source X',0,100,1],['flareY','Manual source Y',0,100,1]]);
const matte=section('Dynamic matte shadows','effects',[['matte','Shadow lift',0,100,1],['matteRange','Shadow range',0,100,1],['matteSoftness','Transition softness',0,100,1],['matteDynamic','Adapt to photo',0,100,1],['matteTint','Shadow tint strength',0,100,1]]);moveRow('fade',matte);moveRow('grain',grain);filmLegacy.remove();
for(const el of [diffusion,bloom,halation,flare])el.dataset.effectFamily='optics';for(const el of [matte,grain])el.dataset.effectFamily='film';vignette.dataset.effectFamily='finish';
// Keep optical tools in the same order as their workflow.
const groups=$('advancedControls');for(const el of [diffusion,bloom,halation,flare,matte,grain,vignette])groups.append(el);
function selectControl(parent,key,label,options){const row=document.createElement('label');row.className='select-row';row.textContent=label;const input=document.createElement('select');input.id=key;input.setAttribute('aria-label',label);for(const [value,name]of options)input.append(new Option(name,String(value)));input.onchange=()=>mutate(()=>settings[key]=Number(input.value));row.append(input);parent.querySelector('summary').after(row);return input;}
selectControl(diffusion,'diffusionMode','Filter type',[[0,'White mist'],[1,'Black mist'],[2,'Soft focus']]);selectControl(flare,'flareSource','Light source',[[0,'Find bright lights'],[1,'Place manually']]);
function colorControl(parent,key,label){const row=document.createElement('label');row.className='color-row';row.textContent=label;const input=document.createElement('input');input.type='color';input.id=key;input.setAttribute('aria-label',label);input.onchange=()=>mutate(()=>settings[key]=input.value);row.append(input);parent.append(row);}
colorControl(bloom,'bloomTint','Bloom tint');colorControl(flare,'flareTint','Flare tint');colorControl(matte,'matteColor','Matte shadow color');
function recipes(parent,items){const wrap=document.createElement('div');wrap.className='effect-recipes';for(const [name,values]of items){const b=document.createElement('button');b.textContent=name;b.dataset.effectRecipe=Object.keys(values)[0];b.onclick=()=>mutate(()=>{for(const [key,value]of Object.entries(values))settings[key]=value;});wrap.append(b);}parent.querySelector('summary').after(wrap);}
recipes(diffusion,[['Black mist ¼',{diffusion:30,diffusionMode:1,diffusionScatter:35,diffusionProtect:90}],['Soft portrait',{diffusion:50,diffusionMode:2,diffusionRadius:45,diffusionScatter:25}],['Dream mist',{diffusion:60,diffusionMode:0,diffusionRadius:55,diffusionScatter:70,diffusionProtect:35}]]);
recipes(flare,[['Blue streak',{flare:70,flareLength:80,flareWidth:10,flareTint:'#79bfff'}],['Warm cinema',{flare:55,flareLength:65,flareWidth:18,flareTint:'#ffd28d'}]]);
recipes(matte,[['Soft matte',{matte:35,matteRange:45,matteDynamic:80}],['Faded shadows',{matte:70,matteRange:65,matteDynamic:90}]]);
const gateButton=document.createElement('button');gateButton.id='bloomGate';gateButton.className='wide-button';gateButton.textContent='Preview threshold gate';bloom.append(gateButton);gateButton.onclick=()=>{gate=!gate;if(gate){view='edited';$('reviewMode').value=view;cropping=false;}render();syncReview();};
const effectNav=document.createElement('div');effectNav.id='effectNav';effectNav.dataset.toolgroup='effects';effectNav.className='effect-nav';for(const [id,label]of [['optics','Optics'],['film','Film'],['blend','Blend'],['finish','Finish']]){const b=document.createElement('button');b.textContent=label;b.dataset.effectFamilyButton=id;b.onclick=()=>{family=id;refreshSections(tool);};effectNav.append(b);}$('controls').before(effectNav);
function refreshSections(value){tool=value;effectNav.hidden=value!=='effects';document.querySelectorAll('[data-effect-family]').forEach(el=>el.hidden=value!=='effects'||el.dataset.effectFamily!==family);document.querySelectorAll('[data-effect-family-button]').forEach(b=>b.classList.toggle('active',b.dataset.effectFamilyButton===family));}
const presetSelect=document.createElement('select');presetSelect.id='presetFamily';presetSelect.setAttribute('aria-label','Preset collection');for(const [value,label]of [['all','All looks'],['stock','Film stocks'],['dream','Dreamy looks'],['35mm','35mm styles']])presetSelect.append(new Option(label,value));$('presets').before(presetSelect);presetSelect.onchange=()=>{for(const b of document.querySelectorAll('.preset')){const name=b.textContent,filter=presetSelect.value;b.hidden=filter==='all'?false:filter==='stock'?!name.includes('inspired'):filter==='dream'?!name.startsWith('Dream'):!name.startsWith('35mm');}};
// Aligned before/after references retain composition and borders, without color/effect edits.
const frame=$('photoFrame'),before=document.createElement('canvas');before.id='beforeCanvas';before.hidden=true;frame.append(before);const divider=document.createElement('div');divider.id='wipeDivider';divider.tabIndex=0;divider.setAttribute('role','slider');divider.setAttribute('aria-label','Before after divider');divider.setAttribute('aria-valuemin','0');divider.setAttribute('aria-valuemax','100');divider.innerHTML='<span>↔</span>';divider.hidden=true;frame.append(divider);
const badge=document.createElement('div');badge.id='reviewBadge';badge.hidden=true;frame.append(badge);
const side=document.createElement('div');side.id='sideComparison';side.hidden=true;const sideCanvases=[];for(const label of ['BEFORE','AFTER']){const wrap=document.createElement('div');const canvas=document.createElement('canvas');const text=document.createElement('span');text.textContent=label;wrap.append(canvas,text);side.append(wrap);sideCanvases.push(canvas);}$('stage').append(side);
const reviewSelect=document.createElement('select');reviewSelect.id='reviewMode';reviewSelect.setAttribute('aria-label','Before after view');for(const [value,label]of [['edited','Edited'],['wipe','Before / after wipe'],['side','Side by side'],['original','Before · same crop']])reviewSelect.append(new Option(label,value));$('compare').before(reviewSelect);const wipeRange=document.createElement('input');Object.assign(wipeRange,{id:'wipePosition',type:'range',min:0,max:100,value:50});wipeRange.setAttribute('aria-label','Before after split');wipeRange.hidden=true;reviewSelect.after(wipeRange);
function setSplit(value){split=Math.max(0,Math.min(100,value));wipeRange.value=split;before.style.clipPath=view==='wipe'?'inset(0 '+(100-split)+'% 0 0)':'none';divider.style.left=split+'%';divider.setAttribute('aria-valuenow',Math.round(split));}
reviewSelect.onchange=()=>{view=reviewSelect.value;gate=false;cropping=false;zoom=0;render();syncReview();};wipeRange.oninput=()=>setSplit(Number(wipeRange.value));divider.onpointerdown=e=>{divider.setPointerCapture(e.pointerId);divider.dataset.dragging=e.pointerId;};divider.onpointermove=e=>{if(divider.dataset.dragging!==String(e.pointerId))return;const rect=frame.getBoundingClientRect();setSplit((e.clientX-rect.left)/rect.width*100);};divider.onpointerup=divider.onpointercancel=()=>delete divider.dataset.dragging;divider.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();setSplit(e.key==='Home'?0:e.key==='End'?100:split+(e.key==='ArrowRight'?2:-2));}};
function copy(source,target){target.width=source.width;target.height=source.height;target.getContext('2d').drawImage(source,0,0);}
async function update(snapshot){if(!img)return;layoutReview();if(view==='edited'||comparing||cropping||gate)return;const neutral=structuredClone(Imaging.defaults);for(const key of Imaging.compositionKeys)neutral[key]=snapshot[key];const key=JSON.stringify([previewLimit(img,neutral),...Imaging.compositionKeys.map(k=>neutral[k])]);if(referenceKey!==key||referenceImage!==img){referenceKey=key;referenceImage=img;const token=++referenceRequest;before.dataset.ready='false';try{const blob=await Renderer.export(img,neutral,previewLimit(img,neutral),'png',1);const bitmap=await createImageBitmap(blob);if(token!==referenceRequest){bitmap.close();return;}copy(bitmap,before);copy(bitmap,sideCanvases[0]);bitmap.close();before.dataset.ready='true';}catch(e){referenceKey='';fail(e);}}copy($('photo'),sideCanvases[1]);layoutReview();}
function layoutReview(){const show=!!img&&!comparing&&!cropping&&!gate;before.hidden=!show||!['wipe','original'].includes(view)||before.dataset.ready!=='true';divider.hidden=!show||view!=='wipe';wipeRange.hidden=!show||view!=='wipe';side.hidden=!show||view!=='side'||before.dataset.ready!=='true';frame.hidden=show&&view==='side'&&before.dataset.ready==='true';setSplit(split);badge.hidden=!gate&&!cropping&&(!show||view==='edited'||view==='side');badge.textContent=gate?'BLOOM GATE · PREVIEW ONLY':cropping?'DRAG TO FRAME YOUR CROP':view==='wipe'?'BEFORE  |  AFTER':'BEFORE · SAME CROP';if(show&&view==='side'){const stage=$('stage'),ratio=$('photo').width/$('photo').height,w=Math.min((stage.clientWidth-76)/2,(stage.clientHeight-70)*ratio);for(const c of sideCanvases){c.style.width=Math.max(1,w)+'px';c.style.height=Math.max(1,w/ratio)+'px';}}}
// Expanded composition tools; selection coordinates describe the un-cropped safe image.
const cropSection=$('crop').closest('details');cropSection.querySelector('summary').textContent='Crop & composition';for(const [value,label]of [[.666666667,'2 : 3 portrait'],[.75,'3 : 4 portrait'],[1.25,'5 : 4 print'],[.5625,'9 : 16 story'],[2,'2 : 1 wide'],[2.333333333,'21 : 9 cinema'],[2.39,'2.39 : 1 scope'],[-1,'Custom ratio']])$('crop').append(new Option(label,String(value)));
const custom=document.createElement('div');custom.id='customRatio';custom.className='custom-ratio';for(const [key,label]of [['customAspectW','Width'],['customAspectH','Height']]){const lab=document.createElement('label');lab.textContent=label;const input=document.createElement('input');Object.assign(input,{id:key,type:'number',min:1,max:30000,step:1});input.onchange=()=>{const value=Number(input.value);if(!Number.isFinite(value)||value<1||value>30000){input.value=settings[key];return;}mutate(()=>settings[key]=value);};lab.append(input);custom.append(lab);}$('crop').closest('label').after(custom);$('cropControls').prepend(slider('cropScale','Crop area (%)',1,100,.1),slider('straighten','Straighten',-15,15,.1));
const social=document.createElement('div');social.className='social-crops';const socialTitle=document.createElement('p');socialTitle.className='small muted';socialTitle.textContent='Instagram crops';social.append(socialTitle);for(const [ratio,label]of [[.8,'4:5 · Portrait'],[1,'1:1 · Square'],[.5625,'9:16 · Story / Reel'],[1.91,'1.91:1 · Landscape']]){if(![...$('crop').options].some(o=>Number(o.value)===ratio))$('crop').append(new Option(label,String(ratio)));const b=document.createElement('button');b.textContent=label;b.dataset.socialRatio=ratio;b.onclick=()=>mutate(()=>settings.crop=ratio);social.append(b);}cropSection.querySelector('.select-row').before(social);
const cropActions=document.createElement('div');cropActions.className='crop-actions';for(const [id,label,action]of [['drawCrop','Draw free crop',()=>{cropping=true;gate=false;view='edited';reviewSelect.value=view;cropRect={x:.1,y:.1,w:.8,h:.8};render();syncReview();}],['swapRatio','Swap ratio',()=>mutate(()=>{const g=Imaging.geometry(img.naturalWidth,img.naturalHeight,documentSettings);settings.customAspectW=g.height;settings.customAspectH=g.width;settings.crop=-1;})],['flipVertical','Flip vertical',()=>mutate(()=>settings.flipV=!settings.flipV)],['resetCrop','Reset crop',()=>mutate(()=>{for(const key of ['crop','cropX','cropY','cropScale','rotation','straighten','flip','flipV'])settings[key]=Imaging.defaults[key];})]]){const b=document.createElement('button');b.id=id;b.textContent=label;b.onclick=()=>{if(img)action();};cropActions.append(b);}cropSection.append(cropActions);
const guidesLabel=document.createElement('label');guidesLabel.className='mask-checks';const guideToggle=document.createElement('input');guideToggle.id='cropGuides';guideToggle.type='checkbox';guidesLabel.append(guideToggle,document.createTextNode('Rule-of-thirds guides'));cropSection.append(guidesLabel);const guides=document.createElement('div');guides.id='compositionGuides';guides.hidden=true;frame.append(guides);guideToggle.onchange=()=>guides.hidden=!guideToggle.checked||tool!=='frame';
const cropLayer=document.createElement('div');cropLayer.id='cropDrawLayer';cropLayer.hidden=true;const cropBox=document.createElement('div');cropBox.id='cropDrawBox';cropLayer.append(cropBox);frame.append(cropLayer);const confirmation=document.createElement('div');confirmation.id='cropConfirmation';confirmation.hidden=true;const apply=document.createElement('button');apply.id='applyCrop';apply.textContent='Apply crop';apply.className='primary';const cancel=document.createElement('button');cancel.id='cancelCrop';cancel.textContent='Cancel';confirmation.append(apply,cancel);cropSection.append(confirmation);
function showCropRect(){if(!cropRect)return;cropBox.style.left=cropRect.x*100+'%';cropBox.style.top=cropRect.y*100+'%';cropBox.style.width=cropRect.w*100+'%';cropBox.style.height=cropRect.h*100+'%';}
function point(e){const r=cropLayer.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};}
cropLayer.onpointerdown=e=>{if(e.button!==0)return;cropPointer=e.pointerId;cropStart=point(e);cropLayer.setPointerCapture(e.pointerId);};cropLayer.onpointermove=e=>{if(cropPointer!==e.pointerId)return;const p=point(e);cropRect={x:Math.min(p.x,cropStart.x),y:Math.min(p.y,cropStart.y),w:Math.abs(p.x-cropStart.x),h:Math.abs(p.y-cropStart.y)};showCropRect();};cropLayer.onpointerup=cropLayer.onpointercancel=()=>cropPointer=null;
apply.onclick=()=>{if(!cropRect||cropRect.w<.05||cropRect.h<.05){toast('Draw a crop at least 5% of the image in each direction.');return;}const base=Imaging.geometry(img.naturalWidth,img.naturalHeight,{...documentSettings,crop:0,cropScale:100}),cw=cropRect.w*base.cw,ch=cropRect.h*base.ch;cropping=false;mutate(()=>{settings.crop=-1;settings.customAspectW=Math.max(1,Math.round(cw));settings.customAspectH=Math.max(1,Math.round(ch));const fit=Imaging.geometry(img.naturalWidth,img.naturalHeight,{...documentSettings,cropScale:100});settings.cropScale=Math.max(1,Math.min(100,cw/fit.cw*100));settings.cropX=base.cw-cw>.001?cropRect.x*base.cw/(base.cw-cw)*100:50;settings.cropY=base.ch-ch>.001?cropRect.y*base.ch/(base.ch-ch)*100:50;});syncReview();};cancel.onclick=()=>{cropping=false;render();syncReview();};
function syncReview(){if(gate&&(!window.nodeUI.canEdit('glow')||documentSettings.nodes.find(n=>n.uid===activeNodeUid)?.enabled===false)){gate=false;render();}if(gate&&lastGateTarget!==activeNodeUid){lastGateTarget=activeNodeUid;render();}reviewSelect.disabled=!img;social.querySelectorAll('button').forEach(b=>{b.disabled=!img;b.classList.toggle('active',Number(b.dataset.socialRatio)===settings.crop);b.setAttribute('aria-pressed',String(Number(b.dataset.socialRatio)===settings.crop));});for(const el of cropActions.children)el.disabled=!img;for(const el of custom.querySelectorAll('input'))el.disabled=!img;custom.hidden=settings.crop!==-1;cropLayer.hidden=!cropping||!img;confirmation.hidden=!cropping;showCropRect();guideToggle.disabled=!img;guides.hidden=!guideToggle.checked||tool!=='frame'||cropping;gateButton.disabled=!img||!window.nodeUI.canEdit('glow');gateButton.textContent=gate?'Hide threshold gate':'Preview threshold gate';for(const b of document.querySelectorAll('[data-effect-recipe]'))b.disabled=!img||!window.nodeUI.canEdit(b.dataset.effectRecipe);for(const id of ['flareX','flareY'])$(id).closest('.slider-row').hidden=settings.flareSource!==1;refreshSections(tool);layoutReview();}
function previewSettings(s){if(cropping)return {...s,crop:0,cropScale:100,border:0,previewCropMode:true};return gate?{...s,previewGate:true,gateTarget:activeNodeUid}:s;}
function toolChanged(value){tool=value;if(value!=='frame'&&cropping){cropping=false;render();}if(value==='mask'&&gate){gate=false;render();}if(value==='mask'&&view!=='edited'){view='edited';reviewSelect.value=view;layoutReview();}guides.hidden=!guideToggle.checked||value!=='frame';}
for(const [id,label,key,target]of [['sideCompare','Side-by-side comparison','y','side'],['originalCompare','Toggle original','\\','original']])Shortcuts.register(id,label,'View',[key],()=>{reviewSelect.value=view===target?'edited':target;reviewSelect.dispatchEvent(new Event('change'));},()=>!!img);

window.reviewUI={isCropping:()=>cropping,isCurrent:s=>!!s.previewGate===gate&&!!s.previewCropMode===cropping&&(!gate||s.gateTarget===activeNodeUid),sync:syncReview,update,layout:layoutReview,previewSettings,toolChanged,refreshSections};sync();refreshSections('light');
})();
