const fs=require('node:fs/promises'),path=require('node:path'),{Worker}=require('node:worker_threads');
function setup({ipcMain,getCatalog,root,nativeImage,Raw,Formats,app}){
 const folder=path.join(root,'smart-search'),file=path.join(folder,'index-v1.json');let state={enabled:false,entries:{}},worker=null,sequence=0,pending=null,idle=null,progress=null,serial=Promise.resolve();
 const ready=(async()=>{try{const d=JSON.parse(await fs.readFile(file,'utf8'));if(d.version===1&&d.entries)state={enabled:d.enabled===true,entries:d.entries};}catch{}})();
 async function persist(){await fs.mkdir(folder,{recursive:true});await fs.writeFile(file+'.tmp',JSON.stringify({version:1,...state}));await fs.rename(file+'.tmp',file);}
 function stop(){clearTimeout(idle);worker?.terminate();worker=null;if(pending){clearTimeout(pending.timer);pending.reject(Error('Search cancelled'));pending=null;}}
 function run(type,data={}){clearTimeout(idle);if(!worker){worker=new Worker(path.join(__dirname,'search-worker.cjs'),{workerData:{cache:path.join(folder,'models')}});const local=worker;worker.on('message',m=>{if(m.progress!==undefined){progress={percent:m.progress,file:m.file};return;}const p=pending;if(p&&p.id===m.id){pending=null;clearTimeout(p.timer);m.error?p.reject(Error(m.error)):p.resolve(m.result);idle=setTimeout(stop,30000);}});worker.on('error',e=>{if(worker!==local)return;clearTimeout(pending?.timer);pending?.reject(e);pending=null;worker=null;});worker.on('exit',()=>{if(worker!==local)return;if(pending){clearTimeout(pending.timer);pending.reject(Error('Search worker stopped'));pending=null;}worker=null;});}return new Promise((resolve,reject)=>{const id=++sequence;const timer=setTimeout(()=>{reject(Error('Search timed out. Try again.'));stop();},type==='enable'?600000:120000);pending={id,resolve,reject,timer};worker.postMessage({type,id,...data});});}
 const photo=id=>{const p=getCatalog().photos.find(p=>p.id===id);if(!p)throw Error('Photo not found');return p;};
 const key=p=>(p.sourceId||p.id)+p.ext;
 const info=p=>({id:p.id,camera:state.entries[key(p)]?.camera||'',metadata:!!state.entries[key(p)]?.metadata,indexed:Array.isArray(state.entries[key(p)]?.vector)});
 ipcMain.handle('gallery-search-status',async()=>{await ready;return {enabled:state.enabled,progress,photos:getCatalog().photos.map(info)};});
 ipcMain.handle('gallery-search',(_,request)=>{const task=serial.catch(()=>{}).then(async()=>{await ready;const type=request?.type;if(type==='enable'){progress={percent:0,file:'Preparing download'};try{await run('enable');state.enabled=true;await persist();return true;}finally{progress=null;}}if(type==='disable'){state.enabled=false;stop();await persist();return true;}if(type==='metadata'||type==='index'){const p=photo(request.id),id=p.sourceId||p.id,k=key(p),entry=state.entries[k]||{},source=path.join(root,'originals',id+p.ext);if(type==='metadata'&&!entry.metadata){Object.assign(entry,await run('metadata',{file:source}),{metadata:true});}if(type==='index'){if(!state.enabled)throw Error('Enable optional AI search first.');if(!entry.vector){const target=path.join(folder,id+'-search.jpg');await fs.mkdir(folder,{recursive:true});try{await fs.access(target);}catch{const image=await nativeImage.createThumbnailFromPath(Formats.isRaw(p.ext)?await Raw.image(root,{...p,id},true):source,{width:256,height:256});if(image.isEmpty())throw Error('Could not read a search preview');await fs.writeFile(target,image.toJPEG(85));}entry.vector=await run('image',{file:target});}}state.entries[k]=entry;await persist();return info(p);}if(type==='query'){if(!state.enabled)throw Error('Enable optional AI search first.');const text=String(request.text||'').trim().slice(0,300);if(!text)return [];const entries=getCatalog().photos.filter(p=>p.projectId===request.projectId&&Array.isArray(state.entries[key(p)]?.vector)).map(p=>({id:p.id,vector:state.entries[key(p)].vector}));return run('rank',{text,entries});}throw Error('Unknown search action');});serial=task;return task;});
 app.on('before-quit',stop);
}
module.exports={setup};
