(()=>{
const paths={settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>',project:'<path d="M3 7V5h7l2 3h9v12H3Z"/>',export:'<path d="M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5"/>',keyboard:'<rect x="2" y="5" width="20" height="14" rx="3"/><path d="M6 9h1m4 0h1m4 0h1M6 13h1m4 0h1m4 0h1M8 16h8"/>',appearance:'<circle cx="12" cy="12" r="9"/><path d="M12 3v18M12 7h5m-5 5h8m-8 5h5"/>',ai:'<path d="m12 3 3 6 6 3-6 3-3 6-3-6-6-3 6-3Z"/>',updates:'<path d="M20 8a8 8 0 1 0 0 8M20 3v5h-5"/>',heart:'<path d="M12 21 3 12C-2 4 8 0 12 7c4-7 14-3 9 5Z"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',select:'<rect x="3" y="3" width="18" height="18" rx="4"/><path d="m7 12 3 3 7-7"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>'};
const icon=name=>'<svg class="hub-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+paths[name]+'</svg>';
const header=document.querySelector('header'),brand=document.querySelector('.brand'),project=$('projectPanel');
brand.after(project);project.classList.add('header-project');$('newProject').textContent='＋';$('newProject').setAttribute('aria-label','New project');
const trigger=document.createElement('button');trigger.id='openSettingsHub';trigger.innerHTML=icon('settings')+'<span>Settings</span>';trigger.title='Project, export, keyboard and app settings';project.after(trigger);
const dialog=document.createElement('dialog');dialog.id='settingsHub';dialog.setAttribute('aria-labelledby','settingsHubTitle');dialog.innerHTML='<div class="hub-heading"><div><h2 id="settingsHubTitle">Make Lith yours</h2><p>Project preferences and app settings, together.</p></div><button id="closeSettingsHub" aria-label="Close settings">×</button></div><div class="hub-layout"><nav class="hub-tabs" role="tablist" aria-label="Settings categories"></nav><div class="hub-content"></div></div>';document.body.append(dialog);
const names={project:'Project',export:'Export',keyboard:'Keyboard',appearance:'Workspace',ai:'Local AI search',updates:'Updates & library'},panes={},tabs={};let currentTab='project';
for(const [key,name]of Object.entries(names)){const tab=document.createElement('button');tab.id='settingsTab-'+key;tab.type='button';tab.role='tab';tab.setAttribute('aria-controls','settingsPane-'+key);tab.innerHTML=icon(key)+'<span>'+name+'</span>';tab.dataset.category=key;tab.onclick=()=>open(key);dialog.querySelector('.hub-tabs').append(tab);tabs[key]=tab;const pane=document.createElement('section');pane.id='settingsPane-'+key;pane.role='tabpanel';pane.setAttribute('aria-labelledby',tab.id);pane.hidden=true;panes[key]=pane;dialog.querySelector('.hub-content').append(pane);}
// Reuse the existing settings controls and their persistence handlers.
panes.project.append($('projectForm'));for(const child of [...$('shortcutHelp').children])panes.keyboard.append(child);for(const child of [...$('updatesDialog').children])panes.updates.append(child);
const theme=document.querySelector('.theme-label');panes.appearance.innerHTML='<h3>Workspace & appearance</h3><p class="muted small">Choose a comfortable palette and arrange your editing space.</p>';panes.appearance.append(theme);
const customize=$('customizeWorkspace');panes.appearance.append(customize);customize.addEventListener('click',()=>dialog.close());
const quality=document.createElement('button');quality.id='settingsPreviewQuality';quality.onclick=()=>{$('maximumPreview').click();syncQuality();};panes.appearance.append(quality);function syncQuality(){quality.textContent=($('maximumPreview').getAttribute('aria-pressed')==='true'?'✓ ':'')+'Best display preview · recommended';quality.setAttribute('aria-pressed',$('maximumPreview').getAttribute('aria-pressed'));}
const second=document.createElement('section');second.innerHTML='<h3>Second monitor</h3><p class="small muted">Connect another display to enable a dedicated photo preview.</p>';second.append($('secondDisplayControls'));panes.appearance.append(second);
const ai=$('smartSearchOptions');ai.open=true;panes.ai.append(ai);
const aiButton=document.createElement('button');aiButton.id='galleryAISettings';aiButton.innerHTML=icon('ai');aiButton.title='Local AI search · indexing & settings';aiButton.setAttribute('aria-label',aiButton.title);aiButton.onclick=()=>open('ai');document.querySelector('.gallery-search-row').append(aiButton);
const searchIcon=document.createElement('span');searchIcon.className='gallery-search-icon';searchIcon.innerHTML=icon('search');document.querySelector('.gallery-search-row').prepend(searchIcon);
$('gallerySearchInput').placeholder='Search your photos…';$('gallerySearchInput').title='Search filenames, cameras and scenes automatically';
for(const [id,key]of [['all','grid'],['favorites','heart']]){const el=$(id);for(const node of [...el.childNodes])if(node.nodeType===3)node.remove();el.insertAdjacentHTML('afterbegin',icon(key));}
for(const [id,key,label]of [['libraryMode','grid','Gallery view'],['batchSelect','select','Select']]){const el=$(id);el.textContent='';el.insertAdjacentHTML('afterbegin',icon(key)+'<span>'+label+'</span>');}
const searchStatus=$('gallerySearchStatus');new MutationObserver(()=>searchStatus.title=searchStatus.textContent).observe(searchStatus,{childList:true,characterData:true,subtree:true});
function show(key){currentTab=key;dialog.dataset.category=key;if(key==='project'||key==='export')panes[key].append($('projectForm'));for(const [k,pane]of Object.entries(panes))pane.hidden=k!==key;for(const [k,tab]of Object.entries(tabs)){tab.setAttribute('aria-selected',String(k===key));tab.tabIndex=k===key?0:-1;}syncQuality();if(!dialog.open)dialog.showModal();dialog.querySelector('.hub-content').scrollTop=0;}
function open(key='project'){if(key==='project'||key==='export'){if(!dialog.open||!['project','export'].includes(currentTab))$('projectSettings').click();show(key);}else if(key==='keyboard')window.keyboardSettings.open();else if(key==='updates'){show('updates');}else show(key);}
function close(){dialog.close();}
trigger.onclick=()=>open('project');$('closeSettingsHub').onclick=close;dialog.addEventListener('close',()=>{$('shortcutHelp').dispatchEvent(new Event('close'));});
dialog.querySelector('.hub-tabs').addEventListener('keydown',e=>{if(!['ArrowDown','ArrowUp','ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const keys=Object.keys(tabs),i=keys.indexOf(currentTab),n=e.key==='Home'?0:e.key==='End'?keys.length-1:(i+(['ArrowDown','ArrowRight'].includes(e.key)?1:keys.length-1))%keys.length;open(keys[n]);tabs[keys[n]].focus();});
window.settingsHub={open,show,close,active:key=>dialog.open&&currentTab===key};
// The mode badge is redundant with the always-visible workspace.
header.querySelector('.mode').hidden=true;
})();
