const vm=require('node:vm'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
(async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'luma-test-'));const source=path.join(root,'sample.png'),dest=path.join(root,'export.png'),library=path.join(root,'library');await fs.writeFile(source,Buffer.from([137,80,78,71,13,10,26,10]));
async function load(){const handlers={};let ready;const dialog={showOpenDialog:async()=>({canceled:false,filePaths:[source]}),showSaveDialog:async()=>({canceled:false,filePath:dest}),showMessageBox:async()=>{throw Error('Unexpected catalog error');}};class Window{constructor(){this.webContents={setWindowOpenHandler(){},on(){}};}on(){} async loadFile(){}}
const electron={app:{setPath(){},whenReady:()=>({then:fn=>ready=fn()}),on(){},quit(){}},BrowserWindow:Window,ipcMain:{handle:(k,f)=>handlers[k]=f},dialog};vm.runInNewContext(await fs.readFile(path.join(__dirname,'main.cjs'),'utf8'),{require:n=>n==='electron'?electron:n==='./updater.cjs'?{setupUpdates(){}}:require(n),process:{env:{LUMA_DATA_DIR:library}},__dirname,Buffer,console,structuredClone});await ready;return {handlers,dialog};}
let {handlers:h,dialog}=await load();const imported=await h.import();assert.equal(imported.catalog.photos.length,1);const p=imported.catalog.photos[0];await h.save(null,{id:p.id,settings:{exposure:1,crop:1},favorite:true});assert.ok((await h.image(null,p.id)).startsWith('file:'));assert.deepEqual(await fs.readFile(path.join(library,'originals',p.id+'.png')),await fs.readFile(source));await h.export(null,{name:'sample.png',format:'png',base64:Buffer.from('export test').toString('base64')});assert.equal(await fs.readFile(dest,'utf8'),'export test');dialog.showSaveDialog=async()=>({canceled:true});assert.equal(await h.export(null,{name:'a',format:'png',base64:''}),false);dialog.showSaveDialog=async()=>({canceled:false,filePath:path.join(library,'originals',p.id+'.png')});await assert.rejects(()=>h.export(null,{name:'a',format:'png',base64:''}),/outside/);({handlers:h}=await load());const restored=h.catalog();assert.equal(restored.photos[0].favorite,true);assert.equal(restored.photos[0].settings.exposure,1);const originalProject=restored.activeProjectId;
await h.project(null,{type:'create',name:'Travel'});const travel=h.catalog().activeProjectId;assert.notEqual(travel,originalProject);assert.equal(h.catalog().selected,null);
await h.project(null,{type:'update',id:travel,settings:{format:'png',quality:80,size:2048,notes:'Night photos'}});
await h.save(null,{id:p.id,settings:{exposure:2}});assert.equal(h.catalog().activeProjectId,travel);assert.equal(h.catalog().selected,null);
await h.project(null,{type:'move',id:travel,photoId:p.id});assert.equal(h.catalog().photos[0].projectId,travel);
({handlers:h}=await load());assert.equal(h.catalog().activeProjectId,travel);assert.equal(h.catalog().projects.find(p=>p.id===travel).settings.size,2048);assert.equal(h.catalog().photos[0].settings.exposure,2);
await h.project(null,{type:'switch',id:originalProject});assert.equal(h.catalog().selected,null);
await assert.rejects(()=>h.project(null,{type:'move',id:'missing',photoId:p.id}),/Project not found/);
const copied=await h['virtual-copy'](null,p.id),copy=copied.catalog.photos.find(photo=>photo.id===copied.id);assert.equal(copy.sourceId,p.id);assert.equal(await h.image(null,copy.id),await h.image(null,p.id));await h.save(null,{id:copy.id,settings:{exposure:-1}});assert.equal(h.catalog().photos.find(photo=>photo.id===p.id).settings.exposure,2);assert.equal((await fs.readdir(path.join(library,'originals'))).length,1);const restoredFolder=path.join(root,'restored-copies');await require('./library.cjs').importLibrary(library,restoredFolder);assert.equal((await fs.readdir(path.join(restoredFolder,'originals'))).length,1);assert.equal(JSON.parse(await fs.readFile(path.join(restoredFolder,'catalog.json'),'utf8')).photos.length,2);
console.log('Passed: local import copy, saved edits, favorites, catalog restart, data loading, export writing, cancellation and original-file protection.');})().catch(e=>{console.error(e);process.exitCode=1});

