(()=>{
const right=document.querySelector('.right'),editor=document.querySelector('.node-editor');right.querySelector('.edit-heading').after(editor);const blendPanel=document.createElement('details');blendPanel.id='blendPanel';blendPanel.open=true;blendPanel.innerHTML='<summary>◈ Effect blend</summary><div id="effectMixes"></div><label class="select-row">Add to node<select id="addEffectType" aria-label="Add effect type"></select></label><button id="mergeEffect">＋ Combine effect</button><p class="small muted">Effects run top to bottom. Blend each effect, then blend the whole node.</p>';
editor.after(blendPanel);for(const [id,label]of [...FX.nodeTypes,['diffusion','Diffusion / mist'],['glow','Glow / bloom'],['halation','Halation'],['flare','Anamorphic flare'],['grain','Grain'],['fade','Fade'],['matte','Matte shadows']])$('addEffectType').append(new Option(label,id));
const targetLabel=$('editTarget').closest('label');targetLabel.className='target-picker';editor.before(targetLabel);const setup=document.createElement('details');setup.id='nodeSetup';setup.innerHTML='<summary>◈ Node setup & blending</summary>';editor.before(setup);setup.append(editor,blendPanel);let setupTarget='initial';
let mixSignature='';const node=()=>documentSettings.nodes.find(n=>n.uid===activeNodeUid);
function mixRow(label,value,apply){const row=document.createElement('label');row.className='mix-row';const text=document.createElement('span');text.textContent=label;const out=document.createElement('output');out.textContent=value+'%';const input=document.createElement('input');input.type='range';input.min=0;input.max=100;input.value=value;input.setAttribute('aria-label',label+' blend');let started=false;input.oninput=()=>{if(!started){pushHistory();started=true;}apply(Number(input.value));out.textContent=input.value+'%';scheduleRender();};input.onchange=()=>{started=false;save();render();};row.append(text,out,input);return row;}
function syncMix(){const n=node();if(setupTarget!==activeNodeUid){setupTarget=activeNodeUid;setup.open=false;}const effects=n?(n.operations||[{type:n.operation,mix:100}]):[];const sig=JSON.stringify([activeNodeUid,n?.mix,documentSettings.developMix,effects,!!img]);if(sig===mixSignature)return;mixSignature=sig;const box=$('effectMixes');box.replaceChildren(mixRow(n?'Whole node':'Base photo',n?(n.mix??100):(documentSettings.developMix??100),v=>{if(n)n.mix=v;else documentSettings.developMix=v;}));effects.forEach((effect,i)=>{const row=mixRow(effect.type==='develop'?'Full Develop':($('addEffectType').querySelector('option[value="'+effect.type+'"]')?.textContent||effect.type),effect.mix??100,v=>{n.operations||=effects;n.operations[i].mix=v;});if(effects.length>1){const remove=document.createElement('button');remove.textContent='×';remove.title='Remove effect from node';remove.onclick=()=>mutate(()=>{n.operations=effects.filter((_,j)=>j!==i);n.operation=n.operations[0].type;});row.append(remove);}box.append(row);});box.querySelectorAll('input').forEach(e=>e.disabled=!img);$('mergeEffect').disabled=!img||!n||effects.length>=8;$('addEffectType').disabled=!img||!n;}
$('mergeEffect').onclick=()=>{const n=node();if(!n)return;const type=$('addEffectType').value;const effects=n.operations||[{type:n.operation,mix:100}];const covers=t=>t==='develop'?FX.nodeTypes.map(o=>o[0]).filter(o=>!['bloom','film'].includes(o)).concat(['diffusion','glow','halation','flare','grain','fade','matte']):t==='bloom'?['diffusion','glow','halation','flare']:t==='film'?['grain','fade','matte']:[t];if(effects.some(e=>covers(e.type).some(t=>covers(type).includes(t)))){toast('This node already includes those tools. Choose a specific operation first, or add a separate node for another pass.');return;}mutate(()=>{n.operations=[...effects,{type,mix:100}];});};
// Compact workspace controls remain visible even with the side panels hidden.
const focus=document.createElement('button');focus.id='focusView';focus.textContent='⛶ Focus';focus.title='Expand photo area';document.querySelector('.canvas-tools').firstElementChild.append(focus);focus.onclick=()=>{document.body.classList.toggle('focus-view');focus.classList.toggle('active',document.body.classList.contains('focus-view'));layout();};
const contact=document.createElement('button');contact.id='toggleContact';contact.textContent='▦ Contact sheet';contact.setAttribute('aria-expanded','true');document.querySelector('.film-header').firstElementChild.prepend(contact);contact.onclick=()=>{const collapsed=document.body.classList.toggle('contact-collapsed');contact.setAttribute('aria-expanded',String(!collapsed));layout();};
$('toggleNodes').onclick=()=>{const collapsed=document.body.classList.toggle('nodes-collapsed');$('toggleNodes').setAttribute('aria-expanded',String(!collapsed));layout();};
const frame=$('photoFrame'),stage=$('stage');frame.title='Double-click to zoom here. Drag to pan when zoomed.';
frame.addEventListener('dblclick',e=>{if(!img||window.maskUI?.isEditing()||window.reviewUI?.isCropping()||(e.target!==$('photo')&&e.target!==frame))return;const r=$('photo').getBoundingClientRect(),nx=(e.clientX-r.left)/r.width,ny=(e.clientY-r.top)/r.height;zoom=zoom?0:1;layout();if(zoom){const now=$('photo').getBoundingClientRect();stage.scrollLeft+=now.left+nx*now.width-e.clientX;stage.scrollTop+=now.top+ny*now.height-e.clientY;}else stage.scrollTo(0,0);render();});
let pan=null;frame.addEventListener('pointerdown',e=>{if(!zoom||e.button!==0||e.target!==$('photo')||window.maskUI?.isEditing()||window.reviewUI?.isCropping())return;pan={id:e.pointerId,x:e.clientX,y:e.clientY,l:stage.scrollLeft,t:stage.scrollTop};frame.setPointerCapture(e.pointerId);frame.classList.add('panning');});frame.addEventListener('pointermove',e=>{if(!pan||pan.id!==e.pointerId)return;stage.scrollLeft=pan.l+pan.x-e.clientX;stage.scrollTop=pan.t+pan.y-e.clientY;});for(const type of ['pointerup','pointercancel'])frame.addEventListener(type,()=>{pan=null;frame.classList.remove('panning');});
$('fit').onclick=()=>{zoom=0;layout();stage.scrollTo(0,0);render();};for(const [id,mult]of [['zoomIn',1.25],['zoomOut',.8]])$(id).onclick=()=>{zoom=Math.max(.05,Math.min(4,(zoom||$('photo').clientWidth/(img?.naturalWidth||1400))*mult));layout();render();};
// Direct tone curve editing, using the exact same mapping as the renderer.
const curve=$('curveGraph'),keys=['curveBlack','curveShadow','curveMid','curveHighlight','curveWhite'];curve.setAttribute('aria-label','Tone curve. Drag the five points, or use the labelled sliders below.');let drag=-1;
function drawCurve(){const ctx=curve.getContext('2d');ctx.clearRect(0,0,256,120);ctx.strokeStyle='#88998855';ctx.lineWidth=1;for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(i*64,0);ctx.lineTo(i*64,120);ctx.moveTo(0,i*30);ctx.lineTo(256,i*30);ctx.stroke();}ctx.strokeStyle='#8dab72';ctx.beginPath();ctx.moveTo(0,120);ctx.lineTo(256,0);ctx.stroke();ctx.strokeStyle='#bbd59b';ctx.lineWidth=2;ctx.beginPath();for(let x=0;x<=256;x++)ctx.lineTo(x,120-FX.curveValue(x/256,settings)*120);ctx.stroke();keys.forEach((key,i)=>{ctx.beginPath();ctx.arc(Math.max(5,Math.min(251,i*64)),Math.max(5,Math.min(115,120-FX.curveValue(i/4,settings)*120)),4,0,Math.PI*2);ctx.fillStyle=settings[key]!==Imaging.defaults[key]?'#f1c27c':'#d5edaa';ctx.fill();});}
function moveCurve(e){if(drag<0)return;const r=curve.getBoundingClientRect(),y=Math.max(0,Math.min(1,1-(e.clientY-r.top)/r.height)),input=$(keys[drag]);settings[keys[drag]]=Math.max(Number(input.min),Math.min(Number(input.max),Math.round((y-drag/4)*100)));input.value=settings[keys[drag]];syncValues();drawCurve();scheduleRender();}
curve.onpointerdown=e=>{if(!img||!window.nodeUI.canEdit('curveMid'))return;pushHistory();const r=curve.getBoundingClientRect();drag=Math.max(0,Math.min(4,Math.round((e.clientX-r.left)/r.width*4)));curve.setPointerCapture(e.pointerId);moveCurve(e);};curve.onpointermove=moveCurve;curve.onpointerup=curve.onpointercancel=()=>{if(drag<0)return;drag=-1;save();render();};curve.ondblclick=()=>{if(img&&window.nodeUI.canEdit('curveMid'))mutate(()=>keys.forEach(k=>settings[k]=0));};
const curvePresets=document.createElement('div');curvePresets.className='curve-presets';curve.after(curvePresets);for(const [name,values]of [['Linear',[0,0,0,0,0]],['Soft S',[0,-8,0,8,0]],['Matte',[12,4,0,-4,-6]]]){const b=document.createElement('button');b.textContent=name;b.onclick=()=>{if(window.nodeUI.canEdit('curveMid'))mutate(()=>keys.forEach((k,i)=>settings[k]=values[i]));};curvePresets.append(b);}
// Related adjustments live within their parent tool tabs.
curve.closest('details').dataset.toolgroup='light';document.querySelector('.color-chips').closest('details').dataset.toolgroup='color';$('gradeShadows').closest('details').dataset.toolgroup='color';
const labels={light:'☀ Light',color:'◒ Color',detail:'◇ Detail',effects:'✧ Effects',mask:'◌ Masks',frame:'▣ Frame'};document.querySelectorAll('[data-tool]').forEach(b=>{if(labels[b.dataset.tool])b.textContent=labels[b.dataset.tool];b.dataset.label=b.textContent;});
for(const [id,label,title]of [['addBrush','✎ Brush','Paint exactly where you want an edit'],['addLinear','▥ Gradient','Drag a gradual transition across the image'],['addRadial','◎ Radial','Draw an elliptical spotlight'],['maskAddColor','◉ Color','Pick a color in the photo and adjust its range']]){$(id).textContent=label;$(id).title=title;}
function changed(k,p=settings){return Imaging.defaults[k]!==undefined&&JSON.stringify(p[k]??Imaging.defaults[k])!==JSON.stringify(Imaging.defaults[k]);}
function indicators(){document.querySelectorAll('.slider-row input[id]').forEach(input=>{if(Imaging.defaults[input.id]===undefined)return;const modified=changed(input.id);input.closest('.slider-row').classList.toggle('modified',modified);input.title=modified?'Changed · double-click to reset':'Double-click to reset';});document.querySelectorAll('[data-tool]').forEach(b=>{const ids=[...document.querySelectorAll('[data-toolgroup="'+b.dataset.tool+'"] input[id]')].map(e=>e.id);let count=ids.filter(k=>changed(k)).length;if(b.dataset.tool==='mask')count=(settings.masks||[]).length;b.textContent=(b.dataset.label||b.textContent)+(count?' · '+count:'');b.classList.toggle('has-edits',count>0);});for(const b of document.querySelectorAll('.effect-node')){const n=documentSettings.nodes.find(n=>n.uid===b.dataset.node);if(!n)continue;const count=Object.keys(Imaging.defaults).filter(k=>!['nodes','_schema'].includes(k)&&window.nodeUI.canEdit(k,n)&&changed(k,n.adjustments)).length;b.dataset.edits=count;b.title=n.label+' · '+count+' changed settings · '+(n.operations?.length||1)+' effect(s) · '+(n.mix??100)+'% blend';let badge=b.querySelector('.node-edits');if(!badge){badge=document.createElement('b');badge.className='node-edits';b.append(badge);}badge.textContent=count?'● '+count:'○';}}
const search=document.createElement('input');search.type='search';search.id='lookSearch';search.placeholder='Search film, vintage, dreamy…';search.setAttribute('aria-label','Search looks');$('presetFamily').before(search);$('presetFamily').append(new Option('Vintage looks','vintage'));function filterLooks(){const family=$('presetFamily').value,q=search.value.toLowerCase();document.querySelectorAll('.preset').forEach(b=>{const text=b.textContent.toLowerCase();const match=family==='all'||family==='stock'&&text.includes('inspired')||family==='dream'&&text.startsWith('dream')||family==='35mm'&&text.startsWith('35mm')||family==='vintage'&&text.startsWith('vintage');b.hidden=!match||!text.includes(q);});}search.oninput=filterLooks;$('presetFamily').onchange=filterLooks;document.querySelectorAll('.left .section-title span').forEach(e=>e.textContent=looks.length+' LOOKS');
window.studioUI={sync:()=>{syncMix();indicators();drawCurve();},indicators,curve:drawCurve};sync();window.advancedUI.setTool('light');
})();

