(()=>{
let selected=null,target=null,active=false,drag=null;
const tab=document.createElement('button');tab.dataset.tool='text';tab.dataset.label='T Text';tab.textContent='T Text';document.querySelector('.tool-tabs').append(tab);
const panel=document.createElement('details');panel.id='textPanel';panel.dataset.toolgroup='text';panel.open=true;panel.hidden=true;panel.innerHTML='<summary>Cinematic text</summary><div id="textStyles"></div><p class="small muted">Add a style, type your words, then drag the text on the photo. Saved in the selected node.</p><div id="textLayers"></div><div id="textProperties"><label class="text-field">Your text<textarea id="textContent" rows="3" maxlength="600" placeholder="Write a title or caption"></textarea></label><div class="text-pair"><label>Font<select id="textFont"><option>Georgia</option><option>Arial</option><option>Courier New</option><option>Times New Roman</option></select></label><label>Alignment<select id="textAlign"><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label></div><div class="text-pair"><label>Color<input id="textColor" type="color"></label><label><input id="textItalic" type="checkbox"> Italic</label><label><input id="textBold" type="checkbox"> Bold</label></div><div id="textSliders"></div><div class="text-actions"><button id="textToggle">Hide text</button><button id="textDuplicate">Duplicate</button><button id="textDelete">Delete</button></div></div>';
document.querySelector('.right').insertBefore(panel,document.querySelector('.edit-foot'));const handle=document.createElement('div');handle.id='textHandle';handle.hidden=true;handle.tabIndex=0;handle.setAttribute('role','button');handle.setAttribute('aria-label','Move selected text. Drag or use arrow keys.');$('photoFrame').append(handle);
$('textFont').replaceChildren();for(const [group,names]of TextFX.fonts){const optgroup=document.createElement('optgroup');optgroup.label=group;for(const name of names)optgroup.append(new Option(name,name));$('textFont').append(optgroup);}
const layers=()=>settings.textLayers||[],currentLayer=()=>layers().find(l=>l.id===selected);
const styles=[['Film title',{text:'A MOMENT IN TIME',font:'Georgia',size:5,tracking:.13,y:75}],['Subtitle',{text:'Somewhere, everything felt still.',font:'Arial',size:2.8,tracking:.02,y:89}],['Editorial',{text:'The quiet\nbetween moments.',font:'Georgia',italic:true,size:6,tracking:0,x:12,y:70,align:'left'}],['Credits',{text:'A FILM BY YOU\nSHOT WITH FEELING',font:'Arial',size:2,tracking:.2,y:85}],['Date stamp',{text:'24 SEP 2026',font:'Courier New',size:2.3,tracking:.05,color:'#ffbc6b',x:92,y:92,align:'right'}]];
for(const [name,values]of styles){const b=document.createElement('button');b.textContent=name;b.dataset.textStyle=name;b.onclick=()=>{if(layers().length>=12)return;mutate(()=>{const layer={...TextFX.make(),...values};if(name==='Date stamp')layer.text=new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date()).toUpperCase();settings.textLayers=[...layers(),layer];selected=layer.id;});};$('textStyles').append(b);}
function change(key,value){if(!currentLayer())return;mutate(()=>currentLayer()[key]=value);}
let typing=false;$('textContent').oninput=()=>{const l=currentLayer();if(!l)return;if(!typing){pushHistory();typing=true;}l.text=$('textContent').value;scheduleRender();place();};$('textContent').onchange=()=>{typing=false;save();render();};
for(const [id,key]of [['textFont','font'],['textAlign','align'],['textColor','color'],['textItalic','italic'],['textBold','bold']])$(id).onchange=()=>change(key,$(id).type==='checkbox'?$(id).checked:$(id).value);
const controls=[['size','Size',1,18,.1],['tracking','Letter spacing',-.05,.6,.01],['lineHeight','Line spacing',.8,2.5,.05],['opacity','Opacity',0,100,1],['shadow','Shadow',0,100,1],['x','Horizontal position',0,100,1],['y','Vertical position',0,100,1]];
for(const [key,label,min,max,step]of controls){const row=document.createElement('label');row.className='text-range';row.textContent=label;const out=document.createElement('output');out.id='textOut-'+key;const input=document.createElement('input');Object.assign(input,{id:'text-'+key,type:'range',min,max,step});input.setAttribute('aria-label','Text '+label.toLowerCase());let started=false;input.oninput=()=>{const l=currentLayer();if(!l)return;if(!started){pushHistory();started=true;}l[key]=Number(input.value);out.textContent=input.value;scheduleRender();place();};input.onchange=()=>{started=false;save();render();};row.append(out,input);$('textSliders').append(row);}
$('textToggle').onclick=()=>change('enabled',currentLayer()?.enabled===false);$('textDelete').onclick=()=>mutate(()=>{settings.textLayers=layers().filter(l=>l.id!==selected);selected=null;});$('textDuplicate').onclick=()=>{if(!currentLayer()||layers().length>=12)return;mutate(()=>{const l={...structuredClone(currentLayer()),id:crypto.randomUUID(),y:Math.min(95,currentLayer().y+7)};settings.textLayers=[...layers(),l];selected=l.id;});};
function place(){const l=currentLayer(),photo=$('photo');handle.hidden=!active||!img||!l||l.enabled===false||!l.text||comparing||$('reviewMode').value!=='edited'||documentSettings.nodes.find(n=>n.uid===activeNodeUid)?.enabled===false||!$('sideComparison').hidden||document.querySelector('[data-tool="text"]')?.getAttribute('aria-pressed')!=='true';if(handle.hidden)return;const ctx=photo.getContext('2d');ctx.save();const box=TextFX.layout(ctx,photo,l);ctx.restore();const sx=photo.clientWidth/photo.width,sy=photo.clientHeight/photo.height;Object.assign(handle.style,{left:(box.left*sx-5)+'px',top:(box.top*sy-5)+'px',width:(box.width*sx+10)+'px',height:(box.height*sy+10)+'px'});}
handle.onpointerdown=e=>{if(e.button!==0||!currentLayer())return;e.preventDefault();e.stopPropagation();pushHistory();drag={id:e.pointerId,x:e.clientX,y:e.clientY,startX:currentLayer().x,startY:currentLayer().y};handle.setPointerCapture(e.pointerId);};handle.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;const l=currentLayer();l.x=Math.max(0,Math.min(100,drag.startX+(e.clientX-drag.x)/$('photo').clientWidth*100));l.y=Math.max(0,Math.min(100,drag.startY+(e.clientY-drag.y)/$('photo').clientHeight*100));place();scheduleRender();};handle.onpointerup=handle.onpointercancel=()=>{if(!drag)return;drag=null;save();render();};handle.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();e.stopPropagation();const key=['ArrowLeft','ArrowRight'].includes(e.key)?'x':'y',step=(e.shiftKey?5:1)*(['ArrowLeft','ArrowUp'].includes(e.key)?-1:1);change(key,Math.max(0,Math.min(100,currentLayer()[key]+step)));};
let signature='';function syncText(){const t=(current?.id||'')+'|'+activeNodeUid;if(t!==target){target=t;selected=null;typing=false;}if(!layers().some(l=>l.id===selected))selected=layers().at(-1)?.id||null;const l=currentLayer();const sig=JSON.stringify(layers().map(l=>[l.id,l.text,l.enabled]))+'|'+selected;if(sig!==signature){signature=sig;$('textLayers').replaceChildren();for(const item of layers()){const b=document.createElement('button');b.textContent=(item.enabled===false?'○ ':'T ')+(item.text.replace(/\n/g,' ').slice(0,28)||'Empty text');b.classList.toggle('active',item.id===selected);b.onclick=()=>{selected=item.id;syncText();};$('textLayers').append(b);}}$('textProperties').hidden=!l;document.querySelectorAll('[data-text-style]').forEach(b=>b.disabled=!img||layers().length>=12);if(l){if(document.activeElement!==$('textContent'))$('textContent').value=l.text;for(const [id,key]of [['textFont','font'],['textAlign','align'],['textColor','color']])$(id).value=l[key];$('textItalic').checked=!!l.italic;$('textBold').checked=!!l.bold;for(const [key]of controls){$('text-'+key).value=l[key];$('textOut-'+key).textContent=Number(l[key]).toFixed(key==='tracking'?2:1).replace(/\.0$/,'');}$('textToggle').textContent=l.enabled===false?'Show text':'Hide text';$('textDuplicate').disabled=layers().length>=12;}tab.textContent='T Text'+(layers().length?' · '+layers().length:'');place();}
const setTool=window.advancedUI.setTool;window.advancedUI.setTool=tool=>{active=tool==='text';setTool(tool);if(active){panel.open=true;if($('reviewMode').value!=='edited'){$('reviewMode').value='edited';$('reviewMode').dispatchEvent(new Event('change'));}}place();};document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>window.advancedUI.setTool(b.dataset.tool));
window.textUI={sync:syncText,layout:place};syncText();
})();
