(function(scope){
if(typeof module==='undefined'&&!scope.LithFontCatalog&&typeof importScripts==='function')importScripts('font-catalog.js');
const bundled=typeof module!=='undefined'?require('./font-catalog.js'):scope.LithFontCatalog;
const loaded=new Map();
async function loadFont(name){const family=bundled.find(f=>f.name===name);if(!family||typeof FontFace==='undefined')return;if(!loaded.has(name)){const promise=Promise.all(family.faces.map(async item=>{const face=new FontFace(name,'url("fonts/'+item.file.split('/').map(encodeURIComponent).join('/')+'")',{style:item.style,weight:item.weight});await face.load();(scope.document?.fonts||scope.fonts).add(face);}));loaded.set(name,promise);promise.catch(()=>loaded.delete(name));}return loaded.get(name);}
async function ensure(s){const names=new Set();for(const l of s.textLayers||[])if(l.enabled!==false&&l.text)names.add(l.font);for(const n of s.nodes||[])if(n.enabled!==false&&n.mix!==0)for(const l of n.adjustments?.textLayers||[])if(l.enabled!==false&&l.text)names.add(l.font);await Promise.all([...names].map(loadFont));}

const fonts=[['Cinematic serif · included',['Cinzel','Cormorant Garamond','Playfair Display','Bodoni Moda','EB Garamond','Libre Baskerville']],['Title cards · included',['Bebas Neue','Oswald','Anton']],['Clean captions · included',['Josefin Sans','Montserrat','Raleway']],['Typewriter · included',['Courier Prime','Space Mono']],['Handwritten · included',['Caveat','Sacramento']],['System serif',['Georgia','Times New Roman','Cambria','Palatino Linotype']],['System sans serif',['Arial','Calibri','Candara','Segoe UI','Trebuchet MS','Verdana']],['System display',['Impact','Bahnschrift']],['System handwritten',['Gabriola','Segoe Script','Segoe Print','Comic Sans MS']],['System monospace',['Courier New','Consolas']]];
const make=()=>({id:globalThis.crypto.randomUUID(),text:'A MOMENT IN TIME',font:'Georgia',size:5,tracking:.12,lineHeight:1.25,x:50,y:78,align:'center',color:'#ffffff',opacity:100,shadow:35,italic:false,bold:false,enabled:true});
function layout(ctx,c,l){let size=Math.min(c.width,c.height)*(l.size||5)/100;const family=fonts.some(([,names])=>names.includes(l.font))?l.font:'Georgia';const set=()=>ctx.font=(l.italic?'italic ':'')+(l.bold?'bold ':'')+size+'px "'+family+'"';set();const lines=String(l.text||'').slice(0,600).split('\n').slice(0,12),spacing=()=>size*(l.tracking||0),measure=t=>Array.from(t).reduce((a,ch)=>a+ctx.measureText(ch).width,0)+Math.max(0,Array.from(t).length-1)*spacing();let width=Math.max(1,...lines.map(measure));if(width>c.width*.92){size*=c.width*.92/width;set();width=Math.max(1,...lines.map(measure));}const height=size*(1+(lines.length-1)*(l.lineHeight||1.25)),x=c.width*(l.x??50)/100,y=c.height*(l.y??78)/100,align=['left','center','right'].includes(l.align)?l.align:'center';return {lines,size,width,height,x,y,left:x-(align==='center'?width/2:align==='right'?width:0),top:y-height/2,spacing:spacing(),measure,align};}
function draw(c,l,mix=100){if(l.enabled===false||!l.text||!l.opacity)return;const ctx=c.getContext('2d');ctx.save();const a=layout(ctx,c,l);ctx.globalAlpha=Math.max(0,Math.min(1,(l.opacity??100)/100*mix/100));ctx.fillStyle=/^#[\da-f]{6}$/i.test(l.color)?l.color:'#ffffff';ctx.textBaseline='top';ctx.shadowColor='rgba(0,0,0,'+(l.shadow||0)/100+')';ctx.shadowBlur=a.size*.15;ctx.shadowOffsetY=a.size*.035;for(const [i,line]of a.lines.entries()){let x=a.x-(a.align==='center'?a.measure(line)/2:a.align==='right'?a.measure(line):0);for(const ch of Array.from(line)){ctx.fillText(ch,x,a.top+i*a.size*(l.lineHeight||1.25));x+=ctx.measureText(ch).width+a.spacing;}}ctx.restore();}
function render(c,s){for(const l of s.textLayers||[])draw(c,l);for(const n of s.nodes||[])if(n.enabled!==false)for(const l of n.adjustments?.textLayers||[])draw(c,l,n.mix??100);return c;}
const api={bundled,loadFont,ensure,fonts,make,layout,render};if(typeof module!=='undefined')module.exports=api;else scope.TextFX=api;
})(globalThis);
