const TiledEngine=(()=>{
const tileSize=768;
function plan(s,w,h){let halo=0,reason=(s.rotation||s.straighten||s.flip||s.flipV||s.crop||(s.cropScale??100)!==100)?'Transformed geometry uses the whole-image sampler to preserve exact interpolation.':'';const radius=r=>halo+=3*Math.max(1,Math.round(r));
 function operation(p){if(p.prism||p.doubleAmount||p.flare||p.vignette||p.grain||p.matte||(p.masks||[]).some(m=>m.enabled!==false)||(p.textLayers||[]).length){reason='This stack contains an operation that needs whole-image context.';return;}
 if(p.denoise)radius(Math.max(.5,Math.min(w,h)*.0015));for(const [amount,r]of [[p.clarity,.014],[p.texture,.0023],[p.sharpen,.0008]])if(amount)radius(Math.max(.5,Math.min(w,h)*r));
 if(p.diffusion){radius(Math.max(w,h)*(.0004+p.diffusionRadius*.00006));if(p.diffusionScatter)radius(Math.max(w,h)*(.004+p.diffusionRadius*.00035));}
 if(p.glow)radius(Math.max(w,h)*(.001+p.glowRadius*.0004));if(p.halation){const r=Math.max(w,h)*(.001+p.halationRadius*.00035);for(const [mult,amount]of [[.22,p.halationTight],[1,p.halationMid],[3.1,p.halationWide]])if(amount)radius(Math.max(.7,r*mult));}}
 function node(n){if(n.enabled===false||n.mix===0)return;if(n.legacyStage)node(n.legacyStage);for(const op of n.operations||[{mix:100}])if(op.mix!==0)operation({...Imaging.defaults,...n.adjustments});for(const l of n.looks||[])if(l.enabled!==false&&l.amount!==0){if(l.values?.recipeNodes)l.values.recipeNodes.forEach(node);else operation({...Imaging.defaults,...l.values});}}
 operation({...Imaging.defaults,...s});(s.nodes||[]).forEach(node);if(s.border||s.textLayers?.length)reason='Frame or text compositing requires the whole output.';if(halo>384)reason='The optical radius needs a larger neighborhood than a memory-efficient tile.';return {eligible:!reason,reason,halo:Math.ceil(halo)+2,tileSize};}
function forSource(source,precise,s,max=0){const w=source.width||source.naturalWidth,h=source.height||source.naturalHeight,g=Imaging.geometry(w,h,s,max),p=plan(s,g.width,g.height);if(!precise&&(g.width!==w||g.height!==h))return {...p,eligible:false,reason:'Resized browser sources use the whole-image sampler to preserve exact interpolation.'};return p;}
async function* strips(source,precise,s,max,backend='auto',stripHeight=256,sharpening=null){const g=Imaging.geometry(source.width||source.naturalWidth,source.height||source.naturalHeight,s,max),p=forSource(source,precise,s,max);if(!p.eligible)throw Error(p.reason);if(sharpening&&sharpening.mode!=='off')p.halo+=6;for(let y=0;y<g.height;y+=stripHeight){const height=Math.min(stripHeight,g.height-y),data=new Float32Array(g.width*height*4);for(let x=0;x<g.width;x+=tileSize){const width=Math.min(tileSize,g.width-x),left=Math.max(0,x-p.halo),top=Math.max(0,y-p.halo),right=Math.min(g.width,x+width+p.halo),bottom=Math.min(g.height,y+height+p.halo),r=await FloatEngine.render(source,precise,s,max,false,backend,{x:left,y:top,width:right-left,height:bottom-top});if(sharpening&&sharpening.mode!=='off'){const smooth=FloatKernels.blur(r.data,r.width,r.height,sharpening.mode==='print'?1.8:1),amount={low:.35,standard:.65,high:1}[sharpening.amount]??.65;for(let i=0;i<r.data.length;i+=4){const delta=(r.data[i]-smooth[i])*.2126+(r.data[i+1]-smooth[i+1])*.7152+(r.data[i+2]-smooth[i+2])*.0722;if(Math.abs(delta)>2)for(let k=0;k<3;k++)r.data[i+k]+=Math.max(-32,Math.min(32,delta*amount));}}for(let row=0;row<height;row++)data.set(r.data.subarray(((y-top+row)*r.width+x-left)*4,((y-top+row)*r.width+x-left+width)*4),(row*g.width+x)*4);}yield {data,width:g.width,height,y};}}
async function render(source,precise,s,max,backend='auto'){const g=Imaging.geometry(source.width||source.naturalWidth,source.height||source.naturalHeight,s,max),data=new Float32Array(g.width*g.height*4);for await(const strip of strips(source,precise,s,max,backend,512))data.set(strip.data,strip.y*g.width*4);return {data,width:g.width,height:g.height,canvas:FloatEngine.toCanvas(data,g.width,g.height),backend:'tiled-float32',precision:32,sourceBits:precise?16:8};}
return {plan,forSource,render,strips};})();
