const {app,ipcMain,shell,net}=require('electron');
const RELEASES='https://github.com/skarn03/lith/releases';
function newer(candidate,current){const parse=v=>/^v?(\d+)\.(\d+)\.(\d+)$/.exec(v||'')?.slice(1).map(Number),a=parse(candidate),b=parse(current);if(!a||!b)return false;for(let i=0;i<3;i++){if(a[i]!==b[i])return a[i]>b[i];}return false;}
function setupUpdates(win,prepareQuit){let state={status:'idle',version:app.getVersion(),message:'Check for a new version of Lith.'},updater=null,busy=false,installing=false;const send=next=>{state={...state,...next};if(!win.isDestroyed())win.webContents.send('update-status',state);};
const supported=app.isPackaged&&(process.platform==='win32'||process.platform==='darwin'&&process.env.LITH_SIGNED_MAC==='1'),manualMac=app.isPackaged&&process.platform==='darwin'&&!supported;
state.canInstall=supported;
// Unsigned Mac test builds can detect releases, but cannot use Squirrel.Mac installation.
if(supported){updater=require('electron-updater').autoUpdater;updater.autoDownload=true;updater.autoInstallOnAppQuit=false;updater.allowPrerelease=false;updater.on('checking-for-update',()=>send({status:'checking',message:'Checking for updates…'}));updater.on('update-available',info=>send({status:'downloading',message:'Downloading Lith '+info.version+'…',nextVersion:info.version,percent:0}));updater.on('download-progress',p=>send({status:'downloading',percent:Math.round(p.percent),message:'Downloading update · '+Math.round(p.percent)+'%'}));updater.on('update-not-available',()=>send({status:'current',nextVersion:null,percent:0,message:'You have the latest version.'}));updater.on('update-downloaded',info=>send({status:'ready',nextVersion:info?.version||state.nextVersion,percent:100,message:'Update ready. Save and restart to install.'}));updater.on('error',()=>send({status:'error',message:'Update check failed. Your edits are safe. Try again later.'}));}
else state={...state,status:manualMac?'idle':'manual',message:manualMac?'Lith checks for new releases automatically. This unsigned Mac build requires a manual download.':'Automatic updates are available in the installed app.'};
async function check(){if(!updater&&!manualMac)return state;if(busy||state.status==='ready'||state.status==='downloading')return state;busy=true;try{if(updater)await updater.checkForUpdates();else{send({status:'checking',message:'Checking for updates…'});const response=await net.fetch('https://api.github.com/repos/skarn03/lith/releases/latest',{headers:{Accept:'application/vnd.github+json'},signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Release server unavailable');const release=await response.json();if(!release.draft&&!release.prerelease&&newer(release.tag_name,state.version))send({status:'available',nextVersion:release.tag_name.replace(/^v/,''),message:'A new version is available. Download and replace Lith in Applications.'});else send({status:'current',nextVersion:null,message:'You have the latest version.'});}}catch{send({status:'error',message:'Could not reach the release server. Try again later.'});}finally{busy=false;}return state;}
ipcMain.handle('update-status',()=>state);ipcMain.handle('update-check',check);ipcMain.handle('release-page',()=>shell.openExternal(RELEASES));ipcMain.handle('update-install',async()=>{if(!updater||state.status!=='ready'||installing)return false;installing=true;try{await prepareQuit();updater.quitAndInstall(false,true);return true;}catch(e){installing=false;throw e;}});if(updater||manualMac){const timer=setTimeout(check,3000);timer.unref?.();const interval=setInterval(check,4*60*60*1000);interval.unref?.();app.on('before-quit',()=>{clearTimeout(timer);clearInterval(interval);});}return {check};}
module.exports={setupUpdates,newer};
