const {app,ipcMain,shell}=require('electron');
const RELEASES='https://github.com/skarn03/lith/releases';
function setupUpdates(win,prepareQuit){let state={status:'idle',version:app.getVersion(),message:'Check for a new version of Lith.'},updater=null,busy=false;const send=next=>{state={...state,...next};if(!win.isDestroyed())win.webContents.send('update-status',state);};
const supported=app.isPackaged&&(process.platform==='win32'||process.platform==='darwin'&&process.env.LITH_SIGNED_MAC==='1');
// Unsigned Mac test builds cannot use Squirrel.Mac automatic installation.
if(supported){updater=require('electron-updater').autoUpdater;updater.autoDownload=true;updater.autoInstallOnAppQuit=false;updater.allowPrerelease=false;updater.on('checking-for-update',()=>send({status:'checking',message:'Checking for updates…'}));updater.on('update-available',info=>send({status:'downloading',message:'Downloading Lith '+info.version+'…',nextVersion:info.version}));updater.on('download-progress',p=>send({status:'downloading',percent:Math.round(p.percent),message:'Downloading update · '+Math.round(p.percent)+'%'}));updater.on('update-not-available',()=>send({status:'current',message:'You have the latest version.'}));updater.on('update-downloaded',()=>send({status:'ready',message:'Update ready. Save and restart to install.'}));updater.on('error',()=>send({status:'error',message:'Update check failed. Your edits are safe. Try again later.'}));}
else state={...state,status:'manual',message:app.isPackaged?'This unsigned Mac test build uses manual updates.':'Automatic updates are available in the installed Windows app.'};
async function check(){if(!updater)return state;if(busy||state.status==='ready'||state.status==='downloading')return state;busy=true;try{await updater.checkForUpdates();}catch{send({status:'error',message:'Could not reach the release server. Try again later.'});}finally{busy=false;}return state;}
ipcMain.handle('update-status',()=>state);ipcMain.handle('update-check',check);ipcMain.handle('release-page',()=>shell.openExternal(RELEASES));ipcMain.handle('update-install',async()=>{if(!updater||state.status!=='ready')return false;await prepareQuit();updater.quitAndInstall(false,true);return true;});if(updater){const timer=setTimeout(check,15000);timer.unref?.();const interval=setInterval(check,4*60*60*1000);interval.unref?.();app.on('before-quit',()=>{clearTimeout(timer);clearInterval(interval);});}return {check};}
module.exports={setupUpdates};
