(()=>{
const button=document.createElement('button');button.id='appUpdates';button.textContent='Updates';button.title='App updates and library restore';document.querySelector('.header-actions').prepend(button);
const dialog=document.createElement('dialog');dialog.id='updatesDialog';dialog.innerHTML='<form method="dialog"><div class="dialog-top"><strong>Lith updates</strong><button aria-label="Close updates">✕</button></div><p id="updateVersion" class="small muted"></p><p id="updateMessage"></p><button type="button" id="checkUpdates">Check for updates</button><button type="button" class="primary" id="installUpdate" hidden>Save & restart to update</button><button type="button" id="releasePage">Open downloads</button><hr><p class="small muted">Moving from the portable version? Close it first, then copy its library into this empty installation. Originals and saved looks stay intact.</p><button type="button" id="restoreLibrary">Import existing library</button></form>';document.body.append(dialog);
const prompt=document.createElement('dialog');prompt.id='updatePrompt';prompt.setAttribute('aria-labelledby','updatePromptTitle');prompt.setAttribute('aria-describedby','updatePromptMessage');prompt.innerHTML='<div class="dialog-top"><span class="eyebrow">A NEW VERSION OF LITH</span><button id="dismissUpdatePrompt" aria-label="Dismiss update notification">✕</button></div><h2 id="updatePromptTitle">An update is available</h2><p id="updatePromptVersion" class="small muted"></p><p id="updatePromptMessage" role="status"></p><progress id="updatePromptProgress" max="100" aria-label="Update download progress"></progress><p id="updatePromptHint" class="small muted"></p><div class="update-prompt-actions"><button id="updatePromptLater">Later</button><button id="updatePromptAction" class="primary">Downloading…</button></div>';document.body.append(prompt);
let state=null,installing=false;const notified=new Set();
function show(s){state=s;$('updateVersion').textContent='Installed version '+s.version;$('updateMessage').textContent=s.message;$('installUpdate').hidden=s.status!=='ready';$('installUpdate').disabled=installing;$('checkUpdates').disabled=['checking','downloading','manual','ready'].includes(s.status);button.textContent=s.status==='ready'?'Update ready':s.status==='available'?'Update available':'Updates';
const ready=s.status==='ready',manual=s.status==='available',downloading=s.status==='downloading',error=s.status==='error';$('updatePromptTitle').textContent=ready?'Your update is ready':manual?'A new Lith is available':error?'Update paused':'A new Lith is on its way';$('updatePromptVersion').textContent=s.nextVersion?'Lith '+s.version+' → '+s.nextVersion:'Installed version '+s.version;$('updatePromptMessage').textContent=s.message;$('updatePromptHint').textContent=manual?'This Mac build needs a manual download. Your installed app will not restart automatically.':ready?'Lith saves your current work before restarting.':error?'You can keep editing and try again later.':'Keep editing while the update downloads. Lith will restart only when you choose.';const progress=$('updatePromptProgress');progress.hidden=!downloading;progress.value=Math.max(0,Math.min(100,s.percent||0));const action=$('updatePromptAction');action.textContent=installing?'Saving & restarting…':ready?'Save & restart':manual?'Download update':error?'Try again':'Downloading…';action.disabled=installing||!(ready||manual||error);$('updatePromptLater').disabled=installing;$('dismissUpdatePrompt').disabled=installing;
if((ready||manual||downloading)&&!notified.has(s.nextVersion||'pending')){notified.add(s.nextVersion||'pending');if(!prompt.open)prompt.showModal();}}
const dismiss=()=>{if(!installing)prompt.close();};$('dismissUpdatePrompt').onclick=$('updatePromptLater').onclick=dismiss;prompt.addEventListener('cancel',e=>{if(installing)e.preventDefault();});
async function install(){if(installing)return;installing=true;show(state);try{const accepted=await api.installUpdate();if(!accepted){installing=false;show(await api.updateStatus());$('updatePromptMessage').textContent='The update is not ready to install yet. Please try again.';}}catch(e){installing=false;show(state);$('updatePromptMessage').textContent='Could not save and restart: '+e.message;fail(e);}}
api.onUpdate(show);button.onclick=async()=>{show(await api.updateStatus());if(['ready','available','downloading'].includes(state.status)){if(!prompt.open)prompt.showModal();}else if(!dialog.open)dialog.showModal();};$('checkUpdates').onclick=()=>api.checkUpdates().then(show).catch(fail);$('installUpdate').onclick=install;$('updatePromptAction').onclick=()=>{if(state?.status==='ready')install();else if(state?.status==='available')api.releasePage().catch(fail);else if(state?.status==='error')api.checkUpdates().then(show).catch(fail);};$('releasePage').onclick=()=>api.releasePage().catch(fail);$('restoreLibrary').onclick=()=>api.importLibrary().catch(fail);api.updateStatus().then(show).catch(fail);
})();
