(()=>{
'use strict';
const KEY='lith.workspace.v2',root=document.querySelector('.workspace'),main=document.querySelector('main'),left=document.querySelector('.left'),right=document.querySelector('.right');
const icons={gallery:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',looks:'<path d="m12 3 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5M3 16l9 5 9-5"/>',light:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',color:'<circle cx="9" cy="9" r="6"/><circle cx="15" cy="9" r="6"/><circle cx="12" cy="15" r="6"/>',detail:'<path d="m12 2 9 10-9 10-9-10 9-10Zm0 0v20M3 12h18"/>',effects:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3ZM20 2v4m-2-2h4"/>',mask:'<circle cx="12" cy="12" r="8" stroke-dasharray="3 3"/><path d="m8 16 8-8m-9 3 4-4m2 10 4-4"/>',frame:'<path d="M6 2v14a2 2 0 0 0 2 2h14M2 6h14a2 2 0 0 1 2 2v14"/>',text:'<path d="M4 6V3h16v3M12 3v18m-4 0h8"/>',nodes:'<rect x="2" y="8" width="7" height="8" rx="2"/><rect x="15" y="8" width="7" height="8" rx="2"/><path d="M9 12h6"/>',photo:'<rect x="3" y="4" width="18" height="16" rx="3"/><circle cx="8" cy="9" r="1.5"/><path d="m3 17 6-5 4 3 4-5 4 5"/>',histogram:'<path d="M3 20V13h3V9h3V4h3v5h3v5h3v-3h3v9H3Z"/>',move:'<path d="M12 2v20M2 12h20M8 6l4-4 4 4M8 18l4 4 4-4M6 8l-4 4 4 4M18 8l4 4-4 4"/>',star:'<path d="m12 3 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1 3-6Z"/>'};
icons.curve='<path d="M3 3v18h18M4 18c10 0 6-12 16-14"/><circle cx="12" cy="11" r="2"/>';icons.prism='<path d="m12 3 10 18H2L12 3ZM2 13h7m6 0 7-4m-6 7 6 1"/>';icons.grain='<circle cx="5" cy="5" r="1"/><circle cx="12" cy="8" r="2"/><circle cx="19" cy="4" r="1"/><circle cx="6" cy="17" r="2"/><circle cx="18" cy="17" r="3"/>';icons.double='<rect x="2" y="3" width="13" height="13" rx="2"/><rect x="9" y="9" width="13" height="13" rx="2"/>';
const svg=name=>'<svg class="ws-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(icons[name]||icons.effects)+'</svg>';
const toolInfo={light:['Light','Exposure, contrast and tone curve'],color:['Color','White balance, HSL, grading and printing'],detail:['Detail','Clarity, texture and sharpening'],effects:['Effects','Optics, film finish and double exposure'],mask:['Masks','Local edits with brush, shapes and color'],frame:['Frame','Crop, straighten and print borders'],text:['Text','Type, style and place a caption']};
let customizing=false,saved={},dragId=null,resizeFrame=0;try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')||{};}catch{}
const directions=saved.directions&&typeof saved.directions==='object'?saved.directions:{};const docks={};for(const name of ['left','top','center','looks','right','bottom']){const d=document.createElement('div');d.className='workspace-dock dock-'+name;d.dataset.dock=name;d.classList.toggle('dock-horizontal',directions[name]==='horizontal');d.setAttribute('aria-label',name+' workspace area');docks[name]=d;root.append(d);}root.classList.add('workspace-redesign');
const panels=new Map();let groups=Array.isArray(saved.groups)?saved.groups:[];
function panel(id,name,body,dock,{collapse=false}={}){const el=document.createElement('section');el.className='workspace-panel';el.dataset.panel=id;el.setAttribute('aria-label',name+' panel');const heading=document.createElement('div');heading.className='workspace-panel-heading';const handle=document.createElement('button');handle.className='panel-drag';handle.innerHTML=svg('move');handle.title='Drag '+name+' to another workspace area';handle.setAttribute('aria-label',handle.title);handle.draggable=true;const title=document.createElement('button');title.className='panel-title';title.innerHTML=svg(id)+'<span></span><span class="panel-chevron">⌄</span>';title.querySelector('span').textContent=name;title.setAttribute('aria-expanded',String(!collapse));title.onclick=()=>{el.classList.toggle('panel-collapsed');title.setAttribute('aria-expanded',String(!el.classList.contains('panel-collapsed')));persist();relayout();};if(id==='photo')title.disabled=true;const place=document.createElement('select');place.className='panel-location';place.setAttribute('aria-label','Move '+name+' panel');for(const zone of Object.keys(docks))place.append(new Option(zone[0].toUpperCase()+zone.slice(1),zone));place.onchange=()=>move(id,place.value);const direction=document.createElement('select');direction.className='panel-direction';direction.setAttribute('aria-label','Arrange panels in '+name+' area');direction.append(new Option('↕ Stacked','vertical'),new Option('↔ Side by side','horizontal'));direction.title='Arrange panels in this workspace area';direction.onchange=()=>{const zone=el.parentElement.dataset.dock;directions[zone]=direction.value;docks[zone].classList.toggle('dock-horizontal',direction.value==='horizontal');syncDirections();persist();relayout();};heading.append(handle,title,place,direction);const content=document.createElement('div');content.className='workspace-panel-body';content.append(body);el.append(heading,content);if(collapse)el.classList.add('panel-collapsed');panels.set(id,el);docks[dock].append(el);place.value=dock;handle.addEventListener('dragstart',e=>{if(!customizing){e.preventDefault();return;}dragId=id;e.dataTransfer.setData('application/x-lith-panel',id);e.dataTransfer.effectAllowed='move';el.classList.add('panel-dragging');e.stopPropagation();});handle.addEventListener('dragend',clearDrag);return el;}
// Move existing controls rather than recreating them, preserving edits and event handlers.
const gallery=document.createElement('div');gallery.className='gallery-browser';root.append(gallery);const projects=$('projectPanel'),projectButtons=projects.querySelector('.section-title'),picker=projects.querySelector('.project-picker');picker.append($('newProject'));projectButtons.remove();projects.querySelector('#projectSummary').hidden=true;gallery.append(projects);const filters=document.createElement('div');filters.className='gallery-filters';filters.append($('all'),$('favorites'));gallery.append(filters);const galleryActions=document.createElement('div');galleryActions.className='gallery-actions';const library=$('libraryMode');library.textContent='View gallery';galleryActions.append(library);const pick=$('batchSelect');galleryActions.append(pick);gallery.append(galleryActions);const batch=document.querySelector('.batch-bar');gallery.append(batch,document.querySelector('.film-header'),$('filmstrip'));const status=$('saveStatus');document.querySelector('.photo-bar').append(status);$('all').querySelector('span').textContent='All';$('favorites').querySelector('span').textContent='Favorites';
for(const child of [...left.children])if(child.classList.contains('divider')||child.classList.contains('left-bottom')||child.classList.contains('section-title')&&!child.querySelector('#saveCustomLook')||child.matches('p.muted.small'))child.remove();left.classList.add('looks-browser');left.append($('selectedLooks'));const looksTitle=$('saveCustomLook').parentElement;looksTitle.firstChild.textContent='';
const histogram=document.querySelector('.histogram');const nodes=$('nodePanel');nodes.append($('nodeSetup'));$('nodeTargets').hidden=true;const nodeHint=document.createElement('p');nodeHint.id='workspaceNodeHint';nodeHint.className='workspace-node-hint';nodes.querySelector('.node-heading').after(nodeHint);const active=document.createElement('div');active.id='workspaceActiveNode';active.className='active-node-context';right.querySelector('.edit-heading').after(active);right.querySelector('.edit-heading span').textContent='EDIT TOOLS';
const shortcuts=document.querySelector('.tab-transfer-hint');shortcuts.title='Ctrl-click tools to select multiple sections. Right-click to copy or move.';shortcuts.hidden=true;const actions=document.createElement('div');actions.className='develop-utility';actions.append($('sectionActions'));const help=document.createElement('button');help.id='workspaceToolHelp';help.textContent='ⓘ Shortcuts';help.onclick=()=>window.keyboardSettings.open();actions.append(help);right.querySelector('.tool-tabs').after(actions);const helpText=document.createElement('p');helpText.id='workspaceToolDescription';helpText.className='develop-description';actions.after(helpText);
panel('gallery','Gallery',gallery,'left');panel('looks','Looks',left,'looks');panel('photo','Photo',main,'center');panel('nodes','Nodes',nodes,'bottom').querySelector('.workspace-panel-heading').append(nodes.querySelector('.node-heading'));panel('develop','Develop',right,'right');panel('histogram','Histogram',histogram,'right',{collapse:true});
const customize=document.createElement('button');customize.id='customizeWorkspace';customize.className='secondary';customize.innerHTML=svg('move')+'<span>Customize workspace</span>';document.querySelector('.header-actions').prepend(customize);
const strip=document.createElement('div');strip.id='workspaceCustomizeBar';strip.hidden=true;strip.innerHTML='<strong>Make this space yours</strong><span>Drag panel handles to any highlighted area. Tool sections can be detached too.</span><button id="workspaceReset">Reset layout</button><button id="workspaceDone" class="primary">Done</button>';document.querySelector('header').after(strip);customize.onclick=()=>setCustom(!customizing);$('workspaceDone').onclick=()=>setCustom(false);$('workspaceReset').onclick=reset;
function setCustom(value){customizing=value;document.body.classList.toggle('workspace-customizing',value);strip.hidden=!value;document.querySelectorAll('.section-location').forEach(el=>el.disabled=false);customize.setAttribute('aria-pressed',String(value));for(const handle of document.querySelectorAll('.panel-drag,.tool-section-drag'))handle.tabIndex=value?0:-1;relayout();}
function relayout(){cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(()=>{for(const [name,d]of Object.entries(docks)){d.classList.toggle('dock-empty',!d.children.length);root.dataset[name+'Empty']=String(!d.children.length);}window.lookBrowserUI?.refreshThumbnails?.();if(img){layout();render();}});}
function syncDirections(){for(const [zone,d]of Object.entries(docks))for(const p of d.children)p.querySelector('.panel-direction').value=directions[zone]||'vertical';}
function persist(){syncDirections();const config={groups,directions,panels:Object.fromEntries(Object.entries(docks).map(([name,d])=>[name,[...d.children].map(p=>p.dataset.panel)])),collapsed:[...panels].filter(([,p])=>p.classList.contains('panel-collapsed')).map(([id])=>id),sections:[...document.querySelectorAll('details[data-workspace-section]')].map(s=>s.dataset.workspaceSection),sectionParents:Object.fromEntries(sectionEntries.map(e=>[e.key,(e.section.closest('.floating-tool')?e.parent:e.section.parentElement).id||'develop']))};try{localStorage.setItem(KEY,JSON.stringify(config));}catch{toast('Workspace could not be saved.');}}
function move(id,zone,before=null){ungroup(id);const el=panels.get(id);if(!el||!docks[zone])return;if(before===el)return;docks[zone].insertBefore(el,before);el.querySelector('.panel-location').value=zone;persist();relayout();}

function ungroup(id){groups=groups.map(g=>({...g,ids:g.ids.filter(v=>v!==id)})).filter(g=>g.ids.length>1);renderGroups();}
function groupPanels(source,target){if(!panels.has(source)||!panels.has(target)||source===target)return;const group=groups.find(g=>g.ids.includes(target)),sources=groups.find(g=>g.ids.includes(source))?.ids||[source],ids=[...new Set([...(group?.ids||[target]),...sources])];groups=groups.filter(g=>!g.ids.some(id=>ids.includes(id)));const dock=panels.get(target).parentElement;for(const id of ids)dock.append(panels.get(id));groups.push({ids,active:source});renderGroups();persist();relayout();}
function renderGroups(){for(const p of panels.values()){p.hidden=false;p.querySelector(':scope > .workspace-tabs')?.remove();}for(const g of groups){g.ids=g.ids.filter(id=>panels.has(id));if(g.ids.length<2)continue;if(!g.ids.includes(g.active))g.active=g.ids[0];for(const id of g.ids){const p=panels.get(id);p.hidden=id!==g.active;p.classList.remove('panel-collapsed');const tabs=document.createElement('div');tabs.className='workspace-tabs';tabs.setAttribute('role','tablist');for(const other of g.ids){const b=document.createElement('button');b.textContent=panels.get(other).getAttribute('aria-label').replace(/ panel$/,'');b.setAttribute('role','tab');b.setAttribute('aria-selected',String(other===g.active));b.onclick=()=>{g.active=other;renderGroups();persist();relayout();};tabs.append(b);}const detach=document.createElement('button');detach.textContent='↗';detach.title='Detach this tab';detach.setAttribute('aria-label','Detach this tab');detach.onclick=()=>{ungroup(id);persist();relayout();};tabs.append(detach);p.prepend(tabs);}}}
function clearDrag(){dragId=null;document.querySelectorAll('.panel-dragging,.dock-over').forEach(e=>e.classList.remove('panel-dragging','dock-over'));document.body.classList.remove('dragging');}
for(const [name,dock]of Object.entries(docks)){dock.addEventListener('dragover',e=>{if(!customizing||!e.dataTransfer.types.some(t=>['application/x-lith-panel','application/x-lith-section'].includes(t)))return;e.preventDefault();e.stopPropagation();dock.classList.add('dock-over');});dock.addEventListener('dragleave',e=>{if(!dock.contains(e.relatedTarget))dock.classList.remove('dock-over');});dock.addEventListener('drop',e=>{const id=e.dataTransfer.getData('application/x-lith-panel'),sectionKey=e.dataTransfer.getData('application/x-lith-section');if(!id&&!sectionKey)return;e.preventDefault();e.stopPropagation();const targetPanel=e.target.closest('.workspace-panel');if(e.target.closest('.panel-title,.workspace-tabs')&&targetPanel){let source=id;if(sectionKey){const entry=sectionEntries.find(v=>v.key===sectionKey);if(entry){pin(entry,name);source='section:'+sectionKey;}}groupPanels(source,targetPanel.dataset.panel);clearDrag();return;}if(sectionKey){const entry=sectionEntries.find(v=>v.key===sectionKey);if(entry)pin(entry,name);clearDrag();return;}const target=e.target.closest('.workspace-panel');move(id,name,target?.parentElement===dock?target:null);clearDrag();});}
document.addEventListener('dragover',e=>{if(e.dataTransfer.types.some(t=>t.startsWith('application/x-lith-'))){e.preventDefault();document.body.classList.remove('dragging');}},true);
// Every Develop section can be reordered inside its tool category.
const sectionEntries=[];document.querySelectorAll('details[data-toolgroup]').forEach((section,index)=>{const key=section.id||section.dataset.toolgroup+'-'+index;section.dataset.workspaceSection=key;const summary=section.querySelector('summary');if(summary.firstChild?.nodeType===Node.TEXT_NODE)summary.firstChild.textContent=summary.firstChild.textContent.replace(/^[^\p{L}\p{N}]+/u,'');const mark=document.createElement('span');mark.className='ws-section-icon';const title=summary.firstChild.textContent.toLowerCase(),symbol=title.includes('curve')?'curve':title.includes('prism')?'prism':title.includes('grain')?'grain':title.includes('double')?'double':title.includes('halation')||title.includes('bloom')||title.includes('diffusion')?'effects':section.dataset.toolgroup;mark.innerHTML=svg(symbol);summary.append(mark);const handle=document.createElement('button');handle.className='tool-section-drag';handle.innerHTML='⠿';handle.draggable=true;handle.type='button';handle.title='Drag to reorder this Develop section';handle.setAttribute('aria-label',handle.title);summary.append(handle);const location=document.createElement('select');location.className='section-location';location.setAttribute('aria-label','Dock '+summary.firstChild.textContent.trim());location.append(new Option('In Develop','home'));for(const zone of Object.keys(docks))location.append(new Option(zone[0].toUpperCase()+zone.slice(1),zone));location.onchange=()=>{const entry=sectionEntries.find(v=>v.key===key);if(location.value==='home')unpin(entry);else pin(entry,location.value);};summary.append(location);handle.onclick=e=>{e.preventDefault();e.stopPropagation();};handle.ondragstart=e=>{if(!customizing){e.preventDefault();return;}e.stopPropagation();e.dataTransfer.setData('application/x-lith-section',key);};handle.ondragend=clearDrag;section.addEventListener('dragover',e=>{if(customizing&&e.dataTransfer.types.includes('application/x-lith-section')){e.preventDefault();e.stopPropagation();}});section.addEventListener('drop',e=>{const id=e.dataTransfer.getData('application/x-lith-section');if(!id)return;e.preventDefault();e.stopPropagation();const source=sectionEntries.find(v=>v.key===id)?.section;if(source&&source!==section&&source.dataset.toolgroup===section.dataset.toolgroup){section.parentElement.insertBefore(source,section);persist();}else if(source&&source!==section)toast('Move sections within the same tool category.');clearDrag();});sectionEntries.push({key,section,parent:section.parentElement,next:section.nextSibling});});
function revealPinned(){for(const entry of sectionEntries)if(entry.section.closest('.floating-tool')){entry.section.hidden=false;for(const control of entry.section.querySelectorAll('input[id],select[id]'))if(Object.hasOwn(Imaging.defaults,control.id))control.disabled=!img;}}
function pin(entry,zone,remember=true){const id='section:'+entry.key;let host=panels.get(id);if(!host){const title=entry.section.querySelector('summary').firstChild.textContent.trim(),wrap=document.createElement('div');wrap.className='floating-tool';wrap.append(entry.section);host=panel(id,title,wrap,zone);const back=document.createElement('button');back.className='return-tool';back.textContent='↩';back.title='Return this section to Develop';back.setAttribute('aria-label',back.title);host.querySelector('.workspace-panel-heading').append(back);back.onclick=()=>unpin(entry);}else docks[zone].append(host);host.querySelector('.panel-location').value=zone;entry.section.querySelector('.section-location').value=zone;entry.section.open=true;entry.section.hidden=false;if(remember)persist();relayout();}
function unpin(entry){if(!entry)return;const id='section:'+entry.key;ungroup(id);const host=panels.get(id);entry.parent.append(entry.section);entry.section.querySelector('.section-location').value='home';host?.remove();panels.delete(id);advancedUI.setTool(document.querySelector('[data-tool].active')?.dataset.tool||'light');persist();relayout();}
function reset(){groups=[];renderGroups();for(const [zone,d]of Object.entries(docks)){delete directions[zone];d.classList.remove('dock-horizontal');}for(const entry of sectionEntries){const host=panels.get('section:'+entry.key);if(host){entry.parent.append(entry.section);host.remove();panels.delete('section:'+entry.key);entry.section.querySelector('.section-location').value='home';}}for(const [zone,ids]of Object.entries({left:['gallery'],looks:['looks'],center:['photo'],right:['develop','histogram'],bottom:['nodes'],top:[]}))for(const id of ids){docks[zone].append(panels.get(id));panels.get(id).querySelector('.panel-location').value=zone;}for(const [id,p]of panels){p.classList.toggle('panel-collapsed',['histogram'].includes(id));p.querySelector('.panel-title').setAttribute('aria-expanded',String(!p.classList.contains('panel-collapsed')));}for(const entry of sectionEntries)entry.parent.append(entry.section);advancedUI.setTool(document.querySelector('[data-tool].active')?.dataset.tool||'light');persist();relayout();}
if(saved.panels&&!saved.panels.looks){for(const ids of Object.values(saved.panels))if(Array.isArray(ids)){const i=ids.indexOf('looks');if(i>=0)ids.splice(i,1);}saved.panels.looks=['looks'];saved.collapsed=(saved.collapsed||[]).filter(id=>id!=='looks');}
if(saved.panels&&typeof saved.panels==='object'){for(const [zone,ids]of Object.entries(saved.panels))if(docks[zone]&&Array.isArray(ids))for(const id of ids)if(typeof id==='string'&&id.startsWith('section:')){const entry=sectionEntries.find(e=>e.key===id.slice(8));if(entry)pin(entry,zone,false);}const used=new Set();for(const [zone,ids]of Object.entries(saved.panels))if(docks[zone]&&Array.isArray(ids))for(const id of ids)if(panels.has(id)&&!used.has(id)){used.add(id);docks[zone].append(panels.get(id));panels.get(id).querySelector('.panel-location').value=zone;}for(const [id,p]of panels){p.classList.toggle('panel-collapsed',id!=='photo'&&Array.isArray(saved.collapsed)&&saved.collapsed.includes(id));p.querySelector('.panel-title').setAttribute('aria-expanded',String(!p.classList.contains('panel-collapsed')));}}
if(Array.isArray(saved.sections))for(const id of saved.sections){const entry=sectionEntries.find(e=>e.key===id);if(entry&&!entry.section.closest('.floating-tool')){const name=saved.sectionParents?.[id],parent=name==='controls'?$('controls'):name==='advancedControls'?$('advancedControls'):name==='develop'?right:entry.parent;parent.append(entry.section);}}
function decorateTool(button,count=0){const key=button.dataset.tool,info=toolInfo[key];if(!info)return;const index=[...document.querySelectorAll('[data-tool]')].indexOf(button)+1,hotkey=Shortcuts.keys('developTab'+index).map(Shortcuts.label).join(' / ');button.innerHTML=svg(key)+'<span class="tool-name">'+info[0]+'</span><span class="tool-change">'+(count||'')+'</span>';button.title=info[1]+(hotkey?' · '+hotkey:'');button.setAttribute('aria-label',info[0]+(count?' · '+count+' changed settings':''));}
function sync(){revealPinned();if(customizing)document.querySelectorAll('.section-location').forEach(el=>el.disabled=false);const n=documentSettings.nodes.find(n=>n.uid===activeNodeUid),number=documentSettings.nodes.indexOf(n)+1,tool=document.querySelector('[data-tool].active')?.dataset.tool||'light';active.textContent=n?'Editing '+String(number).padStart(2,'0')+' · '+n.label:'Select a photo to begin';$('workspaceToolDescription').textContent=toolInfo[tool]?.[1]||'';const hotkey=Shortcuts.keys('selectNode2').map(Shortcuts.label).join(' / ');nodeHint.textContent=(hotkey||'Node shortcut unassigned')+' · select Node 2, or create the next node. Hover a node + R to rename.';$('nodeAdd').title='Add a node · '+hotkey;for(const b of document.querySelectorAll('[data-tool]')){const keys=[...document.querySelectorAll('[data-toolgroup="'+b.dataset.tool+'"] input[id], [data-toolgroup="'+b.dataset.tool+'"] select[id]')].map(i=>i.id);const count=keys.filter(k=>Imaging.defaults[k]!==undefined&&JSON.stringify(settings[k])!==JSON.stringify(Imaging.defaults[k])).length;decorateTool(b,count);}gallery.classList.toggle('has-selection',!$('batchClear').hidden);}
const oldSetTool=advancedUI.setTool;advancedUI.setTool=tool=>{oldSetTool(tool);sync();};
$('theme').append(new Option('Soft white','white'));try{const theme=localStorage.getItem('luma-theme');if(theme==='white'){$('theme').value=theme;document.documentElement.dataset.theme=theme;}}catch{}
const modeButton=$('editMode');modeButton.textContent='Photo editor';document.querySelector('.brand .studio').textContent='PHOTO STUDIO';
const resize=new ResizeObserver(()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(()=>{if(img)layout();});});resize.observe($('stage'));
window.workspaceUI={sync,decorateTool,move,reset,setCustom,revealPinned};window.addEventListener('shortcutschange',sync);renderGroups();syncDirections();setCustom(false);sync();relayout();
})();
